### ISSUE TITLE
GAME: Quests 

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#1000]
Quests: Help the Talyron Family
Valley Cairnmog's do not count towards quest completion but Valley Cairnmog Alpha's do.
Edit: Or game is selective on what ones count, worth a quick look at.

**Comment by taelon875** [comment]
Quest: Locate the Mandalorian Facility
Upon approaching the facility you get this error:
![image](https://user-images.githubusercontent.com/15068982/63477033-4b865280-c451-11e9-81cb-ca843833d369.png)

**Comment by zunath** [comment]
Got the second issue fixed. Unsure about the first.

**Comment by taelon875** [comment]
The quest is possible to finish either way, so I would consider those closed, we can revisit , the second one was the big issue.

Will hold this post open until I can finish doing all quests.
