### ISSUE TITLE
Game: Hostilitiy

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#1001]
So something in the code is firing to make NPC's hostile at random. I have not attacked anyone except hostile mobs and this guy is out to kill me. (He is a quest NPC outside Coxxion headquarters)  
![hostile](https://user-images.githubusercontent.com/15068982/63476077-91d9b280-c44d-11e9-8fed-d92abd08d7fd.PNG)

**Comment by zunath** [comment]
Did you have rage active by chance?

**Comment by taelon875** [comment]
I do.

**Comment by taelon875** [comment]
DO Chiss NPC's hostile people using force abilities, i mean i like the mechanic....

**Comment by zunath** [comment]
@taelon875 can we double check on this one now that we've upgraded and it's been nearly a year? Close if no longer relevant?
