### ISSUE TITLE
GAME: Rapid Shot with blaster/throwing issues

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1006]
Hi, just something I noticed with throwing: when I activate rapid shot with blasters I get the benefit of rapid shot with throwing without having the rapid throw perk when I switch from blaster weapons to throwing weapons. When I switch ou tmy throwing weapons it goes back to one attack per round.

Artemis Alcantar	viscarawildwoods	233.968963623047	61.9892730712891	-0.31068879365921	137.584594726563	2019-08-20 08:29:23.5566667

**Comment by givemedeath** [comment]
Unable to reproduce this particular behavior, however i did find that the Rapid Throw perk is not working at all.
