### ISSUE TITLE
GAME: Blaster Deflection

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1009]
Blaster Deflection might not be functioning as I spent 3 hours yesterday fighting outlaws without a single deflection. Charisma was 16 at the time and I was using a [Training Foil I].	Iuyihpuru	czs220_maintlvl	71.4078598022461	147.2919921875	0	304.399993896484	2019-08-22 12:45:36.3533333

Look a both blaster deflection and the martial arts version of the same perk. A rework in the calculations might be in order.

**Comment by givemedeath** [comment]
Martial Arts Blaster evasion is Dex vs. Dex. and Force Deflect Blaster is Cha. vs. Dex.
Outlaws have 20 Dex. vs players 16 CHA which is why it is not happening in this particular case.
