### ISSUE TITLE
GAME: Blue pulse glow from Absorb Energy not clearing after ending

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1035]
Blue pulse glow from Absorb Energy remains after discontinue	Sandra Mana	tat_anc_southdis	117.205963134766	95.9697875976563	0	85.5999984741211	2019-08-29 14:24:39.6766667

The VFX should end when the effect ends.

**Comment by givemedeath** [comment]
This is a non-issue currently.
