### ISSUE TITLE
Kotor Creatures Phase 1 hak stuff.

### ISSUE THREAD

**Issue by Terallis** [zunath/SWLOR_NWN#1036]
This is for the first part of my work on new KotOR creature models to be added. 

https://mega.nz/#!PBoAyC6Y!10FeVk0BJjJdi6d1wEh3B_i5I7R6EceBTlmtAI8To-U

**Comment by zunath** [comment]
Reopened over in the hak repo here: https://github.com/zunath/SWLOR_Haks/issues/18#issuecomment-526332439
