### ISSUE TITLE
GAME: Show grid lines when placing furniture

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1044]
![image](https://user-images.githubusercontent.com/3136227/64478906-842a6980-d17d-11e9-952e-4f42c7eadf8a.png)

^ Example of how it looks in Layonara Online. Orth (admin) has sent over the stuff he uses for it. Following is some code snippet (NWScript) and the model/texture he uses for it.

[grid_model.zip](https://github.com/zunath/SWLOR_NWN/files/3586932/grid_model.zip)

Sample code:

[grid_code.txt](https://github.com/zunath/SWLOR_NWN/files/3586933/grid_code.txt)

**Comment by givemedeath** [comment]
Is the grid model meant to be a placeable?

**Comment by zunath** [comment]
It's a tile magic effect. I forget how that works to be honest, but I know you can make effects like lava, water, ice, etc display across the entire area. This effect is just like those I believe. We would want to add it to the haks and then display it during furniture placement
