### ISSUE TITLE
Crawling Phenotype Activation

### ISSUE THREAD

**Issue by Terallis** [zunath/SWLOR_NWN#1051]
Putting this up here at GMD's request, relating to the crawling phenotype. I feel it could add a lot of potential for fun with adding it in through something like a chat command. Obviously have it slow down the character so they don't crawl at mach speed, though. It could also potentially be interesting, as well, if it added something like a small AC bonus against certain damage types (like specifically blaster fire) or beyond that. AC penalty to melee types, though. I think that's similar to how it functioned on RotR, when I think of it, but I can't fully remember. Either way, a system for this could be really interesting and even just having the ability to crawl like that could add to the RP of everything.

**Comment by givemedeath** [comment]
Do you know which phenotype is for crawling? 
It's not currently listed in phenotypes.2da

**Comment by Terallis** [comment]
Uhh... Did we actually not end up adding it? I could've sworn it was part of D20 Modern haks, and those are part of what we originally added. But I dunno. Possible that someone else might know? Or it's very possible we have it, but it was never added to the phenotypes.2da to be called on.

**Comment by zunath** [comment]
I don't know what action to take on this, so I'm closing it. Please reopen if we still want to do this.
