### ISSUE TITLE
Careful Scavenger currently does nothing

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#1054]
Scavenge points now destroy themselves on every use - a good thing since the old code to replenish them didn't seem to work.  However, that now leaves the Careful Scavenger perk doing nothing - we check it in Placeable.ScavengePoint.OnOpened line 94 and then ignore the result.

Thoughts on what it could do instead?  Perhaps find something from a totally different table - maybe you find some electronics, or an enhancement component, with a small % chance?

**Comment by Mithreas** [comment]
Maybe a chance of extra loot rolls when looting NPCs?

**Comment by taelon875** [comment]
I like the extra loot roll for NPC's. Think that would be a good use of it.

**Comment by givemedeath** [comment]
This is probably easy to implement but needs better definition.

**Comment by zunath** [comment]
Not sure what to do with this one either. I leaned on the side of just disabling it personally. Thoughts?

**Comment by givemedeath** [comment]
It's 21 perk points for 30% chance on a perk line that helps with zero other mechanics so it should probably be something fairly decent. What about chance to roll across all enhancement gems loot table or something like that? This could possibly be abused with high levels of Scavenging Expert but getting both of these is a serious perk point investment that should probably have a decent reward.

**Comment by zunath** [comment]
We can adjust the pricing on it if necessary. That's not a huge lift. I honestly don't have a preference so I'm good with doing something like what you suggested

**Comment by zunath** [comment]
Closing this ticket out as it will no longer be relevant in the revamp.
