### ISSUE TITLE
22 New Male and Female Torgruta Heads

### ISSUE THREAD

**Issue by Azimn** [zunath/SWLOR_NWN#1064]
Hello not really an issue but I finally completed these heads for Torgrutas. 

[Torgrutaheads.zip](https://github.com/zunath/SWLOR_NWN/files/3992208/Torgrutaheads.zip)

**Comment by zunath** [comment]
Moved this ticket over to the hak repo. https://github.com/zunath/SWLOR_Haks/issues/35
