### ISSUE TITLE
Inconsistent Luck definitions and application

### ISSUE THREAD

**Issue by Mozzeltoff** [zunath/SWLOR_NWN#1071]
Blocking Recovery, Expulsion Maneuver and Scavenging on opened all use effectiveStats.Luck
`int luck = PerkService.GetCreaturePerkLevel(creature, PerkType.Lucky) + effectiveStats.Luck` 

Molecular Reassembler uses '_playerItemStats.Luck'
`int luck = PerkService.GetCreaturePerkLevel(_player, PerkType.Lucky) + (_playerItemStats.Luck / 3); `

All other instances affected by luck only use the value give by PerkType.Lucky ignoring item bonuses (Recovery Blast, Tranquilliser, Mass Tranquilliser, Healing Kits, Force Packs, Force Push, Force Body, Force Speed, Smelting and Crafting (property transfer)).
[More info](https://forums.starwarsnwn.com/t/perk-guide-lucky/72/3)

So the issues are:
1. Using consistent definitions for ease of editting- in this case, choosing which value to use to apply Item Bonus Luck.
2. Reviewing what should be affected by the Lucky Perk alone and what should include Luck from items.

**Comment by zunath** [comment]
The first two are the same thing... the variables are just named differently.

For the rest of it, I agree with it in spirit - being consistent across the board - but my fear is that we decided to not include equipment "Lucky" bonuses in some places for balancing reasons. Not saying we couldn't include equipment and put a cap on it or something, but with so many of those being raw stats, it makes me think that was the reasoning.

**Comment by zunath** [comment]
Luck will be removed in the revamp.
