### ISSUE TITLE
GAME: Faction System

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#1097]
Make Factions Joinable by a representative, and you can only join 1 faction.  
Make levels of the faction to automate ranks and promotions as well as stores provided for gear as quartermasters. 
-Factions DM Compatible (Editing Ranks for Offline Users)
-Have should have some kind of job/task assignment for a 'salary'.
-Tie in a ID or some feature for players in a faction to land at their faction area.
-Faction Ships

**Comment by givemedeath** [comment]
What are the actual factions to support?

**Comment by zunath** [comment]
This will be included in the revamp.
