### ISSUE TITLE
DM Spawned AI

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#1098]
Any DM spawned ai just acts dumb and does not attack unless it is attacked first.

**Comment by givemedeath** [comment]
Currently their AI is explicitly disabled.
Should they behave exactly like creatures spawned by the spawning system?

Possible enhancement: spawn with either ai on or off by default and add a chat command to toggle on and off.

Thoughts?

AIService:

        private static void OnCreatureSpawn()
        {
            NWCreature self = OBJECT_SELF;

            // Don't modify AI behaviour for DM-spawned creatures.
            if (GetLocalBool(self, "DM_SPAWNED") == true) return;

**Comment by taelon875** [comment]
Would the command be like a module wide toggle for DMs?

**Comment by givemedeath** [comment]
Could be... Could be area wide... Could be creature specific, or could be all three.

**Comment by zunath** [comment]
There's a built in way to enable/disable AI. Might need nwnx for it, but we should at a minimum leverage that functionality

**Comment by zunath** [comment]
Closing this ticket out as it will no longer be relevant in the revamp.
