### ISSUE TITLE
GAME: Rogue-style skills & perks

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#110]
Need to put together some rogue-style skills & perks.

These would probably include hacking/slicing, lockpicking, stealing, etc. They would need to fit our game world and mechanics. They also need to be anti-spammable.

**Comment by zunath** [comment]
I think all of these actions should fall under a global "Subterfuge" skill. Open to a better name, as well.

I picture this as a 50-max skill. Perk categories would include Slicing, Lockpicking, and Stealing. I think we can draw from KOTOR for inspiration for a lot of this.

It'll require some changes to our random scavenge sites. Some of those should be randomly locked, requiring players to slice or pick the lock open, depending on the object. 

Stealing should be a perk which enables you to get rarer items off of enemies. That means the loot system needs to be adjusted to handle this. We also need to update all existing loot tables to incorporate this ability. Unsure if we should allow this to be used on other players.

**Comment by Terallis** [comment]
This is very much what I had in mind as a whole, as well. The idea of a generalized Subterfuge skill works perfectly for these sorts of things. Though, I do wonder how we'd go about handling something more like stealth. That said, that could be something to think about at a later time.

**Comment by zunath** [comment]
I think Stealth - that is, hide and move silently - should be treated as a perk and shouldn't grant you Subterfuge skill XP simply because I think it'll be abused pretty heavily. You could make the players have to move around to gain the XP but even that seems really boring to me. It's better served as a perk you can purchase, with higher ranks granting better Hide/MS NWN skill ranks.

**Comment by Terallis** [comment]
So would that mean the re-enabling of the NWN stealth, then, if we look to add to the base skill ranks like that? I mean, I'm down for that personally. Though we may also need to change the tlk to mention those skills as what they are, seeing as they are currently "Unused"

**Comment by zunath** [comment]
I don't think that's really necessary. Whatever numbers we manage behind the scenes isn't relevant to the player. They just need to know they're running "Tier 2 of Stealth" or whatever. The calculations we make can be done outside their purview. 

We can also turn it into another perk if it's difficult to hook that action.

**Comment by YellowKingThe** [comment]
I would be weary of using nwn stealth, due to stat inflation it would be hard to get it to work right.
Could we do it the same way that things like the npcs and placeables that disappear until you have a specific flag work?
Worst comes to worst we could look into removing stats from spot/hide
I would say still don't use ms/listen at worst it makes it harder to sneak because the opponent gets two checks instead of one, at best it does nothing.
