### ISSUE TITLE
Hotfixes for Helmet Pack 1

### ISSUE THREAD

**Issue by Xisifer** [zunath/SWLOR_NWN#1157]
- [x] Extend hood of Jedi Temple Guardian `helm_030`  to prevent floating on all genders; allow for use with non-robe chests
- [x] Adjust placement of Iskellia (Scarred) `pfh0_head221`
- [x] Slightly adjust placement of Iskellia (Masked) `helm_220`

**Comment by Xisifer** [comment]
[XisHeadFixes.zip](https://github.com/zunath/SWLOR_NWN/files/7445106/XisHeadFixes.zip)

Fixes uploaded.

**Comment by zunath** [comment]
Reopening the ticket because the work still needs to be imported to the haks/module

**Comment by Xisifer** [comment]
Fixes re-uploaded:
[XisPack1-Fixes.zip](https://github.com/zunath/SWLOR_NWN/files/7510301/XisPack1-Fixes.zip)

**Comment by zunath** [comment]
Assets were imported with head pack 3
