### ISSUE TITLE
New Planets / Area / NPC additions

### ISSUE THREAD

**Issue by AznablZ** [zunath/SWLOR_NWN#1158]
- [x] Starship - Sith Interceptor Interior

- [x] Starship - Second Chance Interior
 
- [x] Viscara - Sith Lake Base Interior

- [ ] Ord Mantell - Starport

- [ ] Ord Mantell - Mountain Region/Village

- [ ] Ord Mantell - Swoop Race Stands

- [x] Ord Mantell - Embassy/Shopping ar

- [x] Ord Mantell - The Mantell Lagoon/The Secret Thirst

- [x] NPC - Darth Revan

- [x] NPC - Bastila Shan
[bastila.zip](https://github.com/zunath/SWLOR_NWN/files/7438600/bastila.zip)
- [x] NPC - Jedi Master Zez-Kai Ell

- [x] NPC - Jedi Master Vandar

- [x] NPC - Master Vrake Remodel
 
- [x] NPC - Dac Baine

- [x] NPC - Gero the Hutt

- [x] NPC - Mantellian Enclave Guard

- [x] NPC - Gero's Enforcer (3 variants)

- [x] NPC -

**Comment by zunath** [comment]
@AznablZ Is this ready to be merged?

**Comment by zunath** [comment]
Closing this ticket per @AznablZ 's request. New ticket(s) will be added for the content ready to be merged.
