### ISSUE TITLE
Revamp - Correct docker-compose up issue for V2

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1160]
Out of the box, docker-compose up reports the following error:

key cannot contain space 

This is likely due to a change in the docker-compose.yml file format. Investigate and determine what actions are necessary to fix this issue.

The current workaround is to disable V2 docker compose files.

**Comment by tarwich** [comment]
I stumbled upon your issue while trying to resolve a similar issue myself. This [reddit article] helped me figure out the solution.

[reddit article]: https://www.reddit.com/r/docker/comments/q306l0/key_cannot_contain_a_space/

My .env file had a key like this:

```env
DATA=had spaces in it
RIGHT_DATA='should be quoted'
```

I'm not sure if trailing spaces such as this one will cause the issue:

https://github.com/zunath/SWLOR_NWN/blob/d7a59c9a50c91e7e8d8f9da9a61157fe79bf1b01/SWLOR.Game.Server/ServerFiles/Docker/docker-compose.yml#L11

![image](https://user-images.githubusercontent.com/334149/139542940-4799dabf-9cd2-42bf-9634-8fece0799e14.png)
_(Image for reference)_

Generally trailing spaces should be removed when possible. Still you may end up finding the issue in other .env files such as this one:

https://github.com/zunath/SWLOR_NWN/blob/d7a59c9a50c91e7e8d8f9da9a61157fe79bf1b01/SWLOR.Game.Server/ServerFiles/Docker/docker-compose.yml#L22

Remember: The error says you have spaces in the key, but you're not allowed to have unquoted spaces in the values either.

Hope that helps!

**Comment by zunath** [comment]
Much appreciated! Will take a look into it. Thanks!

**Comment by coindegen** [comment]
in my case the problem was due to a local .env file, which `docker-compose` was automatically reading first: https://stackoverflow.com/a/70242918/1011766. Renaming it  fixed the problem.
