### ISSUE TITLE
Player Starship Interior Pack #1

### ISSUE THREAD

**Issue by AznablZ** [zunath/SWLOR_NWN#1162]
- [ ] Starship Freighter 2 Interior
- [ ] Starship Freighter 3 Interior
- [ ] Starship Escort 2 Interior
- [ ] Starship Escort 3 Interior

Adding 4 new Player Starship interiors. Files uploading soon.

**Comment by zunath** [comment]
@AznablZ Please attach the files to this ticket when ready to be merged. Thank you!

**Comment by zunath** [comment]
We received another contribution for these ship areas. If you still plan on making these please open a new ticket and attach the erf to it.
