### ISSUE TITLE
Scorchy's Mon Cala Caves

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1167]
[moncala.zip](https://github.com/zunath/SWLOR_NWN/files/7447939/moncala.zip)

**Comment by Scorchys12** [comment]
Added area, hanging waters.
[moncalahangingwa.zip](https://github.com/zunath/SWLOR_NWN/files/7506621/moncalahangingwa.zip)

**Comment by zunath** [comment]
I was unable to import the hanging waters area but got the other ones added to the revamp module. Sent you a message on Discord, but just to reiterate - please take a look and see if there's any content you're using in the area which doesn't exist in SWLOR's haks.
