### ISSUE TITLE
Revamp - Add height scaling to appearance editor

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1184]
Add a new tab section to the appearance editor for "Configuration" with a scale slider to adjust the scale of a character.

**Comment by zunath** [comment]
Mithreas has some NWScript code which may assist with this.

https://github.com/Mithreas/CoW/blob/master/scripts/zdlg_pc_init.nss

**Comment by givemedeath** [comment]
Taking this one on.

**Comment by givemedeath** [comment]
Need to handle sit scaling also in PlaceableScripts.cs
