### ISSUE TITLE
Revamp - Review All Perks + Implementation

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1202]
Things may have been changed in the spreadsheet without actually updating the code. Run through all of the perks listed here: https://docs.google.com/spreadsheets/d/1uzF7rtXXUaxBS_8cZb83M_9I2bMma6WBOFRkgDY5PP0/edit#gid=0

and ensure their associated code works as expected.

**Comment by zunath** [comment]
Look at consolidating the twin blade and saberstaff perk lines into the one-handed skill due to how much overlap there is.

**Comment by givemedeath** [comment]
I can start on reviewing and testing the perks. I'll set the perk name cell to green highlight in the spreadsheet when they are confirmed and tested.

**Comment by givemedeath** [comment]
SWLOR.Game.Server/Feature/PerkDefinition/OneHandedPerkDefinition.cs

Is this needed? Is it a copy of the item being passed in here or is this just going to remove the 1.5 bonus always when unequipping?

DoubleWeapon
 .TriggerUnequippedItem((player, item, slot, type, level) =>

                    // Always remove the item's one-half bonus
                    if (Item.OneHandedMeleeItemTypes.Contains(itemType))
                    {
                        WeaponPlugin.SetOneHalfStrength(item, false, true);
                    }

**Comment by zunath** [comment]
As part of this check we need to ensure the names/descriptions of perks match in the spreadsheet, in the code, and in the TLK file. I've already come across one instance where they weren't in sync.

**Comment by zunath** [comment]
We need to rename all references of Bacta to Kolto.

**Comment by Xisifer** [comment]
Changed a bunch of icons to SWTOR icons. Also added a bunch of my own.

https://github.com/Xisifer/SWLOR_Haks/tree/new-icons

**Comment by zunath** [comment]
Ability ranges should all be reviewed as part of this too.

**Comment by zunath** [comment]
Valid targets should be reviewed and updated as part of this ticket too.

Hostile abilities shouldn't be usable on the activator. Review weapon abilities like Riot Blade for an example of this.

**Comment by zunath** [comment]
Modify one-handed abilities to restrict usage to what whatever weapon is in the creature's right hand instead of checking both hands.

**Comment by Mithreas** [comment]
Suggest we move Point Blank Shot to Ranged 5 or less.  It's a critical feat for ranged users and they need to get it earlier than level 10.

**Comment by zunath** [comment]
Treasure Hunter perk is listed in the code but doesn't seem to be available to PCs to buy.

Zun note: I've added this to the spreadsheet under the Gathering skill.

**Comment by Mithreas** [comment]
Should add an Inspire perk line that uses the Leadership skill and functions similarly to bard song.

Lasts: 5 rounds.  Adds a combat point to all nearby enemies [not just already-tagged ones].
Level 1 - damage bonus to nearby allies equal to user's SOC modifier.  Cost 1 stamina.
Level 2 - damage and AC bonus to nearby allies equal to user's SOC modifier.  Cost 2 stamina.
Level 3 - damage, AC and attack bonus to nearby allies equal to user's SOC modifier.  Cost 3 stamina. 
The leader does *not* get the benefit from their own ability.

**Comment by zunath** [comment]
Force characters should have the ability to use the first tier of the Resuscitation Devices perk line.

**Comment by zunath** [comment]
Review all force perks and ensure they factor in the caster's WIL when used.

**Comment by zunath** [comment]
Bug report: Throw Saber is doing about 272 damage at level 1.

**Comment by zunath** [comment]
Force leap:

It's not working well, taking into account that the 5 meter requirement is also very little for a jedi jump, when I get close I can't use the skill, because it says I need to be far from the target.

**Comment by zunath** [comment]
All skills are not instant, but with a charge time to be executed.

Zun note: Ensure casting times match what's listed on the spreadsheet.

**Comment by zunath** [comment]
(Moving from main bug report ticket to here)
Saber Strike I has no animation

**Comment by taelon875** [comment]
Flamethrower does not trigger the damage effects.

**Comment by taelon875** [comment]
Kolto Grenade gives Ion Grenade Perks

**Comment by zunath** [comment]
The Double Thrust polearm ability has an activation time, but no animations

**Comment by zunath** [comment]
Pistol Double Shot has no animation.

**Comment by zunath** [comment]
Flamethrower doesn't seem to have VFX or do any damage.

Zun note: Could already be fixed - I accidentally forgot to update the NWSync server after updating the code at one point. Verify if still an issue.

**Comment by taelon875** [comment]
Both Rifle Perks, Tranquilizer Shot and Crippling Shot both have a 5 meter range to use.

**Comment by taelon875** [comment]
If max SP distributing RPXP will just remove amount told to distribute without levels.

**Comment by taelon875** [comment]
Flurry of Blows does not give a useable feat when bought, is this supposed to be a useable perk?

**Comment by taelon875** [comment]
Leg Sweep Not showing in Perks list

**Comment by taelon875** [comment]
RPXP Distribution is giving more xp then value inputted.  Ex. Put in 150 to armor and it gave 187 armor. 
--Possible cause Food XP Increase.

**Comment by zunath** [comment]
Taelon has made it through One-Handed, Two-Handed, Ranged, Martial Arts, and Devices. We still need to test the remaining perk lines for issues.

**Comment by zunath** [comment]
Force Burst IV has no effective range unliek the others

**Comment by zunath** [comment]
Force Breech

1 768 agaist Mynock on astoriod (range if centered anyone on the map)
2 640
3 641
4 804 (range melee)

**Comment by zunath** [comment]
Bug report:

None of the Compraheand languages are fireing off consistently I click on them and nothign happens i got it to pop once but not sure how clearly not working as intended they also need beter cost documentation on the skill itself in the hot bar

levle 3 and 4 do not show any FP cost in the hot bar

Levle 1 and 2 fire off but 3 and 4 do not and the FP cost is very high even on levle 2 considering how long it takes someoen to type this will not be very useful as is for haveing a real converations with a player

**Comment by zunath** [comment]
Comprehend Speech is throwing exceptions when it's in use. This could have been because the feat granted when you purchase the perk was incorrect (this piece has been fixed). Confirm the issue and make a fix if necessary. Example exceptions below:

2022-04-28 21:48:11.287 +00:00 [INF] C# Script 'mod_heartbeat' threw an exception. Details: 

Exception type: System.Collections.Generic.KeyNotFoundException
Message       : The given key 'ComprehendSpeech1' was not present in the dictionary.
Stacktrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SWLOR.Game.Server.Service.StatusEffect.TickStatusEffects() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\StatusEffect.cs:line 187
   at SWLOR.Game.Server.Core.Internal.RunScripts(String script) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Core\Internal.cs:line 133




2022-04-28 21:55:53.173 +00:00 [INF] C# Script 'mod_heartbeat' threw an exception. Details: 

Exception type: System.Collections.Generic.KeyNotFoundException
Message       : The given key 'ComprehendSpeech4' was not present in the dictionary.
Stacktrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SWLOR.Game.Server.Service.StatusEffect.TickStatusEffects() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\StatusEffect.cs:line 187
   at SWLOR.Game.Server.Core.Internal.RunScripts(String script) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Core\Internal.cs:line 133

**Comment by zunath** [comment]
Appearance editor is throwing this exception - something related to part 18. Could be an off by one error.


Exception type: System.Collections.Generic.KeyNotFoundException
Message       : The given key '18' was not present in the dictionary.
Stacktrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SWLOR.Game.Server.Feature.GuiDefinition.ViewModel.AppearanceEditorViewModel.LoadBodyParts() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Feature\GuiDefinition\ViewModel\AppearanceEditorViewModel.cs:line 451
   at SWLOR.Game.Server.Feature.GuiDefinition.ViewModel.AppearanceEditorViewModel.Initialize(GuiPayloadBase initialPayload) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Feature\GuiDefinition\ViewModel\AppearanceEditorViewModel.cs:line 213
   at SWLOR.Game.Server.Service.GuiService.GuiViewModelBase`2.Bind(UInt32 player, Int32 windowToken, GuiRectangle initialGeometry, GuiWindowType type, GuiPayloadBase payload, UInt32 tetherObject) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\GuiService\GuiViewModelBase.cs:line 199
   at SWLOR.Game.Server.Service.Gui.TogglePlayerWindow(UInt32 player, GuiWindowType type, GuiPayloadBase payload, UInt32 tetherObject) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\Gui.cs:line 326
   at SWLOR.Game.Server.Feature.GuiDefinition.ViewModel.CharacterSheetViewModel.<OnClickAppearance>b__91_0() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Feature\GuiDefinition\ViewModel\CharacterSheetViewModel.cs:line 236
   at SWLOR.Game.Server.Service.Gui.HandleNuiEvents() in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Service\Gui.cs:line 230
   at SWLOR.Game.Server.Core.Internal.RunScripts(String script) in C:\Projects\SWLOR_NWN\SWLOR.Game.Server\Core\Internal.cs:line 133

**Comment by zunath** [comment]
Might want to increase the range of Force Burst from 5 meters. Extremely short range

Zun note: Probably missing a max range on this ability. Also check the Dark Side equivalent.

**Comment by zunath** [comment]
Bug Report
Force Body (Current iteration: converts HP into FP) requires the user to target themself with a click. Can be clicked onto other people, but will still convert the user's HP into user FP. Recommend making it automatic self-target for convenience.

**Comment by zunath** [comment]
Bug Report
starport dockhands will not open the shop window

Zun note: For player properties

**Comment by zunath** [comment]
Bug Report
force mind sis taking all not half you FP and just now i had 6 fp left and lost all of it and gained 19 HP not sure what the convertion rate is or if it is intended to take half your totak or all if less then that

**Comment by zunath** [comment]
Bug Report
Force heal is not triggering on activation it takes the FP but you do not get a heal tick till next FP draw, leading to activating the skill lossing the FP for the activation and receving no healing if you do not have 2x the activations cost in FP ready
