### ISSUE TITLE
Updates to Master - Aznable

### ISSUE THREAD

**Issue by AznablZ** [zunath/SWLOR_NWN#1207]
- [x] Veles Colony Sheriff's Office / Bounty Hunter Guild Outpost

- Door to outside needs to be connected
[v_sheriffbhoff.zip](https://github.com/zunath/SWLOR_NWN/files/7557629/v_sheriffbhoff.zip)

![image](https://user-images.githubusercontent.com/91160015/142272749-62fe7f50-cd38-45a1-b46a-7a83ffce0b8d.png)

![image](https://user-images.githubusercontent.com/91160015/142272047-6754654d-8a03-4e3c-a7f9-7aae10f849b0.png)

- [x] Areas for DM Athena Story Event
Corrected version in added comment

- [x] NPC addition for DM Bright
[riefhargith.zip](https://github.com/zunath/SWLOR_NWN/files/7557654/riefhargith.zip)

- [x] NPC update for Dac Baine for DM Tally
[dacbaine.zip](https://github.com/zunath/SWLOR_NWN/files/7557665/dacbaine.zip)

**Comment by AznablZ** [comment]
Update for DM Athena Areas
[randoncity.zip](https://github.com/zunath/SWLOR_NWN/files/7566607/randoncity.zip)

**Comment by zunath** [comment]
Imported to master and revamp, door connection hooked up. Announcer and Corbin will be reviewing the merge.
