### ISSUE TITLE
Sunken Lab Area

### ISSUE THREAD

**Issue by kfauquher** [zunath/SWLOR_NWN#1208]
[moncalasunkenlab.zip](https://github.com/zunath/SWLOR_NWN/files/7565076/moncalasunkenlab.zip)

Sunken Lab for Mon Cala. Door/terminal puzzle, script should be working but test on your side to be sure. Look at each door, under key it has the terminal tag it relates to. 4 doors total.

Needs mobs and boss added.

Any questions PM me on discord.

**Comment by zunath** [comment]
Awesome! Thank you!

**Comment by zunath** [comment]
Superceded but v2

https://github.com/zunath/SWLOR_NWN/issues/1209
