### ISSUE TITLE
18-Nov-21 New Areas + Fixes

### ISSUE THREAD

**Issue by Announcer348** [zunath/SWLOR_NWN#1210]
**Items**
pr_heavy_helm
tusken_gaffi

**Creatures**
tusken_melee
sandworm
nulaaaldette

**Areas**
moncaladaccitysu
jeditemp_int
v_jeditemple_ext
viscaralake
v_sithlake_int

Made use of two new NPC scripts: sw_npcsit and sw_staticholo , OnSpawn events simply telling the NPC to find the nearest sittable object with a certain tag and use it, or apply a permanent Ghostly Visage VFX with no sound to itself. Since they're so simple and don't interact with any exterior custom code, I'm guessing they won't cause any issues. 

[18Nov21.zip](https://github.com/zunath/SWLOR_NWN/files/7566848/18Nov21.zip)

**Comment by zunath** [comment]
Whatever scripts are in here will need to be converted to C#. Even though they don't interact with our systems, the complexity of maintaining two code bases adds too much overhead (see: First Rites quest for an example of why this is a problem)

I don't know what all's in here but I'll take a look at converting the scripts over when I get time. If Holmes or someone else can get to it before me, that's fine too.

**Comment by zunath** [comment]
I've imported these areas to both legacy and revamp. Revamp is currently crashing when opening the Jedi interior. We likely need to review the hak files to figure out what's going on. I've also updated the script + npcs to use the ghostly visage effect.
