### ISSUE TITLE
Revamp - use PER instead of MGT for more combat situations

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#1250]
Native/GetDamageRoll.cs lines 85++
                    // Ranged weapons use Perception (NWN's DEX)
                    // All others use Might (NWN's STR)
                    if (weapon.m_nBaseItem == (uint)BaseItem.Rifle ||
                        weapon.m_nBaseItem == (uint)BaseItem.Pistol ||
                        weapon.m_nBaseItem == (uint)BaseItem.Cannon ||
                        weapon.m_nBaseItem == (uint)BaseItem.Longbow ||
                        weapon.m_nBaseItem == (uint)BaseItem.Sling)

Issue #1: This list should include throwing weapons - e.g. throwing axe, dart, shuriken, grenade... whatever we're supporting.

Issue #2: If the character has weapon finesse, is using a finessable weapon and has PER>MGT we should apply that here.

**Comment by givemedeath** [comment]
from discussions with Zunath, it was decided to remove PER from damage calc for now.
