### ISSUE TITLE
Revamp: Adjust racial stats

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1271]
We're moving to a +1 / -1 attribute system for revamp. All of the existing races need to be updated appropriately to have one stat increased by 1 and another stat decreased by 1.

**Comment by Mithreas** [comment]
Suggestion - any race that gets a Social (Cha) bonus should get +2 in place of +1.  The other abilities are all combat-relevant, so Cha is likely to be a weaker choice - hence suggesting we give it a higher bonus.

**Comment by Mithreas** [comment]
Suggested racial adjustments:
Human: +1 SP
Bothan: +1 Perception, -1 Might
Chiss: +1 Will, -1 Vitality
Zabrak: +1 Might, -1 Will
Wookie: +1 Might, -2 Social
Twi'lek: +2 Social, -1 Will
Cathar: +1 Vitality, -1 Will
Trandoshan: +1 Vitality, -2 Social
Mirialan: +1 Perception, -1 Vitality
Echani: +1 Perception, -1 Will
Mon Calamari: +1 Will, -1 Perception
Ugnaught: +1 Might, -1 Perception
Togruta: +1 Will, -1 Might
Rodian: +1 Perception, -2 Social

Unused combos:
+2 Social -1 Might/Perception/Vitality
+1 Might, -1 Vitality
+1 Vitality, -1 Might/Perception/-2 Social
+1 Will, -2 Social

**Comment by zunath** [comment]
Making one minor adjustment to Human after our discussion earlier. Human will get +1 VIT / -1 PER instead of SP to eliminate the maintenance overhead and to keep consistency.
