### ISSUE TITLE
Revamp - Add gemstone enhancements to harvesting

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1288]
Enhancement gem stones need to be added back to harvesting. These should be assigned random properties within a certain threshold depending on level range. Enhancement level should also be applied to the item generated so that they can only be used in level-appropriate crafting recipes.

Also look into giving a small XP bonus if a gemstone is harvested.

**Comment by Mithreas** [comment]
So, this is a hard one.  Some musings follow.

I think we want to be very careful about what enhancements can be added to what item types.  e.g. if we allowed +1 to an attribute on every item slot, that will very quickly double the stat range we're working with ;)

Maybe we have generic gemstones that do different things on different items?  Or have different types of gemstones but with recipe restrictions per base item type.

Restricted properties:
Attack/enhancement bonus on weapons
Might on gloves
Vitality on belts
Perception on helmets
Social on cloaks
Defense on armour and shields
Cooldown recovery time on rings?

Other properties:
Allow HP, SP and FP on any item.  

Attributes we may or may not keep:
- scanning bonus 
- harvesting bonus
(seems overkill to have both of these.  Collapse them both to Gathering Bonus and have them affect gem chance, harvesting double yield chance, and scavenging double yield chance?)

Rest/Meditate/HP Regen/FP Regen (& add ST Regen).  With passive HP regen going away, we could collapse all of these down into a single Rest bonus that increases the rate of HP, FP and ST regen by 1 point per level.

Crafting bonuses - replace the skill specific ones with +CP and +quality enhancements?  I haven't played much with crafting yet but iirc FF14 has both these bonuses :)

Also need to consider whether scavenging should be able to get cool stuff too, or only gathering.  I'd propose using a scanner on a scavenge point has a chance to 'reveal' a random gem following the same distribution/quality rules as gathering points.

**Comment by zunath** [comment]
Agreed on your concerns. Even prior to you reworking the damage/attack calcs, I had concerns around raw stat increases. There's a couple things I've added:

1. Enhancements are locked to either only weapons or only armor. 
2. They can be installed if the enhancement level is no more than 5 levels above the recipe level. 

As far as stats go, I had considered the following:

Weapons:

- AB
- EB
- DMG (in +0.1 increments)
- (possibly) Specific perk increases. I.E: Riot Blade +1, which would improve damage of the ability

Armor:
- DEF (All different types: Physical, Force, Fire, Poison, Electrical, Ice)
- HP
- STM
- FP
- CP
- Craftsmanship

Gathering, harvesting, and scavenging fall under the same skill now, so I'd suggest doing a single stat for it rather than individually. 

I'm hesitant to even offer +MGT, +PER, +SOC, +VIT, and +WIL at least initially. If we do, it should be for the tier 4 or tier 5 levels and heavily restricted. 

For Rest - not necessarily opposed to having a stat for it but I had planned on Cooking to provide those bonuses. Any stat we introduce may get overshadowed with food buffs.

**Comment by Mithreas** [comment]
You know... I'm not missing gemstones.  Harvesting is needed for the base ingredients so has a purpose, particularly if you want to be a craft focused PC.  And having weird and wonderful enhancements discovered in the world on different creatures and scavenge points gives a sense of discovery.  

Still early days in my exploration of crafting but I'm not seeing gemstones as a priority right now.  I'd rather we continue to build out ingredients on creature drops and scavenge points.

**Comment by zunath** [comment]
I'm good with this. I'll go ahead and close this out for now.
