### ISSUE TITLE
Revamp - adjust encumbrance.2da

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#1289]
With the lower number of stat points in revamp, the carry capacity for low Might characters is too low.  e.g. 10 pieces of ore = 55lbs, 50 med kits = 25lbs.  

I've attached an adjusted version I use for Anemoi, you could use this as is or adjust the values to your taste. Just make them bigger than default please :)
[encumbrance.2da.txt](https://github.com/zunath/SWLOR_NWN/files/7765351/encumbrance.2da.txt)

**Comment by zunath** [comment]
I took your 2da and added the remaining 155 entries we currently have. Thanks for this and good catch.
