### ISSUE TITLE
Revamp - Review and update all NPC stats

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1292]
Review all NPC stats and update them to the new system.

Loot tables should also be considered as part of this, where possible.

**Comment by zunath** [comment]
Wildwoods Kinrath appear to be missing a creature hide.
- They award XP as level 0.
- They do very little damage.
They also are very hard to hit - they probably have a significant natural AC bonus that needs to be adjusted when they are fixed.  Right now the only way my 12 str character can hit them is using Riot Blade.

**Comment by zunath** [comment]
Warocas drop no loot, but I don't get the same exception that I do with Kath Hounds that there are no loot items in the matrix. Suggests that items are there but have invalid resrefs.

**Comment by zunath** [comment]
Valley Cairnmog Alpha is another creature that seems to be missing a damage attribute (though it might have a defense attribute - so it may be missing claws rather than hide).

**Comment by zunath** [comment]
I'm not seeing any drops from Kath Hounds. In particular this makes Szaan Synko's quest to get 5 teeth and 5 furs impossible.

Edit - Oh.

swlor-server_1     | Exception type: System.Exception
swlor-server_1     | Message       : No items are in this loot table.
swlor-server_1     | Stacktrace:
swlor-server_1     |    at SWLOR.Game.Server.Service.LootService.LootTable.GetRandomItem(Int32 treasureHunterLevel) in C:\NeverwinterNights\github\SWLOR.forked\SWLOR.Game.Server\Service\LootService\LootTable.cs:line 17
swlor-server_1     |    at SWLOR.Game.Server.Service.Loot.SpawnLoot(UInt32 creature, String lootTableName, Int32 chance, Int32 attempts) in C:\NeverwinterNights\github\SWLOR.forked\SWLOR.Game.Server\Service\Loot.cs:line 128
swlor-server_1     |    at SWLOR.Game.Server.Service.Loot.SpawnLoot() in C:\NeverwinterNights\github\SWLOR.forked\SWLOR.Game.Server\Service\Loot.cs:line 157
swlor-server_1     |    at SWLOR.Game.Server.Core.Entrypoints.RunScripts(String script) in C:\NeverwinterNights\github\SWLOR.forked\SWLOR.Game.Server\Core\Entrypoints.cs:line 151

**Comment by Mithreas** [comment]
New PR addresses creature stats and hides, but I haven't touched loot tables at this point.  (I haven't even figured out how loot tables are configured yet :)).

**Comment by zunath** [comment]
I've done a pass through the loot tables. Going to close this out. Can open a new ticket if there are problems found during testing.
