### ISSUE TITLE
Revamp - Review all crafting recipe components

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1294]
We need to review all crafting recipes to adjust component requirements. I feel they may require too many items as it is. 

~~We should also set up recipes for Fabrication as part of this ticket.~~

**Comment by zunath** [comment]
FEEDBACK: Refined Veldite counts are pretty high. 7-8 Refined Veldite for a single recipe is 8 charges of a harvester then 4 power cores (or 2 power cores and 2 perk points). Spending a lot of time making metal just to do a single recipe attempt.

**Comment by Mithreas** [comment]
I also noticed that rings and necklaces are two of the easiest recipes to make, but the proficiency perks are 5 levels later than the basic armour types.  It would make more sense to put rings and necklaces later in the progression.

**Comment by Mithreas** [comment]
Related and probably worth reviewing as part of this ticket.  Viscara is the 0-20 zone, but has very few of the 11-20 resource nodes.  We should probably make T2 resources more common in the Valley and Mountains areas, and make the 1-10 resources less common.   (And make the relevant resource harvesters available in stores - right now I seem to only be able to buy basic).

**Comment by Mithreas** [comment]
Mandalorians and their crates should drop T2 resources, not T1.
