### ISSUE TITLE
Revamp: increase base PC speed slightly

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#1306]
Now that I can't use perma-Dash any more, I'm really noticing the large areas.  On Anemoi I have bumped base PC speed slightly in creaturespeed.2da as follows.  Suggest we adopt the same here!

(Yes, this will help ranged PCs with kiting a bit - that's no bad thing the way we're set up here).

```
2DA V2.0
     Label       Name   2DAName  WALKRATE RUNRATE
0    PC_Movement ****   PLAYER     2.50      5.00
1    Immobile    2319   NOMOVE     0.00      0.00
2    Very_Slow   2320   VSLOW      1.50      3.00
3    Slow        2321   SLOW       2.00      4.00
4    Normal      2322   NORM       2.25      4.50
5    Fast        2323   FAST       2.75      5.50
6    Very_Fast   2324   VFAST      3.00      6.00
7    Default     6614   DEFAULT    0.00      0.00
8    DM_Fast     6893   DFAST      5.50     11.00
```

**Comment by zunath** [comment]
I think I'd rather turn this into a perk. I think NWNX has a function to do it. What do you think about that?

We also have speeders coming down the pipeline which will help with travel times.

**Comment by zunath** [comment]
I added the Dash perk line which is a permanent 10% increase to movement speed per level.

**Comment by Mithreas** [comment]
Two ranks of Dash is making all the difference in the world - thanks. 

5 ranks is a lot and could be very strong for a ranged character.... but I think they will need it!
