### ISSUE TITLE
Revamp - rebrand Acid damage to Poison

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#1334]
As discussed - our defense and DMG properties are called Poison, but we're using base game Acid damage.  Would be good to get Acid rebranded to poison (if that doesn't work, we should probably rebrand Poison over to Acid).

**Comment by zunath** [comment]
I've added overrides to the TLK to ensure Acid gets replaced with Poison. If there are any I've missed, open a new ticket.
