### ISSUE TITLE
2 curved sabers, and purple/orange glow sabers

### ISSUE THREAD

**Issue by Reddnn** [zunath/SWLOR_NWN#1419]
[sabers.zip](https://github.com/zunath/SWLOR_NWN/files/9078514/sabers.zip)

**Comment by zunath** [comment]
Reddnn will be resubmitting as compiled models with hopefully less poly counts. Severe performance issues when loading these in the toolset. Also 244 wasn't supposed to be submitted so they're removing that too.

**Comment by zunath** [comment]
Closing in favor of #1439
