### ISSUE TITLE
Additional AI Behaviors

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1434]
Add the following actions to NPC AI:

- Walk waypoints (WalkWayPoints NWScript function)
- Random one-liners when talked to

**Comment by zunath** [comment]
Bug Report
NPC's with a variety of force powers can wind up using only one power if its recast is short enough. This was the case when Lord Inquisitor Koyee kept spamming Force Speed when fighting a player during a test fight.

If possible, randomizing the abilities used based on what is available off cooldown would be nice.

**Comment by Valo56** [comment]
> Bug Report NPC's with a variety of force powers can wind up using only one power if its recast is short enough. This was the case when Lord Inquisitor Koyee kept spamming Force Speed when fighting a player during a test fight.
> 
> If possible, randomizing the abilities used based on what is available off cooldown would be nice.

This was an issue with the AI not having the ability to use stuff like Force Drain at all. This has been resolved in my recent PR. However, it would be nice if AI were a bit more aggressive in using whatever abilities they had. They tend to take a long time between queuing the ability, using it, and preparing to queue another.
