### ISSUE TITLE
Vibrosword Appearances: 1H, 2H, Twinblade

### ISSUE THREAD

**Issue by rainbownights** [zunath/SWLOR_NWN#1436]
[many a vibrosword.zip](https://github.com/zunath/SWLOR_NWN/files/9159243/many.a.vibrosword.zip)
IT JUST WORKS

**Comment by zunath** [comment]
![image](https://user-images.githubusercontent.com/3136227/180589330-d6f7b6ce-58ba-44a9-ad97-2f566367fd8a.png)

Model does not work in game. Icon is also missing.

**Comment by rainbownights** [comment]
Try again with these. Icons included.
[vibrosword CBT edition.zip](https://github.com/zunath/SWLOR_NWN/files/9174426/vibrosword.CBT.edition.zip)
