### ISSUE TITLE
8 Rifles and 2 Lightsaber Models

### ISSUE THREAD

**Issue by Cartoonkarl** [zunath/SWLOR_NWN#1457]
[Rifle Models.zip](https://github.com/zunath/SWLOR_NWN/files/9207164/Rifle.Models.zip)
[Lightsaber Models.zip](https://github.com/zunath/SWLOR_NWN/files/9207167/Lightsaber.Models.zip)

**Comment by zunath** [comment]
[Rifle.Models(1).zip](https://github.com/zunath/SWLOR_NWN/files/9285916/Rifle.Models.1.zip)
[Lightsaber.Models(1).zip](https://github.com/zunath/SWLOR_NWN/files/9285917/Lightsaber.Models.1.zip)

These files were submitted in a PR. They may be the same as the other ones in this issue, not sure.

**Comment by zunath** [comment]
There's a PR open for this already.
