### ISSUE TITLE
DM Notes

### ISSUE THREAD

**Issue by Valo56** [zunath/SWLOR_NWN#1464]
A way for a DM to leave notes on players and, if possible, areas, ideally functioning as follows:

-A player can type /notes and pull up any Public DM notes there are on themselves or on the area they are in.
-A DM can type /notes and a window pops up with a search bar at the top. The DM can type in the search box to begin searching for a map name or character name.
-A DM can press a button in the /notes NUI menu to target a particular player or the ground of a map. Doing so brings up the notes for that player or map, which can be edited.
-The text boxes should be relatively large, the in-game notes that already exists for players is a little too small to work with.
-Pressing save after editing notes will update the entry. If public notes were edited/updated, then the player they were created for gets a message indicating such. If public notes were created for the area, every player currently in the area gets notified.
-Possibly make it so every time a player enters an area, public notes are sent to their combat log. This would allow DM's to freely create and edit ambient messages.

**Comment by givemedeath** [comment]
Players are currently limited to 25 note entries. Does this limit need to be expanded?

How many note entries does an area need to support?

**Comment by Valo56** [comment]
One private (only DM's can access) and one public (the player themselves, or anyone in the area can see) should be enough.

**Comment by zunath** [comment]
I've added editable notes to a new examine menu accessible by DMs. Up to 50 notes can be created per character. These are currently only visible to DMs but Valo has requested the notes optionally be viewable by the player. This is something we can add at a later date. GMD is working on the area notes now.
