### ISSUE TITLE
Viscara - Lake Grounds remodel

### ISSUE THREAD

**Issue by pavvles** [zunath/SWLOR_NWN#1468]
Tidied up the area and made it neater. Removed some excessive and unnecessary placeables. Made the area in general more "livable". 

Please test it on a recent version of the live server to make sure there are no conflicts with any of the city fixtures. I didn't touch any tiles where something was built in, so it shouldn't be a problem, but if there is, please let me know asap so I can amend it.

[viscara_lakegrou.zip](https://github.com/zunath/SWLOR_NWN/files/9228628/viscara_lakegrou.zip)

**Comment by zunath** [comment]
Reached out to the Sith players and did not receive confirmation to include this change.

**Comment by pavvles** [comment]
As per what was written in the Sith chat, I will be making a slight adjustment which was confirmed by two players to be desirable. No one else participated in the discussion and no one seemed to want to comment at the time the question was posed besides them.
