### ISSUE TITLE
WIP: ACPv4.0 animations for SWLOR

### ISSUE THREAD

**Issue by JohnWildkins** [zunath/SWLOR_NWN#1474]
[The oft-requested ACP 4.0](https://neverwintervault.org/project/nwn1/hakpak/original-hakpak/alternate-combat-animations-pack-acp-v40) requires some work to get fully compatible with SWLOR (and NWN post-1.68); by default the animations work reasonably well, however there are notable incompatibilities with robes in particular, due to the way they're handled in-engine. While most are fixed with CEP compatibility patches and creating new `.mdl` entries for new phenotypes, there are still some robes that use 1.69 coat nodes that these animations were not built for.

Conflicting robes: Part 9-12, 20, 21, 174, 236
In addition, Parts 30-33 (loincloths) are currently stiff, this is a low priority fix in comparison.
Part 116 and 170 are also broken, but unknown if the coat fixes will apply to those.

I'm going through the effort of roughly animating them so as to not be rigid / completely broken, however I am by no means an animator. My standards are avoid clipping where possible, and get the job done. 

TODO before PR is ready:

- [ ] Kensei (ksh_) 
  - [ ] Male Human / Elf animation set
  - [ ] Female Human / Elf animation set
  - [x] Male Dwarf / Half-Orc animation set
  - [ ] Female Dwarf / Half-Orc animation set
- [ ] Assassin (njh_) 
  - [x] Male Human / Elf animation set
  - [ ] Female Human / Elf animation set
  - [ ] Optional: Animate two-handed and better one-handed set
  - [x] Male Dwarf / Half-Orc animation set
  - [ ] Female Dwarf / Half-Orc animation set
- [ ] Heavy / Barbarian (hvh_)
  - [ ] Male Human / Elf animation set
  - [ ] Female Human / Elf animation set
  - [x] Male Dwarf / Half-Orc animation set
  - [ ] Female Dwarf / Half-Orc animation set
- [ ] Fencing (fnh_)
  - [x] Male Human / Elf animation set
  - [x] Female Human / Elf animation set
  - [x] Male Dwarf / Half-Orc animation set
  - [ ] Female Dwarf / Half-Orc animation set
- [x] Demonblade (dbh_)
  - [x] Male Human / Elf animation set
  - [x] Female Human / Elf animation set
  - [x] Male Dwarf / Half-Orc animation set
  - [x] Female Dwarf / Half-Orc animation set
- [ ] Warrior (glh_)
  - [ ] Male Human / Elf animation set
  - [ ] Female Human / Elf animation set
  - [x] Male Dwarf / Half-Orc animation set
  - [ ] Female Dwarf / Half-Orc animation set
 
- [ ] Optional, NPC-only: Arcane
  - [ ] Male Human / Elf animation set
  - [ ] Female Human / Elf animation set
  - [x] Male Dwarf / Half-Orc animation set
  - [ ] Female Dwarf / Half-Orc animation set

**Comment by zunath** [comment]
Project was left incomplete. Closing out this ticket. Please reopen if you end up following through and fully implementing it.
