### ISSUE TITLE
Tatooine Cantina-South District Fix

### ISSUE THREAD

**Issue by ImMisterMoyai** [zunath/SWLOR_NWN#1481]
[Tat_SDist_Cantina_Fix.zip](https://github.com/zunath/SWLOR_NWN/files/9274333/Tat_SDist_Cantina_Fix.zip)

Fix for the Cantina transition. Updated transition tag to be area accurate, linked door from cantina back to proper outside door.

**Comment by zunath** [comment]
Need you to redo this change with the latest version of the area. This wipes out all of the additions made for crafting convenience.

**Comment by ImMisterMoyai** [comment]
[Tat_SDist_Cantina_Fix.zip](https://github.com/zunath/SWLOR_NWN/files/9283879/Tat_SDist_Cantina_Fix.zip)

NEW and IMPROVED fix that doesn't put people in the backrooms of the old Northern District!
