### ISSUE TITLE
Bugs #9

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#1482]
Tracking bugs found in revamp testing. New thread created as the old one was getting cluttered.

Bug ticket 1: https://github.com/zunath/SWLOR_NWN/issues/1130
Bug ticket 2: https://github.com/zunath/SWLOR_NWN/issues/1359
Bug ticket 3: https://github.com/zunath/SWLOR_NWN/issues/1380
Bug ticket 4: https://github.com/zunath/SWLOR_NWN/issues/1387
Bug ticket 5: https://github.com/zunath/SWLOR_NWN/issues/1396
Bug ticket 6: https://github.com/zunath/SWLOR_NWN/issues/1402
Bug ticket 7: https://github.com/zunath/SWLOR_NWN/issues/1421
Bug ticket 8: https://github.com/zunath/SWLOR_NWN/issues/1451

**Comment by zunath** [comment]
Bug Report
The Vellen Flesheaters in the Swamp drop the Coxxion Base map instead of the Swamp map.

The Western Swamplands or whatever it's called does seem to drop the correct map however.

**Comment by zunath** [comment]
QUEST ISSUES:

Bug Report
Issue : Quest not accepting.

Location : Hutlar.

NPC : Guylan Verruchi.

Summary : The quest given by Guylan regarding the power structures that have to be checked isn't accepting properly upon completion of the dialogue. Quest log doesn't update, system messages don't verify it's been accepted and the aforementioned power structures aren't interactable.

Bug Report
Hutlar power conduit quest doesn't activate when you talk to the quest-giver. The conversation happens as normal, but the journal doesn't update and the conduits can't be interacted with.

Bug Report
The avenging the captain quest on Veles does not give a reward if you choose the 'continue' option instead of one of the weapons

Bug Report
The quest 'Stuff Keeps Breaking!' demands 1 flawed leather, 1 flawed electronics and 1 agate. When I delivered the quest it said 'it requires 0 agate' and then ate all three items without giving mission completion.

Bug Report
Quests here still require repair kits with Farah that no longer exist.

Bug Report
The hunters guild gives a quest for 6x Mandalorian Polearm Parts and another one for 6x Mandalorian Blaster Parts. Several runs of the Mandalorian compound results in only drops of spears, pistols, and blaster rifles no parts, which don't count towards quest turn in. I believe the nessicary items have been removed from the loot table on rework.

Bug Report
Mandalorians do not seem to be dropping weapon parts such as vibroblades or blaster parts.

Bug Report
The twi'lek in the noxion compound wants repair kits. Those no longer exist.

Bug Report
Mando weapon parts needed for hunters guild quests do not drop from the mandos or the boxes in the Mando facility.

**Comment by zunath** [comment]
Bug Report
The 2nd level of vegetable patch doesn't seem to be spawning. I also would suggest that the swamp vines would share the same loot table or any loot table since they don't seem to have one?

**Comment by zunath** [comment]
Bug Report
Using offensive abilities like double-shot and rocket do not break the stealth of the stealh field generator ability.

**Comment by zunath** [comment]
Bug Report
Force Powers Disturbance and Spark do not appear to reduce a target's accuracy or evasion as it specifies it does.

Disturbance doesn't seem to lower targets accuracy.

**Comment by zunath** [comment]
when I wear a helmet it appears to be SUPER large. I also feel like my Wookiee has shrunk, or appears small to me, but I could also be miss seeing things.

Bug Report
Enlarged helmet on Wookie playermodel. Unsure if this has been reported before as this has occurred several days ago. Also feels like playermodel has shrunk and I'm not as tall as I should be.

Bug Report
There is a bug with the Twi'lek .2da files controlling the camera. When using a Twi'lek character, your camera is off-center and low, when zoomed in, you are staring at their pelvis, causing everything to seem eerily off-center. It's unpleasant, but I'm a little OCD, so that checks out.

Bug Report
That bug about cameras zooming in on twi'lek chests probably isn't limited to twi'leks, on account of the fact I can't stare into my beautiful shining red eyes properly anymore. (Chiss (males?) also got the dodgy camera zoom)

**Comment by zunath** [comment]
Bug Report
For Althea: The use of Elven Race for her character pheno?

**Comment by zunath** [comment]
Bug Report
Character sits in "Chair, Chancellor" sideways.

![image](https://user-images.githubusercontent.com/3136227/178858812-cc7001e9-2fbe-4ea3-8c57-789918637a68.png)

**Comment by zunath** [comment]
Bug Report
A Pirate Ferron tried to ambush my ship. It could deal no damage to me, and when I flew close to it, it blew itself up.

Zun note: Make it so missile launchers cannot hurt their users when an NPC uses them.

Bug Report
I moved out of range of a Pirate Ferron and it started attacking itself and eventually killed itself. I suspect as it had no other target in range.

https://cdn.discordapp.com/attachments/997279624331530270/997279766891745400/unknown.png

Bug Report
Space combat: Still being hit by missiles despite 0% chance after the target is dead.

Bug Report
Was in space and fighting one of the npc pirates, and it killed me. But instead of being killed, I was subdued and was able to get up and walk around in space.

Zun note: Skip subdual mode if in space.

**Comment by zunath** [comment]
Player attacked a DM and caused a server crash. No exception was logged.

Bug Report
DM-set immortality on players appears to conflict with the resolveattack process. When immortal players whacked each other as part of a DM event, it immediately crashed the server.

**Comment by zunath** [comment]
Bug Report
Karrav Maubar in Tatooine MOA doesn't actually open a shop window after saying you want to shop.

**Comment by zunath** [comment]
Bug Report
Force Valor's and Battle Insight's buffs arn't appearing on buff bar when used? I use the skills and it goes on CD, but the icon for the buff of DR dosn't come up in the buff bar for Force Valor,, so, I'm not sure if I'm reciving the buff and theres no icon notification, or, if the buff isn't being applied. As far as Battle Insight, I receive the negitive effects, but, when I examine nearby party members they do not appear to be getting the +to evasion or attack, I think?

Bug Report
Force Valor does not add a buff icon next to your profile.

Bug Report
Buff icon for "Shielding II" does not appear next to portrait on screen.

Bug Report
Shielding II does not add an buff icon near your picture unlike Shielding I.

**Comment by zunath** [comment]
Bags empty weight was stuck at 6.0 after storing guild hunter task items (kath hound furs, mynock wings, etc) onto my starship directly from the bag.
Tried putting items back into bag and then moving them to regular inventory but the weight was still bugged. Then I sold the bag to get rid of it and now ALL vendors only sell a 6.0 weight bag.
I still have 1 bag with normal default weight in my inventory so it only seems to effect the bag I did starship storage from and now the vendors.

https://media.discordapp.net/attachments/1001154694825128017/1001154707194118255/20220719_112628.jpg

**Comment by zunath** [comment]
The Korriban Sith crypt is very buggy, the ghosts get permenantly stuck in terrain quite often due to spawning inside of it. There are also invisible walls aplenty.

**Comment by zunath** [comment]
Bug Report
Permissions tabs in the starships are only showing blackness, they're currently not working. Got a screenshot of it. Relogging and restarting the game doesn't fix it and the issue seems to be affecting several people at the time not just me.

Bug Report
Can't get permissions to enter another player's ship.

Bug Report
boarding permissions to board other ships is buggy. there are two ships my pc has access too, the Fenrir and the Maurader, but neither populate into the "Other Ships" list.

This seems to be an issue a lot of characters have. I have over 6 other ships my pc has access too, but some people who have less then that also run into the same issue.

Bug Report
Further permission weirdness, the ability to enter a ship I have permission to enter seems to just come and go arbitrarily. One day I can, the next I can't.

**Comment by zunath** [comment]
STACKABLE ITEMS:

Intact Warocas Beak, Warocas Spine, Kath Hound Fur all do not stack.
Cornucopia (food ingrediant) still not stacking
Mandalorian Dog Tags do not stack.
Mandalorian blaster parts / lightsaber parts / polearm parts / vibroblade parts do not stack. They USED to be used for mods in legacy, but I don't believe they're used for anything any more besides hunting guild quests
Dried Bonito do not stack.

**Comment by zunath** [comment]
Bug Report
When repairng the ship, the right corner display is not updating correctly. It will show the player off by one volley of repairs, while the person repairing will have the correct number.

Ie: Yurn repairs me for 15 and shows the ship at 16 hull while on Gra'ryyyr screen it shows me still at 1 hp. Untill I dock and refly which then it showes the correct number.

Zun note: Need to send out a refresh event whenever repairs are performed.

**Comment by zunath** [comment]
Bug Report
Enemies (mainly kath hounds) keep getting stuck at the very edge of the map, usually NW top-area. Cannot kill them since they're treated as being out of line of sight since they're on the very edge of the map.

Area Name
Viscara - Wildlands

**Comment by zunath** [comment]
Bug Report
Not sure how to replicate it, but I managed to use my harvester on a plagionite ore node when it was about 1/3 done mining to get multiple uses stacked up and mine it faster than intended

Figured out how to replicate it. Activating the harvester, side-stepping / moving to stop the action bar, then trying again. It doesn't affect the resource payout/make the player get more than they should from a resource node, just makes the process faster.

**Comment by zunath** [comment]
Bug Report
Neutral NPC's will attack players when players heal/buff the NPC's.

**Comment by zunath** [comment]
Bug Report
Shin part https://github.com/zunath/SWLOR_NWN/issues/142 and https://github.com/zunath/SWLOR_NWN/issues/143 are not evenly sized on the cathar body type. The left shin on both of these are smaller than the right.

**Comment by zunath** [comment]
Genevieve Haught (Inkish) [QR64REMH]
Bug Report
Refinery just ate my ore

Bug Report
When adding 2 stacks of raw ore (6 veldite, 8 scordspar) to a refinery, I accidentally walked away from the refinery and rather than returning the ore, it just ate it. The expected behavior would be returning the ore to the inventory if the player moves too far away.

**Comment by zunath** [comment]
Bug Report
The exit of the cantina on Tatooin still exit ont the "old" map

**Comment by zunath** [comment]
Bug Report
Might already have been reported, but with DM-spawned ships (namely those spawned via DMFI tools) there's an issue where they often don't stop attacking after dying, even after their bodies despawn. Players have to transition to a new area in order to avoid being eventually killed.

**Comment by zunath** [comment]
Bug Report
Holocom allows you to call DM Avatars.

**Comment by zunath** [comment]
Bug Report
When I am over-encumbered, toggling the Dash ability off and on seems to remove my encumbered speed penalty entirely.

**Comment by zunath** [comment]
Bug Report
While possessing an Jedi Temple Guard NPC I was unable to hear a Wookie player at all. I assume it's because the NPC doesn't know Shyriiwook, but I wasn't even able to hear the untranslated growling.

**Comment by zunath** [comment]
Whenever using one of my macros to change languages

/language Basic/Mandoa/Huttese

I receive the warning 'Holonet messages may only be sent once per 5 minutes.' in the combat log.

**Comment by zunath** [comment]
Bug Report
I placed a bookshelf. Lagged. Thought I didn't click. Quickly placed again. Ended up with two bookshelves. Or bookshelves stack and I bought two without realizing it.

Zun note: Likely a lag related issue where more than one request is submitted by the player. Need to add a guard against it

**Comment by zunath** [comment]
Bug Report
You can degrade your two-handed skill level below 5 points and still keep and use cleave perk. Has been tested to still activate even after zoning and relogging.

**Comment by zunath** [comment]
Bug Report
If I HoloCall someone and he logs out before he answers, I will be spammed with an unending stream of 'waiting on X to answer his HoloCom'. Relogging fixes this.

Bug Report
It turns out that if I HoloCall someone and he logs out before answering, while relogging fixes the unending stream of messages saying 'Waiting on X to answer his HoloCom', it does not allow me to make any subsequent HoloCalls - it assumes that I am either in a HoloCall or that I am still waiting for mine to be answered. When I click the HoloCall button in my character sheet, it does not permit me to make new HoloCalls.

**Comment by zunath** [comment]
Bug Report
High-end Space Mining Yield might be greater than designer intent.

First trip out, Dual-T5 Shield Regen Enhanced Consular, a battery of three T5 mining lasers, each with dual T4 enchancements.

Dace has AGI 26, WIL 15, PIloting 45. Space Mining 2/2. Treasure Hunter 3/3

Firing 3 mining lasers simultaneously (first time using that technique, previously one mining laser per asteroid).

Typically getting 12-18 ores or rares per asteroid. Usually 12-18 Gostian/Diamonds per Gostian Asteroid.

Possibly intent was one mining laser at a time.

**Comment by zunath** [comment]
Bug Report
Czerka NPC rifles are textureless. Its been in since the last update but this update didn't fix it.

**Comment by zunath** [comment]
Bug Report
Teir 2 heavy droid boots say "droids may not equip that item" even if you have the perk, and are a droid.

**Comment by zunath** [comment]
Bug Report
Veles Tech Vendor has same dialogue and merchant inventory as Street Food Vendor.

**Comment by zunath** [comment]
Bug Report
Simple bug. Instead of displaying the ''Upgrading your Willpower attribute will consume 1 AP", the text blurb says "Upgrading your {abilityname}".

**Comment by zunath** [comment]
Bug Report
When fighting some DM-supplied training droids, after trying to use a force power on it, any further attempt to use a force power or any other ability results in "You Are Busy" in the combat log. Multiple people affected, multiple times, only seems to be fixed by a full relaunch of the game. Reproduced several times.

**Comment by zunath** [comment]
Bug Report
New echani PCs can't select "force sensitive" as their background. In this thread I will show which other species also have this bug.

**Comment by zunath** [comment]
Bug Report
Deflector shield seems to stack, which is likely unintended.

**Comment by zunath** [comment]
T'ad O'resol (Pele Leekpai) [QRR63VLL]
Bug Report
After entering the game on a PRE V2 character, the game wants me to level up.
Area Name
*Character Rebuild
Area Tag
char_migration
Area Resref
char_migration
Position
(12.966528, 24.049854, 12.966528)
Date Reported
2022-08-16 10:33:17
Player ID
ad7fde7e-d050-4291-86a9-70de921e384c

**Comment by zunath** [comment]
Bug Report
DM's who Rest have rest effect messages show up in playerside combat logs.

**Comment by zunath** [comment]
Bug Report
It seems that using Force Spark on the same target causes the durations to overlap and the effects to stack. Even the Force Sparks are cast by the same person.

**Comment by zunath** [comment]
Bug Report
The audio for force lightning is often either delayed or not activating at all.

**Comment by zunath** [comment]
Bug Report
Rank 5 store hunters guild bag is the exact same as the rank 4 hunters guild bag. -40%, but the rank 5 bag is more exspensive

**Comment by zunath** [comment]
Bug Report
Found a broken transition that leads to nowhere. It looks like its supposed to lead into the broken jawa crawler, but I can't guess to that. Its in the thin gap by the cliff-face on the southern side of the map.

Zun note: Probably remove the transition?

**Comment by zunath** [comment]
Bug Report
Apparently equipping evasion gear on a pilot while piloting decreases enemy ships to-hit against you. I didn't think personal equipment was supposed to affect ship combat.

**Comment by JohnWildkins** [comment]
Bug Report
This transition pops the character out under the floor. /Stuck doesn't fix it. I fixed the problem by going back through the transition (which also spawned me under the floor) and then re-logging with a different player name.

Area Name
Tatooine - Tusken Raider Cave - Bottom Floor
Area Tag
TatooineLetstatDungeonMainFloor
Area Resref
tat_tuskcavebot

![image](https://user-images.githubusercontent.com/6022823/188279869-04ae57ca-e6cd-48a8-8021-11bd034e98fb.png)

**Comment by JohnWildkins** [comment]
Bug Report
There is no way to end a holocall being placed unless someone either answers or hangs up on it.

**Comment by JohnWildkins** [comment]
Bug Report
Coriander in Agricultural Rank I shop has "Bad Strref 3"
Cumin in Agricultural Rank I shop has "Bad Strref 2"
Cayanne in Agricultural Rank I shop has "Bad Strref 3"
Tumeric in Agricultural Rank I shop has "Bad Strref 1"

**Comment by JohnWildkins** [comment]
Bug Report
Something on Mandalorian NPCs (likely helmet or armor) causes a pretty severe lag spike when they enter view distance.

**Comment by JohnWildkins** [comment]
Bug Report
T5 food ingredients do not stack. (Tofu, Turnip, Tomato)
