### ISSUE TITLE
GAME: Droids textures stay stuck in the air a long time after death.

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#149]
Loot appears at their feets but they stay in the air for a few seconds...Not really immersive.

EDIT : Textures takes sometimes minutes to disappear.

**Comment by zunath** [comment]
This is due to the models not having any animations. I've been meaning to get it fixed - I reached out to Acidchalk to see if it's something he can do. If he can't then we'll need to pick a different model.

**Comment by zunath** [comment]
This has been fixed. Please update your haks to see the fixed models/animations.
