### ISSUE TITLE
Increase number of junk piles for scrap metal scavenging

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#152]
Scavenging quest from droid maintenance can take quite some time since there are not many junk piles (or there is a too small chance of finding things...)
Either increase number of junk piles (E.G : make a room full of it) or increase chance to find scrap metal when scavenging.

**Comment by zunath** [comment]
Droids also drop scrap metal on death so that's another avenue for completing the quest. I'll add a few more spawn points for the junk too though

**Comment by zunath** [comment]
I added more spawn points for junk to the maint level.
