### ISSUE TITLE
Decrease scanning time and increase range

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#154]
By default, scanning time is almost as long as harvesting.
Even if it gives xp (which should keep players using it), decreasing its duration would be fair...Sweating when we harvest is enough.
On the other hand, we should be able to scan a rock from a few meters away.

**Comment by zunath** [comment]
Scanning gives XP, improves XP gain for subsequent harvesting attempts and increases the chance of getting a resource with an item property bonus for every subsequent harvesting attempt.

The range I can agree on. I'll raise that. But the scanning time decreases with perk or skill increases (I forget which at the moment, but probably perks). It's slow in the beginning but it'll get quicker once you get better at it.
