### ISSUE TITLE
Item Manager/Creator

### ISSUE THREAD

**Issue by Valo56** [zunath/SWLOR_NWN#1598]
The creature manager tool is a HUGE help. Many thanks!

Something else that would be amazing to see is an in-game tool to create items.

Ideally, it would work like follows:
-Type /itemmanager
-NUI window pops up. Looks like the existing Creature Manager NUI window. Instead of Add New Creature, the Add New Template button brings up a new NUI window.

New NUI window has the following fields:
-Item Name
-Item Tag
-Item Description
-Item Properties (lets you select and apply any valid toolset options, choosing base properties and property value)
-Item Appearance (select from dropdowns)

-Also has an "Adjust Template" button letting you change the item appearance.

-Maybe a "Copy Template" button letting you copy an item to the Item Manager.

This would mean us getting through a lot of our tickets will be an absolute breeze, not to mention dropping special, custom loot and consumable items on events will be a lot more doable. Bonus points if it can copy a container item like a backpack and everything inside it so we can have easy to spawn loot bags.

Its functionality could maybe also be expanded to let it and the creature manager interact? Specifically letting us adjust creature skins on NPC's before they're spawned, letting us balance and create entirely new NPC's on the fly without ever needing server updates for this.

**Comment by zunath** [comment]
Moved to: https://github.com/zunath/SWLOR_NWN/issues/1152
