### ISSUE TITLE
Fiberplast Padding

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#164]
The description could use  a small update...
https://gyazo.com/8339e7e4ae3ebd6e6ff28aed85b66524

And it is also not considering it padding while crafting the light armor core:
https://gyazo.com/95a2a2cddfce836d957d3d58a6a73d23

**Comment by zunath** [comment]
I removed the item type restriction for this item. I forget why I had it in the first place, but it isn't really needed. 

Also fixed the description.
