### ISSUE TITLE
Fabrication has no immediate use without housing

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#165]
Players can craft to make furniture and such but have no place to put it all seeing as they will not have the skill to make a tower right away. There needs to be player housing that is rent-able in cities for players to obtain to show of their pretty fabricated beds and mirrors, maybe even to host a dinner party.

Add Small, Medium, and Large housing.

Maybe if we feel real creative offer some different layouts for each....

Also implement the way for players to rent these rooms.

**Comment by zunath** [comment]
I've added apartments. Will deploy to test server soon.
