### ISSUE TITLE
Base Issues

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#171]
Base Placement -
The range for using the place placement tools is very low, maybe increase how far it is allowed.

Drilling - 
Czerka Corporation has installed tech to make drills inoperable. They are not ticking for their DateNextActivity.  

Control Tower - 
Also we need to look into the shield and durability of the control towers to make sure they are balanced. Before changes we should have players attack a tower.

Silo Changes - 
I know the silos are meant to be large, but I feel they may be too large... Try to find an suitable alternative appearance maybe or maybe this is just a personal Quirk....

**Comment by zunath** [comment]
I doubled the targeting range of structures. Fixed drills. Chose a different model for the resource silos. 

After we do some testing on structure shields / durability if we think they're too powerful we can open another ticket to revise them.
