### ISSUE TITLE
GAME: Cybernetic Implants

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#174]
Enable players to install cybernetic implants. This should require Engineering to build to the implants and Medical to install them.

Implants should have the ability to increase player skill levels as well, to differentiate them from normal equipment. Regular crafting rules should apply.

Installing implants should require specialized equipment crafted with Fabrication.

Implant slots should be:

Eyes
Head
Ears
Arms
Chest
Wrists
Waist
Hands
Legs
Feet

**Comment by zunath** [comment]
I'm back tracking on this idea a bit now that we've had a chance to see how things have played out, balance wise. I don't think we need that many implant slots. Perhaps two or three in total?

I think we should also consider each implant to have both a benefit and a penalty, to further differentiate it from regular equipment. For example, a mod might give you +20 FP but decrease your max HP by 40.

I still stand by my opinion that implants should be the only way to further increase your skill levels (aside from leveling them obviously).

**Comment by Terallis** [comment]
That's essentially the idea I had for it overall, though I would say to never increase FP with cybernetics. My idea was more that all cybernetics should reduce FP, due to weakening the connection to the Force. But other benefits are easy enough to do.

**Comment by YellowKingThe** [comment]
I would say lower the raw force stats over just penalize fp, fp is easy to overcome stat damage is significantly more difficult to overcome.

**Comment by zunath** [comment]
This will be done in the revamp.
