### ISSUE TITLE
GAME: Starting area transition conversation choice "Continue", leads to "Continue", a few times again and again

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#184]
![20181018101909_1](https://user-images.githubusercontent.com/43780705/47140914-c6299300-d2bf-11e8-9ac9-18a6b044b3d5.jpg)
![20181018101906_1](https://user-images.githubusercontent.com/43780705/47140915-c6299300-d2bf-11e8-92c3-7ea1739fb195.jpg)

**Comment by zunath** [comment]
Does this ever happen with any other conversations?
