### ISSUE TITLE
Broken early craft for Leather Tunic

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#186]
With a lvl1 Armorsmith perk, players learn the Leather tunic blueprint but are not able to craft it.

You can use ruined fiberplast from starting areas to craft a Fiberplast padding, needed to craft a Light Armor core.
With a fresh character, Light armor core base difficulty is "very difficult"'. Once you add the Fiberplast padding component, it become "impossible".

Players should be able to craft a Leather Tunic at the beggining as it is the most simple armor, made with the most simple components from starting areas.

EDIT : Once corrected, it will be interesting as Starting players will be able to craft a Basic Baton, Leather Tunic and Light Boots/small shield, (which are using the same components as Leather tunic)
Only with Perk 1 in Armor/Weaponsmith,  I think that's fair for a start.

**Comment by taelon875** [comment]
We need to look into making all the "Basic (item)" gear baselevel 0. Instead of the 4+ they are sitting at now. Seeing as they can all be bought in game(minus boots which should be set to baselevel 1). This will allow players to choose to buy the gear, or build it starting out.

**Comment by zunath** [comment]
I was talking to Taelon about this. I think we should do a few things actually.

1.) Lower the base level on the armor blueprints.
2.) Introduce components on CZ-220 which don't give bonuses but also don't increase stats. They're simply for making the items. This will drop the difficulty down too.
3.) Move the 1st level components to Viscara.

**Comment by zunath** [comment]
I've done 2 and 3 on my list. I'm having second thoughts about doing the first one. I'd like to do further testing with these changes before dropping the base levels.

**Comment by zunath** [comment]
I think we can call this one fixed with the changes to components on CZ-220. If it's a problem, please open a new ticket.

**Comment by extaz93** [comment]
Not sure, last time we checked with Taelon, we were finally able to craft a Light armor core with the new "destroyed fiberplast", but assembling Light armor core and light armor segment was still IMPOSSIBLE.
I'll have to check again.

**Comment by zunath** [comment]
I ran some numbers on that and I think you're right. As it is now, the armor will be level 8 which is outside the range of a level 0 armorcrafter. I dropped the base levels of the core and armor down so light armor should be craftable at level 0.
