### ISSUE TITLE
Broken quest : Hunting kath hounds

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#192]
Player can actually say that he killed the Kath hounds and complete the quest even if it's not true.

EDIT : Player can actually say he killed the hounds, and journal will be updated, saying you did it, but you don't actually complete the quest.
Besides, journal says Moira Halax and NPC is called Moira Halaz....

**Comment by zunath** [comment]
I had an incorrect state set in the convo. Good catch. Also fixed the typo. Will be fixed on the next update.
