### ISSUE TITLE
Balancing Hunting Kath Hound quest and Tooths/Fur Kath hounds quest

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#194]
We should balance both quests.

If a player pick one quest after the other, he has to kill at least 25 Kath Hounds ! 
Which is long, boring and a bit hard...

I'd suggest reducing the Hunting Kath Hound quest to 5. Anyway, any player taking the other quest will have to kill at least ten of those. Which brings us to a total of 15 for both quests.

**Comment by zunath** [comment]
I cut the required targets down in half for the Kath Hound hunting quest as well as the CZ-220 kill quests for Mynocks and droids.
