### ISSUE TITLE
GAME: Harvester move command script

### ISSUE THREAD

**Issue by Cablefish1** [zunath/SWLOR_NWN#196]
A small quality of life improvement to the harvester would be a script that'll trigger when the PC uses a harvester while too far from a ressource node. The script would simply make the PC walk to the node and fire up the harvester. It'd also be cool with some flashy animation when harvesting. Or at least some sparks or something.

**Comment by zunath** [comment]
I added a little animation at the start of a harvesting attempt. Doing the move to object is a little more tricky because of a few custom things I'm doing. I may get to it at some point but it's not a quick and easy change.
