### ISSUE TITLE
GAME: Faction system improvement

### ISSUE THREAD

**Issue by Cablefish1** [zunath/SWLOR_NWN#197]
Have a fame/infamy meter apply to the NPC factions would be helpfull in creating a living galaxy. Combined with the daily/repeating quests it'll make world more immersive. 

**Imagine:** 
On Tantoine you can help the Hutt cartels to gain fame but it'll create infamy towards law enforcement/rival criminal organisations.

In the Kyber mines you can chose to help the workers or the owners through quests too.

**The way it would work is:**
All factions have a HQ somewhere. A small faction fame is required to enter the HQ. This fame bump is gotten from the "alignment" you choose on character creation. So the jedis, sith and smuglers can get access to a certain HQ depending on what they chose. The rest of the playerbase will have to complete some quests from people belonging to the faction outside the HQ.

Inside the HQ's theres acces to more quests, daily tasks and stuff that'll help gain even more faction fame which in turn unlocks the more exotic merchants or maybe some ressource nodes in areas controlled by that faction.

**Comment by zunath** [comment]
I like this idea a lot. I'd have to figure out how to integrate our existing fame mechanic into it, but I'm totally on board with this.
