### ISSUE TITLE
GAME: Starship production

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#20]
Special base structures designed for starship production need to be added. This should be a multi-step process and involve a lot of custom components to produce. 

Dependent on the space system being developed first.

**Comment by Mithreas** [comment]
Presumably it's desirable that it involves multiple trade skills rather than just Fabrication?  At least Engineering as well?

**Comment by zunath** [comment]
Yeah, I definitely seeing it as a synergistic process. It'll require a base and the related skills depending on the part you're making. Weapons would require weaponsmith, shields and defenses armorsmith, etc. etc.

Fabrication might make the devices, but the other crafts would be used for the other segments.

**Comment by Mithreas** [comment]
Blaster weapons are in Engineering, which makes it a bit harder to fit Weaponsmith in.  Armoursmith for plating, sure.  Weaponsmithing and Medical are trickier I think :)

**Comment by zunath** [comment]
True. Will have to think on that. I don't plan on doing this work for at least a couple months anyway. We still have a lot of the land game to flesh out first.
