### ISSUE TITLE
Tristan Talyron broken dialog

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#203]
"Who are you" choice brings in circle to "What are you doing out there" and vice-versa

**Comment by zunath** [comment]
He's used in a quest so that dialogue was intentional, but to make it a little more clear I added both options regardless of what you pick.

**Comment by extaz93** [comment]
The fact is, you can't leave dialog besides walking away...

**Comment by zunath** [comment]
That makes more sense, lol. I'll fix that too
