### ISSUE TITLE
Balance : Harvesting ore veins in Mountain Valley gives lots of xp

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#204]

**Comment by extaz93** [comment]
600xp for each harvest, earned 2 skill ranks with 2 harvests, whichs looks a bit too much.

**Comment by zunath** [comment]
What's your skill rank, what item did you harvest?

**Comment by extaz93** [comment]
My skill rank in harvesting was 1. I harvested ore veins.

**Comment by zunath** [comment]
I think the XP is fine. You're harvesting something that's tier 2 or 3 when you're expected to harvest something at tier 1.

What I did instead was lower the range you can harvest from 7 above your skill level to 5 above your skill level. I also introduced higher item decay on your harvester if you try to harvest something above your skill level.
