### ISSUE TITLE
Respawn bug : Moira Halaz (Veles) doesn't respawn after death

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#205]
Killed her and nothing happens.

**Comment by zunath** [comment]
How long did you wait?

**Comment by extaz93** [comment]
Only ten seconds, cause yesterday i saw someone kill a NPC which respawned almost immediatly. Will wait a bit more then.

**Comment by zunath** [comment]
Respawns are a default of 2 minutes, some are 8 minutes and a few others are 10 minutes. Anything instantaneous should be considered a bug

**Comment by zunath** [comment]
I ran a test on that and it looks like she's respawning. She's set to respawn after 500 seconds or 8.33 minutes.
