### ISSUE TITLE
Dog Tags quest bug

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#209]
NPC won't accept Dog Tags.
That may be cause i took her quest AFTER finishing the Mandalorian Leader hunt quest, and already had a few dog tags from that quest in my inventory.
Anyway, any mando dog tags, coming from "anywhere", should be ok for the quest as she just needs Mandalorian Dog Tags for her bet.

**Comment by zunath** [comment]
Another case of "oops I forgot". I added the item to the quest. Will be in next update
