### ISSUE TITLE
GAME: RP and Balance : Viscara only offers violent quests and/or illegal ones 

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#216]
For an interesting Roleplay and Balance, i think NPC quest giver's should always say "who" they are, and who they are working for. So players can choose to do the quest or not, following their RP.

It is quite obvious for the smuggler quest, even if i think he should warn you that what he wants you to do is illegal, because right now, you know it AFTER accepting the quest.

For The Mandalorian Facility Quest, the quest giver should maybe say he works for Czerka, and they want to get rid of those mandos who makes trouble for their business...Right now it's not obvious.

For the Kath Hound Quests, these could be introduced as "Viscara Community Problem".
 The "Kill 15 Kath" NPC could be a Ranger, so it's more introduced as a "Light side quest", cause you get rid of something which is dangerous for civilians.

For the "Get Furs and Tooths" quest, it could be more introduced as a "We need to craft Clothes and blankets" for our refugees. Once again, it would introduce something closer to a "help others/light side" quest

Then, we could add another "Dark side quest", like the smuggler one.
And think about "non violent quests" or non violent ways of resolving quests, because for now it's mostly fighting mobs.

**Comment by zunath** [comment]
There's a lot of room for improvement both in the dialogues and the types of quests offered. I'm the only one building these right now so I've just been getting them functional. I'd love for you or someone else to run through and spruce them up, flesh them out, and such. I just don't have the time to do all of that at the moment.

Let me know if you have any issues with the quest creator or hooking up the dialogues.

**Comment by zunath** [comment]
We've made a lot of fixes to the existing quests. I know there's room for improvement as far as quest variety goes, but that'll be something we improve as time goes on. For this reason I'm going to close out this specific ticket since it's a little too general for my liking.
