### ISSUE TITLE
GAME: Quest difficulty adjustment: Kath hounds

### ISSUE THREAD

**Issue by Zed287** [zunath/SWLOR_NWN#226]
As one of the first quests off the shuttle in Veles, the Kath hounds are quite tough, their damage seems about expected, so I believe all they need is a health reduction, maybe about 60% of what they currently have may help.

**Comment by zunath** [comment]
My usual question: What are your stats, what equipment are you using, and what combat perks are you using?

(I ask not because I think you're doing something wrong, but because I need to understand the stats on your character.)
