### ISSUE TITLE
GAME: Bug : Random resource spawns can be spawned in inaccessible locations

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#230]
PC just walk around and get through it.

**Comment by zunath** [comment]
Need to add a way to exclude spawn locations based on triggers during the baking process.

Another known location is in the Wildlands, near the beaches.

**Comment by zunath** [comment]
Added a placeable to access the beach. Might revisit the trigger solution at some point, but we'll use this for now.
