### ISSUE TITLE
Increase Dog Tags amount in loot tables

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#232]
The getting Dog Tags quest is really long...Doing the Mando Facility once should be enough to get 10 dog tags.

**Comment by extaz93** [comment]
With a Scavenging skill at 1, had to do entirely the Mando Facility twice to get 10 Dog Tags.
I was looting all the corpses + supplies crates.

**Comment by zunath** [comment]
Increasing your scavenging skill will help. On a related note, I think I need to bump up scavenging XP quite a bit. Seems difficult to raise. I think that's more of the problem than the drop rate (the items are already the most common in the loot table)

I'll bump up the XP on scavenging and look at adding more loot chances to the enemies.
