### ISSUE TITLE
CZ-220 - Mining quest improvement

### ISSUE THREAD

**Issue by Cablefish1** [zunath/SWLOR_NWN#238]
**CZ-220**
Just to streamline the new-player experience. The questgiver Avix Tatham should also provide a ressource harvester when giving players the "Deliver 10 ore pieces". In order to make it balanced the ressource harverster could be really low tech and break down after 15 uses. He can give a comment along the lines of "I'll give you my crappy old harvester but in the future you need to buy your own ones from X and Y merchants!"

**Comment by zunath** [comment]
I've added this. Will be in the next update.
