### ISSUE TITLE
GAME: Improvement, Force abilities

### ISSUE THREAD

**Issue by Zed287** [zunath/SWLOR_NWN#239]
Currently Force abilities play a fire animation, as well as have a cast time that pops up in the screen. 

Suggestion;

Remove fire animation,
 Make force abilities instant cast. 
Increase base cooldown to reflect the current cast time.

This will feel a bit more rewarding to the player, and will maintain the current balance as far as force abilities are considered.

For example, Force lightning, 8 second cooldown, and a 5 second cast... Make the casting instant and give it a 13 second cooldown.

**Comment by zunath** [comment]
You're confusing me a bit with this instant cast stuff. First you say they should be instant, but then you say it should have a 5 second cast. 

If there's a delay in the casting timer then that shouldn't be happening. As soon as you select a target it should kick off immediately.

**Comment by zunath** [comment]
Also - if you're using light or heavy armor that will increase your casting time by quite a bit.
