### ISSUE TITLE
Enhancement Calicoid Expiriment XP reward too low

### ISSUE THREAD

**Issue by Zed287** [zunath/SWLOR_NWN#241]
Calicoid experiment xp gain is low for the difficulty of the kill, I would suggest 500 - 800 xp for boss characters total. 

Currently it looks like the total is 220 + 100 as what I gained, but I will attempt it when it respawns again to confirm

**Comment by zunath** [comment]
I added a 20% bonus to all existing boss creatures, including the Calicoid Experiment boss
