### ISSUE TITLE
Missing Item on crafting: Saber Hilt

### ISSUE THREAD

**Issue by Zed287** [zunath/SWLOR_NWN#245]
Engineering blueprints allow anyone to craft the Saber hilt, However hilt does not show up in inventory when created.

**Comment by zunath** [comment]
Wrong resref in the database. Fix'd.

I also fixed an issue where saberstaffs didn't fall under the same perk requirements as lightsabers and I moved all these to the weaponsmith bench/skill, as they should have been to begin with.
