### ISSUE TITLE
GAME: Mynock Mayhem (Bug)

### ISSUE THREAD

**Issue by PjShirt** [zunath/SWLOR_NWN#263]
I believe that the Mynock Mayhem quest may be bugged because it isn't offering the conversation to complete it. I've killed maybe 15-20 Mynocks and the quest giver NPC: Halron Linth only asks me how the hunt goes to which my only option to respond is: Still working on it, I'll get back in touch with you soon. 

The journal entry makes mention of collecting teeth although none of the Mynock's actually drops them which I was told that they don't actually drop them, but, if killing them updates the quest to completion I think that maybe it isn't actually tracking your kills with them? All kills were mainly made using the Force Breach ability.

**Comment by zunath** [comment]
There was a database issue that caused this. Give it another shot now.
