### ISSUE TITLE
GAME: Attacks of Opportunity Interrupt Casting Force Abilities

### ISSUE THREAD

**Issue by PjShirt** [zunath/SWLOR_NWN#290]
If using a force ability during combat and you gain an attack of opportunity against a target then it will interrupt your casting forcing you to have to cast again. 

I'm sure that it's just base nwn mechanics, but, I wanted to mention this.

**Comment by zunath** [comment]
There's not a whole lot I can do about this aside from turning off AOO, which I've considered. But for now it's just something we'll have to live with.
