### ISSUE TITLE
GAME: Add droid graphic to haks

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#292]
https://cdn.discordapp.com/attachments/495642017414774795/504533551602204682/robot1.rar

**Comment by DMSymphony** [comment]
![GIF of c_robot1.mdl](https://gyazo.com/9b53d456d409ef15475c8af75c0c035f)
This looks pretty great, will test locally and make sure it's all set up to rock and roll for hak inclusion soon.

**Comment by Cavcode** [comment]
Droid works in the server.
