### ISSUE TITLE
GAME: New Portrait

### ISSUE THREAD

**Issue by xephnin** [zunath/SWLOR_NWN#293]
Looking to utilize this portrait for an NPC but no harm in letting PCs use it as well.

[https://i.pinimg.com/564x/c2/fa/db/c2fadb2e1c87829dccb7a4d994bb6f31.jpg](url)

**Comment by zunath** [comment]
I've added this to the haks. They'll be included when I do another update. TGAs are one of the biggest haks we have, so it takes me a while to post.
