### ISSUE TITLE
"Unable to reach target" droid in maintenance level. 

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#301]
![20181026181624_1](https://user-images.githubusercontent.com/43780705/47579719-0f778380-d94d-11e8-9b00-1856c0908f8e.jpg)

It was the only one i could notice having that bug.

**Comment by zunath** [comment]
I moved the spawn to a different part of the map. Hoping that helps. The visibility on these tilesets can be finicky at times.
