### ISSUE TITLE
GAME: Remove Veles Colony Interior Building back entrance or make a link

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#302]
For now, we can still enter in the empty building by the back entrance, and it doesn't bring us in the Veles Interior Area. 
Either delete the second door, or make a link to the right area.

**Comment by zunath** [comment]
https://drive.google.com/open?id=1D4yBlipuirRBu2tONFps0RyUYFsLt6Q2

**Comment by zunath** [comment]
Change log: https://drive.google.com/open?id=1HfeBxUSIJ4nL0tjnoPN_xvkq9ahyqKOF

When implementing this, double check that the combat dummies have the proper faction set on them. I think Xeph edited the area before that change was made, so it'll probably revert on import.

Also check the Maintenance level of CZ-220. All spawns should have the adjusted cooldown - again, if Xeph used an older copy of the area, those changes won't be in place.

**Comment by zunath** [comment]
This has been implemented.
