### ISSUE TITLE
Kath Hound Fur

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#316]
Fur still seems to have a low drop rate. We need to up this.

**Comment by extaz93** [comment]
I'd say fiberplast as also a low drop rate in Junk Piles.
It's hard at the beginning, as you need 9 of them to build a leather armor.

**Comment by taelon875** [comment]
Evidently this was changed, or I was told wrong, I got plenty of fur. Teeth were harder but not impossible I think these are fine. And yes I am thinking of a way to change fiberplast.

**Comment by zunath** [comment]
We have #303 to track the fiberplast bug. I don't know how fur can still be a problem. They're the highest dropped item now, and the Kath Hounds have a chance to drop 2-3 items last I checked. Closing this ticket since you seem to think they're OK now.
