### ISSUE TITLE
PWKs missing on Star Wars placeables

### ISSUE THREAD

**Issue by Cavcode** [zunath/SWLOR_NWN#32]
Hopefully the PWKs are in Xeph's Star Wars haks or in the other ones. But until we get 'em, or I make them, you can walk through all Star Wars placeables.

**Comment by zunath** [comment]
Acidchalk's first batch of fixed PWKs

https://www.dropbox.com/s/ed7zpygf9sfkg33/fixed%20placeables.rar?dl=0

**Comment by zunath** [comment]
#185 - Wooden planks have no PWK files. Neither do the terminals in the refinery area of CZ-220. I reached out to Acidchalk to get this one fixed.

**Comment by zunath** [comment]
I think we've fixed the PWKs for placeables in use for the initial launch. Acidchalk is doing a slow burn to fix the rest. I'm going to close this ticket for now and open new ones as they come up.
