### ISSUE TITLE
Search/Scavenging possible bug (resubmitted to server rather than web issues)

### ISSUE THREAD

**Issue by NariKat** [zunath/SWLOR_NWN#322]
I've made a couple of test characters and both seem to get a message "You can't find anything new here. Check back later..." when searching a node for the first time ever after the character creation. I tried this with three different nodes.
Character 1-
Node 1: Failed Search, +50 XP
Node 2: You can't find anything new here. Check back later...
Node 3: You can't find anything new here. Check back later...

Character 2-
Node 1: Successful Search, item +200 XP
Node 2: Successful Search, item +200 XP
Node 3: You can't find anything new here. Check back later...

I don't know if the issue is that the cooldown on searching sites is global and not personal to each character. If that is the case, maybe it's intended? Either way, that's what I've come across.

**Comment by zunath** [comment]
It's a hold over from a previous project that I'm not sure I'll keep. The idea is basically that search points have two things that can happen:

1.) They can be fully exhausted and disappear after you retrieve the items.
2.) They can regenerate items over time. This made more sense for stuff like fiberplast, but it doesn't really make sense for these junk piles.

I'm going to change the junk piles to always destroy after being scavenged, to help with this.
