### ISSUE TITLE
Map Pins

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#323]
Player suggested that Wildlands, Wildwoods, and Mountains could all use map pins at their exits to avoid getting lost inside the areas because of their size.

**Comment by zunath** [comment]
Is there a reason they can't add map pins themselves? They're persistent across resets.

**Comment by taelon875** [comment]
I told them they were, just relaying the info. ^^

**Comment by zunath** [comment]
Thanks. Yeah I'm going to lean on having the player do that themselves for stuff outside of NPC cities.
