### ISSUE TITLE
GAME: Immediate Improvement Perk Not Working? 

### ISSUE THREAD

**Issue by PjShirt** [zunath/SWLOR_NWN#334]
The Immediate Improvement perk dosn't seem to be working? Says it gives health along with regen with med kits.

Just gives regen, unless the lvl 1 is supposed to give 2 health instantly then regen.

**Comment by zunath** [comment]
It appears to be working for me. The amount it regens is based on the item level, the medicine bonus on the item, and your overall medicine bonus on equipment. It takes that and multiplies based on your immediate improvement perk (1x, 2x, 3x, etc.)

I think this is working as expected, you might just need to boost your equipment and stats.

![image](https://user-images.githubusercontent.com/3136227/47643264-e867be80-dba5-11e8-915c-8f4c5faee205.png)
