### ISSUE TITLE
GAME: Fabrication Crafting seems broken

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#338]
Taelon posted a screenshot showing that even crafting a Basic Resource Silo is impossible for now
(crafting level 48 !!!)

**Comment by taelon875** [comment]
https://gyazo.com/a54d683dce1aa05f49d8bcd8672db3dc

This was crafted with level 1 and 2 resources but still with level 0 resources will require at least 24 levels alone for the construction parts.

I believe that lowering the amount need down to 3 with a max of 6 and changing the base level of construction parts from 4 down to 2 will help this.

**Comment by zunath** [comment]
Added Taelon's adjustments to fabrication. We'll try it out and if it doesn't work we can readjust.
