### ISSUE TITLE
GAME: Reduce Leather drop rate on Kath Hound bodies

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#339]
They have a really high leather drop rate.
Most of the time i get at least 2 or 3 leather units.

EDIT : The drop rate for FURS and TOOTHS is still too low.

**Comment by zunath** [comment]
I put their second loot table on its own setup. So in other words, there's one loot table with two chances for leather, fur, teeth and another loot table with a 50% chance for ONLY fur and teeth.

I think this should help things.
