### ISSUE TITLE
GAME: Boots don't contribute to overall AC

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#350]
Need to fix the AC calculation so that all items with AC will grant the bonuses, including boots.

**Comment by kittenblackfriends** [comment]
Might be related to the fact that AC from armor doesn't apply on login. You have to unequip and re-equip the armor to apply AC.

**Comment by zunath** [comment]
All of the boots were missing the item type property. I added it. Your items won't be retroactively fixed though, so you'll need to make a new pair. We'll probably have to manually fix the ones from the stress test when we go live.
