### ISSUE TITLE
[Bug] Beggar Dialogue typos & Quest

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#354]
![11-02-18_beggar](https://user-images.githubusercontent.com/44709870/47934445-a7c1bb00-dead-11e8-8b91-7b3cb0d75998.png)

1. **Of** course, here you go. [Gives 5 credits]
2. No, **I'm** sorry...
3. Go get a job and stop bothering **me!**

-------------------

Additionally, Crystal's quest doesn't appear to register in the journal, if she has a scripted quest.

**Comment by zunath** [comment]
I've fixed the dialogue on her and a few other NPCs.
