### ISSUE TITLE
GAME: Add in Hutt creature

### ISSUE THREAD

**Issue by Azimn** [zunath/SWLOR_NWN#356]
Not sure if this is right or not I never really used github before but here is the 3d model with animations for a Hutt (this is based off of Jabba from the clone wars) We can add new skins to it and stuff and let me know about the animations I have it linked to the human animation right now and while 85% or more is new animations it's linked to fill in the gaps I can unlink them and try and add more if I need to based on feedback. 
[JabbaThutt.zip](https://github.com/zunath/SWLOR_NWN/files/2544575/JabbaThutt.zip)

**Comment by zunath** [comment]
Included in Lestat's hak changes for Tattooine
