### ISSUE TITLE
[Bug] Scavenger background

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#360]
This background is supposed to perform an extra check while scavenging. It does not appear to show a second check upon failing the first.

If it's supposed to apply +1 to scavenge checks, it is not doing that either, since I'm able to roll a 1 on my DC (which the minimum roll should be 2, since the lowest a d20 can go is 1). It should also be reworded on the website.

If it's supposed to lower the DC, it's not doing that either. I made a copy of the character with a different background, and the initial DC was 7 for both characters (6 at Rank 1, 5 at rank 2, etc).

**Comment by zunath** [comment]
I fixed this. There was a missing check for the background. Will push it to the test server later.
