### ISSUE TITLE
GAME: Supplies Cache

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#367]
All supplies caches are set to spawn with a particular orientation (namely, with the interactable side facing south). This does not prevent you from harvesting any supplies caches, though it does make it difficult to harvest the southeastern-most supplies cache in CZ-220 - Offices and Labs. I suggest just moving the spawn point for it north enough that characters can fit between it and the wall.

**Comment by zunath** [comment]
Adjusted the spawn directions in this area.
