### ISSUE TITLE
GAME: Clicking the X on the progress bar doesn't cancel the process

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#370]
If you hit X while harvesting or scanning, you become unable to harvest/scan/rest until you manually move your character. "You're too busy to activate that ability"

A relog (or moving your character) will fix it.

**Comment by zunath** [comment]
There's a not a lot I can do about it from what I can tell. If you want to cancel the action, just move. It should cancel. There's probably some stuff we can add to NWNX but this is such a small thing I probably won't bother.
