### ISSUE TITLE
Avix Tatham "Refinery Trainee" Will not complete.

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#372]
After completing the second part of Avix's Quest line. "Refinery Trainee" where you turn in refined ores. He acts as though the quest is completed, however the option to select your reward does not display a reward, meaning the quest cannot be completed.

Confirmed by G-Nome & Kendaric

**Comment by zunath** [comment]
Fixed for the next update. Wrong ID name.
