### ISSUE TITLE
"Selan's Request" Harlon Linth inaccurately Identified as "Verena Finn" 

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#373]
When talking to Selan, and when looking at her quest for the three tickets in the quest log, she identifies Security Officer "Harlon Linth" as "Verena Finn".

**Comment by zunath** [comment]
I don't know what the reason was for this change, but I've inquired. I've changed it back to Halron Linth as it was before.
