### ISSUE TITLE
GAME: Comms Double Exposure

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#375]
This may be an intended feature. However, when speaking on comms near the a person on your commlink they hear what you say twice. "Hello, What is up!?" would displayed twice to the listener if nearby.

So it looks like.

Player 1: "Can you hear me?"
Player 2: "Hey, What is up!?"
Player 2: "Hey, What is up!?"

**Comment by kittenblackfriends** [comment]
Players who aren't in the comm (party) can hear what someone says over comms. I believe it is related to that, and maaaay be an intentional feature.

**Comment by G-Nome-SavagePope** [comment]
That's what i figured, and I think it's a cool feature. I just wasn't totally sure so i wanted to bring it up.

**Comment by zunath** [comment]
I think we fixed the dupe messages. Hearing other people over comms is an intended feature.
