### ISSUE TITLE
Heavy Armor Crafting: Heavy Armor Segment not Valid

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#377]
Armor crafting bench. Creating any heavy armor.

Placed Heavy Armor Core in Bench, no Error. 
Placed Heavy Armor Segment in Bench, Error Displayed: "Only Heavy Armor Core components may be used  with this component type. It simultaneously spits the Heavy Armor Segment back into inventory.

**Comment by zunath** [comment]
Not an issue - you just need to click "submit items" and return to the crafting menu. Then second the Secondary Component option and place the armor segment inside.
