### ISSUE TITLE
GAME: To implement : NPC's (link)

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#378]
https://cdn.discordapp.com/attachments/500327492154818571/509708477120118785/NPCs.erf

New bunch of NPC's + old ones.
Added 3 alien bounty hunters all with their own conversations.
Added a new spy (spy2) which could spread rumors (for now he has the same conversation as the Bothan spy in Veles, could change once you give me a few rumors to spread)
If you import .erf, overwrite everything already imported.

**Comment by extaz93** [comment]
UPDATE :
- Added 2 NPC's Female Dancers + Waypoints (i don't know how to make constant dancing animations, i'll leave that to you)
- Modified 80% of already made NPC's to make sure they have proper and various Voice Set.

Make sure to overwrite everything already existing.

https://cdn.discordapp.com/attachments/500327492154818571/509752538115997736/NPCs.erf

**Comment by extaz93** [comment]
UPDATE :
Added 2 NPC Male Dancers + Waypoint
Added Bith Musician + Waypoint

https://cdn.discordapp.com/attachments/500327492154818571/509778154248732682/NPCs.erf

Make sure to overwrite everything already existing.

**Comment by extaz93** [comment]
UPDATE 

Added :
- 2 Male Dancers NPC's + Waypoints
- Musician Outfit
- Female and Male Musicians NPC's + Waypoints
- 1 new Patron (Duro) + Waypoint + Conversation.

Corrected :
- Some Patron conversations
- Modified Bith Musician Voice Set

https://cdn.discordapp.com/attachments/500327492154818571/510084511321686030/NPCs.erf

**Comment by zunath** [comment]
@Cavcode - Are these imported into the module?
