### ISSUE TITLE
GAME: Heavy Weapon levels

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#381]
The earliest craftable Heavy Vibroblade is a Greataxe made of scrap metal and mynock meat - netting the lowest possible level as Lv11 for a crafted heavy vibroblade (5 for the blueprint, plus an additional 3 each for the large blade and large shaft).

Either need to lower the difficulty to make or add Lv4 and Lv8 greataxes/greatswords to NPC stores so people can feasibly train heavy weaponry.

**Comment by zunath** [comment]
I think maybe lowering the large blade and shaft levels would help with this. I don't want to really touch the base weapon's level because it's structured in a way that there's coverage for all 11 levels 0-10 for at least one blueprint.

If we reduce the large blade/shaft to 1 that would bring it down to 7 which would put it in the proper range, I think.

Thoughts?

**Comment by kittenblackfriends** [comment]
I know that after 5 levels, your XP when using any gear is practically negligible. We would need to still lower the blueprint level as a result, unless you want people to reallllly have to grind to use heavy vibroblades.

**Comment by taelon875** [comment]
I will try to look into this as well, I'm planning on doing a polish on all the crafting at the  moment, but fabrication is my real focus. If you can get me a list of possible changes you think could work it would help me out a lot. Progression should be difficult but if you are having issues making basic things it should be looked into more. Example the whole issue with fabrication where it was impossible to reasonably make any structure without practically maxing out  Fabrication skill.

**Comment by zunath** [comment]
I added a heavy vibroblade to the Coxxion store. It's a level 5.

I also reduced base blueprint levels by half for tiers 1 and up.

I also reduced the level increases for a lot of the common components on Viscara.
