### ISSUE TITLE
Fabrication, Mainframe. Primary Component "Computing Module" Not recognized

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#389]
Trying to make a mainframe, when I drag a Computing Module into the inventory it displays "Only Computing Module can be used". Which is what I'm using.

**Comment by G-Nome-SavagePope** [comment]
Item is incorrectly called "Construction Parts" in the description

**Comment by zunath** [comment]
Fixed this for the next update.
