### ISSUE TITLE
Apartment Duplication

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#391]
Bought Apartment (Large).
Extend Lease 7day.
Exit Menu (Still only one apartment on list).
Enter Apartment.
Try to Place Fabrication Bench
Try to Place Fabrication Bench
Try to Place Fabrication Bench
Drop Fabrication Bench
Pick Up Fabrication Bench
Try to Place
Try to Place
Peek Outside
Leave
Check Apartment Terminal (Duplicate Apartment Appears)
Enter Apartment #2
Leave #2
Open Terminal
Click Apt #2 (Does Nothing, No Menu Change).

**Comment by zunath** [comment]
The errors placing a fabrication device could have easily caused this I think. Let me update with those fixes and see if this happens again.

**Comment by zunath** [comment]
Had to do with storing a key of a different type into the cache. I've fixed this particular bug and added a check for potential future issues that might crop up.
