### ISSUE TITLE
Create lightsaber and lightsaber crafting skills/perks

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#396]
Add a lightsaber skill which gauges players' ability to use lightsabers.

Add a lightsaber crafting skill which gauges players' ability to craft lightsabers.

Perks for lightsabers should be locked behind the completion of the force quest.

**Comment by zunath** [comment]
I'm kind of backpedaling on this now. I feel like it goes against how skills are currently set up. The skill is a wider range of a particular action while the perks give you specialization. I feel that they should remain on the One-Handed and Twin Blades skills, but the perks only become available for purchase after you complete the force quest.

Same thing with crafting them. The only change I might make there is to move them over to the engineering skill instead of having it on weaponsmith. Open for discussion on this one, though.

**Comment by G-Nome-SavagePope** [comment]
I agree, one handed is one handed. Specialize using perks. 

I also agree with putting them on engineering. It makes more sense than weapon crafting which is primarily simple melee weapons. Engineering needs some heft to it and weapon crafting is already hugely packed.

**Comment by zunath** [comment]
So yeah after having time to mull it over, the new approach is:

1.) Move lightsabers & firearms over to engineering.
2.) Move lightsaber crafting perk over to engineering.
3.) Don't add a lightsaber skill. Instead, establish perks specific to lightsabers at a later date.
