### ISSUE TITLE
Cannot sit in or on fabricated chairs/benches/thrones

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#400]
You place them and then click on them and then the character kinda just runs up to them and stops.

**Comment by Mithreas** [comment]
Fixed in the attached.  They were trying to use some sort of JVM script, it wasn't working so I replaced with the default Bioware sit script.
[Fixed-Chairs.zip](https://github.com/zunath/SWLOR_NWN/files/2635579/Fixed-Chairs.zip)
