### ISSUE TITLE
Cannot add enhancements to weapons

### ISSUE THREAD

**Issue by OuterSanctum** [zunath/SWLOR_NWN#407]
I have been unable to add any enhancements to weapon blueprints.  Whenever I try I get the error message "Your perk level does not allow you to attach any more enhancements to this item."  I have Weaponsmithing 14 with Weaponsmith Blueprint 3 perk that reads "Tier 2 Blueprints + 1 enhancement slot".

I have tried on the following blueprints:
Basic Baton C
Basic Baton M
Baton M1
Basic Blaster Pistol
Basic Heavy Vibroblade GS

I have tried both high level and low level enhancements as well.

**Comment by zunath** [comment]
Missed an equality check. This will be fixed in the next update.
