### ISSUE TITLE
GAME: Crystals aren't recognized as valid component for Crystal Clusters (Engineering)

### ISSUE THREAD

**Issue by KendaricSwlor** [zunath/SWLOR_NWN#408]
Tested it with all color crystals I had, you can't currently craft a crystal cluster (except power crystal cluster) due to the color crystals not being recognized as a valid component.

**Comment by zunath** [comment]
Had some errors on the component restrictions. Those don't really make sense anymore, so I removed them. I don't think your current items will work, but newly spawned ones will after I update.
