### ISSUE TITLE
GAME: Fabrication, Medium Structure Frame, Does not Spawn Item

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#409]
When creating a "Medium Structure Frame" the system pays out the appropriate XP and Displays the message for completing it, but does not spawn the item into your inventory.

**Comment by taelon875** [comment]
sounds like somehow the blueprint resref got changed to me.... Or it never was right i was never able to make one in game....

**Comment by G-Nome-SavagePope** [comment]
I tried twice. Never got the "Received Item" just "You've Crafted". Also didn't drop it or get the "Inventory Full" message or chime.

**Comment by zunath** [comment]
Incorrect resref in the DB. Will be fixed on the next update.
