### ISSUE TITLE
GAME: Durability on stacking items.

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#411]
Should have a way to stack items with different durability with all items take the durability of the lower component. It should not be auto-feature so a player has the choice to stack.

**Comment by zunath** [comment]
This will require a few things from the NWNX side of things. I need an event hook for when items are merged and I also need the ability to decide whether to allow an item merge or not.

Until either I or someone else over on NWNX can implement it, this will need to be on the backburner. I do realize the problem though - but NWN limitations and all that.

**Comment by zunath** [comment]
At this point I think I'm going to mark this as a technical hurdle we can't get past. Items simply can't be stacked, but we can look into reducing their sizes to 1x1.
