### ISSUE TITLE
GAME: Can't enter the apartment for which you have permissions

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#418]
Need to add a way for players to enter the apartments of other players who have granted them permission to enter.

**Comment by G-Nome-SavagePope** [comment]
Suggestion: having full permission allows players to treat the apartment as their own.
Suggestion: Using Peek Outside to allow people to enter temporarily.

**Comment by zunath** [comment]
I don't really know what "treating the apartment as their own" entails. If you give them the permissions, they'll be able to do whatever they want with it (once I add functionality to enter, that is). 

Peek outside actually doesn't make a lot of sense for an apartment. It's something useful for buildings though and the code gets reused. I probably should remove the option for apartments. I'm not crazy about making a specific feature for temporary visits. I feel like it should just be done via the permissions.

**Comment by zunath** [comment]
Removed the peek outside option. Added way to enter apartments for which you have permission to enter.
