### ISSUE TITLE
[Bug] Scordspar Durability hit

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#421]
I was harvesting High Quality Scordspar ore using a Basic Resource Harvester, and it was eating 1.15 durability per harvest. That doesn't sound right.

**Comment by zunath** [comment]
What is your skill level? What are are you in? What are the stats on your harvester?

**Comment by kittenblackfriends** [comment]
It's a basic resource harvester. My skill level was high enough that I wasn't getting XP from harvesting veldite anymore.
