### ISSUE TITLE
[Bug] High level crafting unable to make low level items

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#423]
I am now a Lv18 weaponsmith, trying to make a Lv17 rifle. Using the Basic Blaster Rifle blueprint (Lv3), if I put in a Ranged Weapon Core that adds 9 levels (total: 12 levels), the difficulty is impossible.

**Comment by zunath** [comment]
These use engineering, not weaponsmith now. They were listed under the wrong device. I've since fixed it.
