### ISSUE TITLE
[Bug] Skill Bonuses on Items not working

### ISSUE THREAD

**Issue by OuterSanctum** [zunath/SWLOR_NWN#425]
Now that enhancements work, I made a +2 weaponsmithing dagger.  With 15 base weaponsmithing and +2 from the dagger, I should be at 17 weaponsmithing and able to make up to level 21 weapons. (You can usually make up to your level +4).

When I attempted to do this, it was Impossible.  I was able to make level 19 weapons at Extremely Difficult, but 20 or 21 was Impossible.  I can only conclude that the skill bonus to weaponsmithing from the dagger did not work.

**Comment by zunath** [comment]
These stats are bonus increases, not raw skill increases. Nothing currently increases your raw skill EXCEPT for backgrounds. 

The bonus increases your chances of transferring properties over by +0.5% per +Craft bonus.
