### ISSUE TITLE
GAME: Lower Component levels on Colored Crystal Clusters

### ISSUE THREAD

**Issue by OuterSanctum** [zunath/SWLOR_NWN#426]
Red Crystal Clusters are component level 6.  The lowest level basic red mod Constitution I requires two of them and is base level 8.  That means that the LOWEST level basic red mod is minimum level 20 and requires at least 16 Engineering to make.

This is similar (but slightly different numbers) for other colors as well.  Blue Crystal Clusters are component level 5, the lowest level basic blue mod Charisma I requires two of them and is base level 8.  Minimum level 18.

**Comment by zunath** [comment]
I lowered the base level on the clusters. We'll need to retest to be sure they work after I update the test server.
