### ISSUE TITLE
GAME: [Bug] Sneak Attack Up I - Successfully applied but didn't show

### ISSUE THREAD

**Issue by OuterSanctum** [zunath/SWLOR_NWN#431]
I successfully applied Sneak Attack Up I (from Cairnmog blood) to a Basic Baton M with a Kath Hound Fur scanning enhancement.  The weapon shows the scanning bonus but it does not indicate any Sneak Attack bonuses.

Weaponsmithing Level 15
Blueprint - Basic Baton M

**Comment by zunath** [comment]
Missing examination description.
