### ISSUE TITLE
GAME: Base Drills

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#432]
Base drills are working as intended, but they get a red glow on them after like 1 pull of resource.

**Comment by taelon875** [comment]
Also need to add somewhere resource limit on bases/drills

**Comment by zunath** [comment]
How much fuel did you put into your tower?

**Comment by zunath** [comment]
I couldn't reproduce the red glow issue. I think you didn't put enough fuel into the base.

I added details about the base's CPU, power, resource bay, and time before it runs out of fuel to the control tower menu.
