### ISSUE TITLE
[Potential Bug] Medic Background doesn't give Temporary Bonus

### ISSUE THREAD

**Issue by OuterSanctum** [zunath/SWLOR_NWN#433]
Medic Background reads:
"Temporary Bonus: Rank 1 of the Immediate Improvement perk"

When you make a new character with the Medic background, they do not have that perk listed amongst their known perks.  Should it be listed there?

**Comment by zunath** [comment]
Good find. All of the perks granted by backgrounds seem to have gotten broken at some point. I've fixed this and also an error in the perk refund tome logic to prevent people from refunding background perks.
