### ISSUE TITLE
Dexterity attribute not being added to ranged weapons

### ISSUE THREAD

**Issue by Cavcode** [zunath/SWLOR_NWN#436]
Ranged weapons need dexterity added to their damage.

**Comment by G-Nome-SavagePope** [comment]
That's never been a thing in nwn mechanics and I don't believe it should be now either. We'd have to reduce the base damage of ranged weapons significantly so they don't completely outshine melee.

**Comment by zunath** [comment]
The argument for this is that melee weapons get additional damage based on their STR. If the only argument is that "NWN doesn't do this", I don't think that's necessarily a valid reason.

Without this, ranged weapons will fall behind the melee weapons.

**Comment by Ryudo700** [comment]
Saw a topic on ranged weapons should get dex upgrades to damage to stay viable, but.. ranged weapons have something melee doesn't, ammo. Ammo can add properties and change how range weapons work on the fly, and nwn was built apon 3.5 which didn't use dex for ranged weapons damage but built ammunition around this.

**Comment by zunath** [comment]
We actually don't use ammo on SWLOR (which you had no way of knowing!)

All of the blasters have infinite ammo and use the basic arrow/bolt/bullet stuff. All of the bonuses come directly from the weapon itself. The different types of ammo are essentially handled via perks and are on a cooldown.

**Comment by G-Nome-SavagePope** [comment]
The benefit of ranged weapons is that they are ranged. You get to attack at distance and that gives you multiple attacks for free before the enemy can close on you. It allows to to fire around obstacles, down cliffs, and over trenches.

**Comment by Cavcode** [comment]
That ranged bonus, attacking off cliffs and other junk like that doesn't come into effect on NWN as much as it would in a pen and paper game. Sometimes it does, but most of the time it is negligible. When you add in the ability to Force jump, jetpack around (which I guess most people will have) and other speed nonsense, then it absolutely doesn't work. A word on mighty: It doesn't quite make sense here to use strength for blasters. We're not using the NWN base system here, so I don't think there is a reason to stick with 3.0 limitations.

Now I agree that, with the 2d8 or whatever base damage, the ranged weapons will -slightly- outshine melee. But it'd just be the opposite the other way around if we leave it as it is. Your ideas are swell, I think. I just don't think we should use mighty. I'd like to see the gap close between ranged and melee (someone is always on top, and getting shot with a blaster is just as bad as getting sliced with a vibro or lightsaber). So we should probably also look at lowering the base damage, possibly.

**Comment by G-Nome-SavagePope** [comment]
Mighty still makes sense to me, It's like saying this bastard kicks like a mule so if you're strong you'll be more accurate. But yeah, I get where you're coming from. You'll see if you go to the outer maps that terrain actually does play a huge part of this server already. Mountains, Rivers, Ravines. Got it all.

We'll figure something out.

**Comment by G-Nome-SavagePope** [comment]
I thought about it more and I think ranged weapons should be the non-force source of most of the elemental damage. I know with mods and crafting it's going to be possible for all weapons to attain elemental damage but what if ranged weapons took it a step further?

Every new rank of a ranged weapon gains a 1d4 of elemental damage for free, starting with energy. 

So, 

Basic: 2d6+1d4(Fire)
Rank I: 2d6+1d4(Fire)+1d4(Electric)
Rank II: 2d6+2d4(Fire)+1d4(Electric)
Rank III: 2d6+2d4(Fire)+2d4(Electric)
Rank IV: 2d6+2d4(Fire)+2d4(Electric)+1d4(Sonic)
Rank V: 2d6+3d4(Fire)+2d4(Electric)+1d4(Sonic)
Rank VI: 2d6+3d4(Fire)+3d4(Electric)+1d4(Sonic)
RankVII: 2d6+3d4(Fire)+3d4(Electric)+2d4(Sonic)
RankVIII: 2d6+3d4(Fire)+3d4(Electric)+2d4(Sonic)+1d4(Positive)
Rank IX: 2d6+4d4(Fire)+3d4(Elecrtic)+2d4(Sonic)+1d4(Positive)

Total Damage Ranges (Pure Numeric)
R1: 3-16
R2: 4-20
R3: 5-24
R4: 6-28
R5: 8-32
R6: 9-36
R7: 10-40
R8: 11-44
R9: 12-48

To contrast with Melee, my test character ran with a Halberd his damage was up to 1-10+11 (12-21).

12-21 as a noob. It's fair to assume he would cap off at around 16-25. Not including better weapons, mods or enhancements. What this means is that, raw, physical damage goes to the melee, while ranged is able to damage a wider variety of enemies.

What this does for the game is allows builders to design mobs more easily dispatched by either physical or energy and therefore situations where one is better than the other. Or where both need to work together.

It would however mean that builders need to keep the damage spread in mind when making new mobs for higher level areas.

What do you think?

**Comment by zunath** [comment]
Tracking changes in #462 after Liareth ran the numbers on what changes look like.
