### ISSUE TITLE
First Rites quest needs to provide a basic lightsaber (level 0)

### ISSUE THREAD

**Issue by KendaricSwlor** [zunath/SWLOR_NWN#441]
The First Rites quest should provide a basic lightsaber (level 0), since lightsabers now fall under their own skill and require to be trained from ground up. Since the lowest craftable one is around level 10 and that includes the crystal from the quest.

**Comment by taelon875** [comment]
Honestly I feel that is a good skill level for the lightsaber crafts. Easily obtainable  with some +gear to get it.

**Comment by KendaricSwlor** [comment]
With lightsabers falling under their own skill now, we need a way to craft a low level variant. Otherwise it's next impossible to raise the skill, since you can't hit a thing or damage it.
And that is a problem.

**Comment by Ryudo700** [comment]
Have practice savers then? The weak underpowered variant that padawns use?

**Comment by zunath** [comment]
I've dropped the base levels on emitters, power clusters, saber hilts, and the lightsabers themselves.

Building a lightsaber with tier 0 components from scratch (excluding the free cluster) will put the lightsaber at level 5. This is still higher than your 0-skill, but I think it's OK for now. We might do training sabers that Jhoren sells at a later date.
