### ISSUE TITLE
GAME: Dual Blasters

### ISSUE THREAD

**Issue by Cavcode** [zunath/SWLOR_NWN#442]
So dual blasters should be a thing! They can either be just a visual thing where they're just the same as single blasters (lame) or just single blasters with an extra attack and less ab! Honestly I have no idea how they were balanced on other servers. They probably shouldn't do less damage (you can dual wield the same pistols) but it's harder to aim properly with two in hand.

**Comment by G-Nome-SavagePope** [comment]
They'd have to run the same rules as dual wielding. Whatever that is, -8 Main Hand -10 Off Hand until the Ambidex and Two Weapon Feats would be applied.

**Comment by givemedeath** [comment]
Cosmetically, this is fairly easy to accomplish by using sling base item type for right hand and an offhand cosmetic base item type for left hand and a modified sling animation and modified bullet vfx. 

Mechanically, this could be challenging if it should be treated as true dual wielding. This is because there is no way to add ranged dual wielding to the NWN engine (integrated into attks/round etc.)

**Comment by zunath** [comment]
Aesthetically is perfectly fine. We can just treat all blasters as dual wielding if that's simpler overall? The mechanics don't need to change - I just know people really want to be Han Solo

**Comment by givemedeath** [comment]
I've confirmed that the required cosmetic assets are already in the current haks. 

I'm thinking the simplest option is as follows:

- When a normal blaster pistol is equipped add a character option to switch to dual blasters which would create the necessary items on the character and copy all properties (including description and variables) to the new items. Offhand blaster model will always match the main hand blaster model which can be changed via change appearance options.
- When a dual blaster is equipped do the same as above in reverse.

Note: When dual blaster main-hand item is unequipped, destroy offhand cosmetic item. When off-hand cosmetic item is unequiped, destory it and auto-unequip main-hand item. When main-hand item is equipped, auto-create and auto-equip matching off-hand cosmetic item.

**Comment by zunath** [comment]
I think this is fine but I wouldn't bother copying properties and such to the off hand item. I think that'll cause us to get duplicate stats. 

How would we give people a way to change between dual or single blasters? A chat command? A use item property on the main gun?

**Comment by givemedeath** [comment]
Would only copy on the primary item. Offhand item is cosmetic only 100%.
Thinking the Character Management option on the rest menu could have a toggle added. On-Equip event would then handle everything based on this setting regardless of which type of base item is being equipped. Default would be single blaster.

**Comment by zunath** [comment]
Got it. I'm cool with this bro. Let me know if you need help on it.
