### ISSUE TITLE
GAME: Placeables in Base

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#446]
I went to place new chest and it let me, but I was unable to use anything one them. The conversation to use didn't not work, and it did not bring up a inventory.  My pre-existing chests still worked as intended. I also tried to place them in a new base house it was the same error, but it worked fine in the new apartment I bought.

**Comment by zunath** [comment]
What is the object name?

**Comment by zunath** [comment]
Ok so we can't figure this one out. I think it can be chalked up to the other bugs we had in bases that probably got these two particular chests in a weird state. New ones seem to work fine, so if it pops up in the future we'll address it then. My guess is the IDs got out of whack during one of the other errors.
