### ISSUE TITLE
Created new placeable Wookie Skin Rug

### ISSUE THREAD

**Issue by Azimn** [zunath/SWLOR_NWN#448]
I created a new placeable that I thought would be fun a wookie skin rug.
[fixedChewyrug.zip](https://github.com/zunath/SWLOR_NWN/files/2590484/fixedChewyrug.zip)

**Comment by zunath** [comment]
Bahahaha this is great.

**Comment by zunath** [comment]
I love it so much. It's in-game as a Fabrication blueprint now.
