### ISSUE TITLE
Engineering: Lightsaber repair kits

### ISSUE THREAD

**Issue by KendaricSwlor** [zunath/SWLOR_NWN#452]
The base difficulty for a lightsaber kit is 15, putting the crafting difficulty even with the lowest possible components at 21. That seems a tad high, compared to the pistol repair kit (base difficulty 10) and the rifle repair kit (base difficulty 11). I suggest lowering the base difficulty to 12, then it becomes possible to craft them at Engineering 15.

**Comment by zunath** [comment]
I've dropped the base difficulty of both saberstaff and lightsaber repair kits.
