### ISSUE TITLE
[Bug] Can't turn in Help the Talyron Family Quest

### ISSUE THREAD

**Issue by OuterSanctum** [zunath/SWLOR_NWN#453]
When I speak to Tristan Talyron I don't get the option to turn in the quest or even discuss it with him.  

I properly acquired the quest, spoke to him the get the first journal update, killed the creatures to get the second journal update (which says to tell Tristan you've finished), but there's no option to turn it in.

Speaking to Reid also doesn't have a way to finish the quest.

**Comment by zunath** [comment]
Convo node would only display if you were on state 2 of the quest. Added a duplicate node for state 3 which includes the turn in option.
