### ISSUE TITLE
Blaster pistol mod sockets

### ISSUE THREAD

**Issue by KendaricSwlor** [zunath/SWLOR_NWN#454]
The current mod sockets for blaster pistols make little sense. A blaster pistol II receives two blue sockets in addition to the yellow ones, making pistols a superior weapon choice for Force users but inferior to soldiers/bounty hunters and others due to not having any red sockets (haven't looked at rifles yet). This seems to me somewhat counterintuitive.

**Comment by zunath** [comment]
I've changed their slots from blue to red. This makes them exactly the same as rifles though which I'm not crazy about. We'll roll with it for now.
