### ISSUE TITLE
Perk Misplacement and Issues

### ISSUE THREAD

**Issue by Wandering-Poet** [zunath/SWLOR_NWN#464]
Twin Blades - Saberstaffs -> Improved Critical - Lightsabers : should be in One-Handed - Lightsabers
Twin Blades - Saberstaffs -> Weapo Focus - Lightsabers : should be in One-Handed - Lightsabers
Survival - Farming Skill was removed, farming perks should be too
Twin Blades - Twin Vibroblades - Twin Blade mastery : Description says it affects saberstaff when saberstaff should have its own perk (missing)
Two-handed - Saberstaffs - Knockdown : Only works for Batons, so should be move to One-Handed - Batons

**Comment by zunath** [comment]
These should be good now.
