### ISSUE TITLE
New Lightsaber Changes and Perks: Analysis

### ISSUE THREAD

**Issue by G-Nome-SavagePope** [zunath/SWLOR_NWN#466]
Sabers do not gain AB for DEX, Does not gain damage for CHA
Improved Critical does not apply.
Focus Does not Apply

Whole thing is jacked up, should go over it all and make sure you didn't over look other stuff too.

**Comment by zunath** [comment]
There's no AB gain for DEX. What was your CHA modifier?

**Comment by zunath** [comment]
Does this include saberstaffs too, or just lightsabers?

**Comment by G-Nome-SavagePope** [comment]
Includes saberstaffs nothing seems to apply

**Comment by zunath** [comment]
Had to do some NWNX magic to fix imp crit/focus/specialization. We'll need to retest after I push the changes.
