### ISSUE TITLE
[Bug] Saberstaff Implementation Bugs

### ISSUE THREAD

**Issue by OuterSanctum** [zunath/SWLOR_NWN#467]
This is based on the sabers currently purchaseable from the merchant for the test server.

What is not working:
Saberstaves appear to be equipped as one-handed weapons.
They can be used with shields
They do not grant a second attack per round.

What may not be working:
+1d4 damage bonus on them?

What is working:
Saberstaves modify your AB to account for two-weapon penalties
Saberstaff mastery perks properly apply

**Comment by zunath** [comment]
Fixed the weapon size which caused the shield / one handed issue.

Fixed the skill check (was Two-Handed, now Lightsabers)

Can you confirm that the +1d4 damage is actually broken? If so, please open a new ticket.
