### ISSUE TITLE
Lightsaber Crafting

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#475]
Basic Lightsaber Green says you need blue cluster.
Basic Lightsaber Red says you need blue cluster.
Basic Lightsaber Yellow says you need blue cluster.

Same with Saberstaffs.

Output appears to be correct though

**Comment by taelon875** [comment]
My visual Studio is being a Bitch. Here are the fixes!

UPDATE dbo.CraftBlueprint
SET TertiaryComponentTypeID = 29
WHERE ItemResref like '%lightsaber_r%'

UPDATE dbo.CraftBlueprint
SET TertiaryComponentTypeID = 31
WHERE ItemResref like '%lightsaber_y%'

UPDATE dbo.CraftBlueprint
SET TertiaryComponentTypeID = 30
WHERE ItemResref like '%lightsaber_g%'

UPDATE dbo.CraftBlueprint
SET TertiaryComponentTypeID = 29
WHERE ItemResref like '%saberstaff_r%'

UPDATE dbo.CraftBlueprint
SET TertiaryComponentTypeID = 31
WHERE ItemResref like '%saberstaff_y%'

UPDATE dbo.CraftBlueprint
SET TertiaryComponentTypeID = 30
WHERE ItemResref like '%saberstaff_g%'

**Comment by zunath** [comment]
Fixed. Thanks
