### ISSUE TITLE
GAME: Crash on connecting after server resets

### ISSUE THREAD

**Issue by CragOrion** [zunath/SWLOR_NWN#495]
After server restarts, the game will crash on my first connection attempt as soon as the area loads.
[nwmain-crash-1543089890.log](https://github.com/zunath/SWLOR_NWN/files/2612565/nwmain-crash-1543089890.log)

**Comment by zunath** [comment]
Reported this to our BD contact.

**Comment by CragOrion** [comment]
Still having this problem, only it doesn't just seem to happen after resets. It also happens after any time I time out from the server and have to reconnect, I'm crashing after the area loads unless I restart my client.
[nwmain-crash-1522460437.log](https://github.com/zunath/SWLOR_NWN/files/2613470/nwmain-crash-1522460437.log)

**Comment by zunath** [comment]
@CragOrion Can you get me the .dmp file as well? He can't run his checks on just the log file.

**Comment by zunath** [comment]
I've had a few other people send me these crash dumps. At the moment, the workaround is to close the game down entirely and then come back in. I've passed the info on to Beamdog but I don't have any control over it any further than that.
