### ISSUE TITLE
GAME: First Rites quest

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#513]
Completed the First Rites quest BUT two of the cutscenes didn't trigger.  The battle with myself didn't trigger.  I just walked through empty space to the portal.	

Xiann En Rhi	area	68.9848022460938	133.420272827148	0

**Comment by KendaricSwlor** [comment]
First Rites is still bugged. It now spawns two hostile NPCs near the end, at least one of which seems to be invulnerable. Which leads your untimely death...
