### ISSUE TITLE
GAME: Bandages unable to be used on other players

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#519]
Bandages can't be used on other people despite their description making it sound like they should be able to	

Bandages	velesinterior	126.661590576172	57.4818725585938	0

**Comment by zunath** [comment]
Fixed the 2da. Will be deployed the next time I update the haks.

**Comment by Wandering-Poet** [comment]
Fixing.

**Comment by Wandering-Poet** [comment]
PR open: https://github.com/zunath/SWLOR_NWN/pull/575
