### ISSUE TITLE
GAME: Crafting Adjustments

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#523]
First pass on tweaking crafting:

- Reduce base difficulty on heavy weapons light Heavy Vibroblades. 
- Reduce mod difficulty
- Add more organic component drops with lower level increases.
- Look at power core level. Player says making them lands a level 3 item, but store bought are level 1.
- Reduce the Efficiency perks to 5 SP.
- Reduce the Efficiency perk skill requirements to 10 and 20 for each skill.
- Reduce the Optimization perks to 7 SP.
- Reduce the Optimization perks skill requirements to 10 and 20 for each skill.
- Reduce Construction Parts down to base level 0.

**Comment by Mithreas** [comment]
Suggestion: Add a method to create scrap (level 0 ingredients) by breaking down higher level ones.  Losing all properties etc.  

I don't think you need to increase crafting XP gain, but reducing the number of low level recipes that don't give XP but which are required to craft mid level products would help.  Maybe just increasing the "tail" so you at least get something for grinding out each low level component recipe.  

More thoughts to follow in the thread.

**Comment by zunath** [comment]
I forgot about the XP bonus you get with transferring properties. You're right, I think XP is fine for now. People will complain, but those that continue to work on it will reap the most rewards.

I like the idea of a breakdown process.

**Comment by Mithreas** [comment]
More thoughts now in https://forums.starwarsnwn.com/t/crafting-system-feedback/130/4 as promised.
