### ISSUE TITLE
GAME: Lightsaber imp crit / weapon focus don't apply

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#536]
The lightsaber perk "improved critical" and "Weapon focus" don't apply to lightsaber but to longswords which means the lightsaber don't get use of the perks at all.

Basic Lightsaber	czs220_maintlvl	24.0200576782227	74.3236541748047	0

**Comment by Wandering-Poet** [comment]
Investigating.

**Comment by zunath** [comment]
Might be a little confusing since they share the longsword feats. We could have added another feat for it, but I didn't have the time to try and make sure NWNX would link it correctly. Poet confirmed it was working in Discord so I'm going to close this out for now.
