### ISSUE TITLE
GAME:  Circle Kick perk isn't giving the Circle Kick feat while unarmed or with a martial arts weapon.

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#551]
Circle Kick perk isn't giving the Circle Kick feat while unarmed or with a martial arts weapon.

Eleanor Virria	viscarawildlands	245.920166015625	236.749496459961	3.10236239433289

**Comment by Ryudo700** [comment]
Just bumping since I found out this still hasn't been fixed.

**Comment by zunath** [comment]
This will be fixed in the next release. Sorry it took so long.
