### ISSUE TITLE
GAME: Make Dash perk instantaneous cast

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#553]
Remove the requirement that a player needs to stand still and cast the Dash perk. Allow them to click it even while running.

**Comment by Couls** [comment]
Giving this a shot!

**Comment by taelon875** [comment]
Fixed this up, if you want to try it on your own go ahead, if you cant figure out whats happening just let me know and I will walk you through it.

--Fix Dash Cast time to 0, for instant use of Perk
UPDATE dbo.Perk
SET BaseCastingTime = 0
WHERE ID = 89

**Comment by Couls** [comment]
Thanks to Taelon I implemented this in #598!
