### ISSUE TITLE
GAME: Fuel in bases not accounting for stack size

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#564]
Adding 2x 5 Fuel to my control tower added 2x 1 fuel instead.	

Phylaverian	viscarawildlands	240.70866394043	273.469146728516	2.05407476425171

**Comment by zunath** [comment]
@Mithreas#3258 (tagging in Discord feed)

Having trouble reproing this one. The stacks seem to be merging properly. Can you walk me through step by step?

**Comment by Mithreas** [comment]
Created control tower.
Opened fuel inventory.
Added 5 fuel. 5 fuel added.
Closed tower inventory.
Went and crafted something else. Realised I had 2 more stacks of 5 fuel.
Went back to tower fuel inventory. 4 fuel showing.
Put stack of 5 fuel in. 1 added, 5 showing.
Put stack of 5 fuel in. 1 added, 6 showing.

Later I split my 5 stacks into 1s and added them all fine that way.

James Donnithorne-Tait
Metaswitch Networks

On 28 Nov 2018, at 5:46 pm, Tyler <notifications@github.com<mailto:notifications@github.com>> wrote:


@Mithreas<https://github.com/Mithreas>#3258 (tagging in Discord feed)

Having trouble reproing this one. The stacks seem to be merging properly. Can you walk me through step by step?

**Comment by zunath** [comment]
Thanks! Will try to repro again.

**Comment by Mithreas** [comment]
This seems to be working correctly now, or has been reliable for the last couple of dozen times.
