### ISSUE TITLE
GAME: Add ability to replace/upgrade tower

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#586]
Give players an easy way to replace their existing tower with a new one. This should force the tower to have to regenerate shields from zero to prevent abuse. It shouldn't be possible during a siege from other players and it shouldn't let the player to place a tower if they would go over the CPU/Power limits.

**Comment by Mithreas** [comment]
Suggestion: use the new tower on the old one to exchange the structures (if all conditions are met).
