### ISSUE TITLE
GAME: Circle Kick

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#588]
Circle Kick does not seem to be functioning at all. No message, no extra attacks, no nothing.

Sebasa Brakov	v_cox_base	56.9702568054199	22.3603992462158	0

**Comment by NZNightwolf** [comment]
98008C6F-A344-4C24-BF1E-D905DF2E14D0 | D48ED868-1CA0-4AAF-8B0E-A8EDD486B08D | UPD4UDDC | Circle Kick martial arts perk doesnt appear to work, no feat and no extra attacks when unarmed or using quarterstaff. | Kal Zalos | manda_facility | 66.95545959 | 135.0999298 | 0 | 155.54776 | 2019-04-29 22:16:59 | 422
