### ISSUE TITLE
FILE : Veles Colony Interior

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#603]
Lighting redone

**Comment by zunath** [comment]
Can you upload the file? Might need to zip it since github doesn't like erf

**Comment by extaz93** [comment]
Didn't see that Github couldn't upload .rar, that's why it wasn't working at first.

[velesinterior.zip](https://github.com/zunath/SWLOR_NWN/files/2636943/velesinterior.zip)
