### ISSUE TITLE
GAME: Lighting issue with structure

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#620]
'Braizer, Stone' fixture item casts shadows on nearby players, but does not actually give off light. Most likely all light-producing fixtures have this same issue.	

Brazier, Stone	house_int_1	25.0366020202637	23.4195499420166	-0.00330036599189043

**Comment by Mithreas** [comment]
Lighting often needs the player to leave and come back into the area before it loads correctly.  Not sure we can fix this.
