### ISSUE TITLE
GAME: Metal reinforcement item

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#624]
I'm trying to use Metal Reinforcement, which is labeled as a padding material, in the Heavy Armor Core recipe. The error message says 'This component cannot be used with this type of blueprint'	

Ales Mennard	house_int_1	35.3866996765137	15.0820398330688	0

**Comment by zunath** [comment]
I've removed the restriction on this item. Going forward, I think we should only apply item type restrictions for enhancements.

**Comment by Mayanaka** [comment]
I would like to update this one as of today.

Okay so interesting find. With the metal reinforcements.
I made one out of scrap and fiberplast and it can be used in armor cores just fine.

I made three out of mandolorian(blue socket metal) metal and fiberplast and they cannot be used in heavy armor cores

**Comment by Mayanaka** [comment]
Now one of my three blue metal augments seem to work(other two are still broke) but I have another plate with AC Up I three times and Durability Up I. And that one will not convert.

Any chance that it is just having issues with accepting ones with enhancements on them?

**Comment by zunath** [comment]
Older items were not retroactively updated. So it's possible a few of the older ones are broken. Get with a DM for a replacement.

Can you confirm that new ones you create are working?

**Comment by zunath** [comment]
Let me know if the new items aren't working. I think they should be now. Contact a DM to replace the old ones with the new version.
