### ISSUE TITLE
GAME: Weather patterns

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#645]
Mithreas has kindly offered up his weather script for making locations have consistent weather.

https://github.com/Mithreas/CoW/blob/master/scripts/inc_weather.nss

I really want this integrated into C# so the code base is all in one place. Easier to maintain, we get git history, etc. etc.

**Comment by Mithreas** [comment]
To ensure proper weather handling, most areas need their properties updated:
- Wildlands area and Viscara Lake area need their default skyboxes changed to Grass_Clear (not Grass_Storm). 
- Mountain Valley and Deep Mountains areas need their type changed to Natural (not Artificial). 
The following interior areas are currently marked as exterior, and need to be flagged as interior (in area properties):
- Hanger
- Colony Interior
- Mandalorian Facility
- Coxxion HQ
- Coxxion Base
- All apartment and player home areas.

**Comment by Mithreas** [comment]
(Also, all area names need to be Planet - Area, like the Viscara ones.  The current Druxer IX areas will need to be renamed to work).

**Comment by Mithreas** [comment]
[climate_and_debug_placeables.zip](https://github.com/zunath/SWLOR_NWN/files/2726024/climate_and_debug_placeables.zip)
Placeables to support the new weather system and the updated ErrorService.  Not necessary, but useful for builders.
