### ISSUE TITLE
GAME: Treasure bag in medium home

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#652]
There is a weird giant treasure bag in my medium home, I'm not sure how it got here but I didn't place it! https://cdn.discordapp.com/attachments/516784407831642150/519029752191909888/unknown.png		

house_int_2	32.4731330871582	20.3598651885986	0

**Comment by Mayanaka** [comment]
That said these treasure bags, beds, buckets, small tables. There are all sorts of none placed decorations that appear in the homes in general when they are placed. I might suggest removing those entirely at some point. It might just be a thing with toolset.

**Comment by Mithreas** [comment]
Removed the extra treasure bags, and changed out the corner tile in that same room so hopefully items placed on it will be usable.  Also fixed up some values on items that I broke in a previous update (sorry!). 
[houses_items.zip](https://github.com/zunath/SWLOR_NWN/files/2752634/houses_items.zip)
