### ISSUE TITLE
GAME: Require that a control tower be placed within hours of leasing land

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#658]
There's currently a loophole where players can purchase land but not place a tower down. This leads to land which cannot be claimed by other players via PVP.

My proposed solution at the moment is to require a tower be placed down within 4 hours of purchasing the land (real world time). If a tower doesn't get placed, the land is forfeited and available for purchase by other players. The money paid is not returned.

If land is lost in this way, the player who purchased the land must wait 24 hours (real world time) before purchasing any land again.

**Comment by Mithreas** [comment]
Good idea.  Related suggestions:
- if the PC doesn't have a tower in their inventory, give them an extra "are you sure" dialog.
- If a tower is picked up, start the 4 hour timer again.
- If on module start a property does not have a tower and the timer is not yet underway, start the 4 hour timer.

**Comment by Couls** [comment]
4 hours may be a bit short but with the confirmation dialogue and the fair warning implemented while purchasing it should be fine, i also think you should implement a reminder every 30 minutes that shows how long is left and make it red to put emphasis on The urgency and the fact It’s not refunded

**Comment by Wandering-Poet** [comment]
Sounds reasonable, although for any existing people in the state the timer should start when they log in.

**Comment by zunath** [comment]
Mithreas has put together a solution for this but I think it needs a few tweaks. Also, there's been a ton of refactoring that's happened since he made the PR so we can't do a straight merge. The best course of action here is to take what he did and reimplement it in our current code base.

**Comment by zunath** [comment]
Closing this ticket out as it will no longer be relevant in the revamp.
