### ISSUE TITLE
GAME: Overfilling tower causes fuel dupe

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#661]
when overfilling a fuel tower there is a chance of the contents of the fuel bay being cloned and deposited on the ground beside the tower as new fuel.	

Small Control Tower	viscarawildlands	75.397590637207	57.742733001709	0.12706570327282

**Comment by givemedeath** [comment]
Any additional info on how to reproduce this or if this is still an issue?

**Comment by zunath** [comment]
I believe it's still an issue based on a recent incident with a player. I don't unfortunately have any good repro steps.

**Comment by zunath** [comment]
Closing this ticket out as it will no longer be relevant in the revamp.
