### ISSUE TITLE
Viscara - Veles Sewers | Area Build

### ISSUE THREAD

**Issue by Miaoutain** [zunath/SWLOR_NWN#662]
Base area for the Veles Colony Sewers. Currently empty and the two transitions need connections. Setup for future quests. 16x16 map using steamworks tileset. Additional two map transitions planned for sectioned off areas.

[VelesSewers.zip](https://github.com/zunath/SWLOR_NWN/files/2652181/VelesSewers.zip)

**Comment by Miaoutain** [comment]
I'm don't know how to do enemies and loot tables and such, so by all means hook those things up. There are two transitions, I believe one north and one south. Once everything is setup for the map to work I'll revisit it to add fixtures and NPCs and other fun triggers when time permits.

**Comment by zunath** [comment]
NP, sounds good. Right now I'm the only one who knows how to do it (though I obviously want that to change!) 

I'll close this ticket for now and will be visiting the area soon to populate it.
