### ISSUE TITLE
GAME URGENT Strength Bug

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#664]
Any STR over 50 sets weight limit to 0, so you instantly get encumbered.

**Comment by taelon875** [comment]
[encumbrance.zip](https://github.com/zunath/SWLOR_NWN/files/2654664/encumbrance.zip)
This 2da should fix it..... not sure where it goes though....

**Comment by zunath** [comment]
This is added. Will do a hak update in the near future
