### ISSUE TITLE
Suggestion: Crafting/Druability changes.

### ISSUE THREAD

**Issue by Ryudo700** [zunath/SWLOR_NWN#668]
Now I need to prefix this with, this is based on the crafting system as it stands on the 7/12/2018 and could have changed in the time that anyone reads this, but all suggestions are based on the crafting system of that date and ways to enhance the experience in the long term rather then the short term.

Now that that is out of the way, I have some problems with the way durability works on this server as a primary Role play server. All items have a durability and a max durability, something that is normal but when you repair an item you lose max durability while you regain durability. This.. I feel is counter intuitive to specifically a roleplay sever because items no longer feel special. Strong items won't be used as often as weaker ones in fear of breaking them, weaker items will become the norm (if they have not already) in an effort to train and discard. They also don't feel "unique" or "special" due to not being attached to the item, especially if they're an reward from a quest. The current system in place is to make crafters be relevant at all aspects of the game but so far it's lead to almost everyone crafting their own gear constantly. And even then the crafting skills do not reflect the progress of the combat skills, the strongest item you could make in engineering for example would be level 54, but you can go all the way too 100 in the blaster or lightsaber skill, so what items do you get after 54? From shops? Dm's? Quests? If that's so they're only to be discarded in the long run due to them breaking. 

I could go on and on about how this affects gameplay, how it invites people to constantly grind for materials, to make items, to grind for materials, to make items which is a very poor loop to be in when your primary concern should be roleplay. on a roleplay server. Yes some might choose that to be their form of roleplay but that should not be the primary gameplay loop to have items. So I have a few suggestions in mind that I hope keep to the spirit of the current system, while also giving the programmers a headache with the work needed to do. (sorry)

First of all, items shouldn't lose max durability, they should have a chance to break sure, but items breaking no matter what you do in time lose any personal story of growth for the item, what about the blaster that served your mentor well in the war before passed onto you? What quirky things might it have attached to it? Wouldn't it be a shame for that to be lost doing it's intended role, to shoot things? What about that cool event item you got? It'd be a shame to lose it for just using it, or never using it in fear or losing it.

Second of all then, repairing outside basic items should be done by crafters only. Now I need to be clear, when I say basic, I do mean the rank 0 weapons/armor/items, the ones that are for example listed as "Basic Blaster" or "Basic light armor". The ranks of an item should be important, but I'll get into that soon. Having crafters be the only ones able to repair items of rank 1 onwards keeps them always in use, always sought after, and always doing something. It makes them feel important in the way they were intended to be if items were to break inevitably, as they have to be ones repairing it. Also locking a repair to a skill say, to repair rank 1 items, you need rank 1 repair perk, then rank 2 for rank 1+2 and so on, allowing skilled and unskilled crafters to be useful for different stages. 

Now third, this is kind of the biggest change but makes the last point work, Item ranks need to be reworked to be more important to how they currently are. Now, that could mean a lot of things, but I will break it down, since it does mean a lot of things. Anyone can make basic items, be that the basic blaster to the basic armor, but anyone can make them better with stronger matterials, I propose that stronger materials be locked to stronger ranks of an item, so with blasters a rank 3 gun needs rank 3 materials, whatever those materials be, and that say rank 2 materials can be put on a rank 3 gun, but rank 3 materials cannot be put on a rank 2 gun. Allowing for a natural progression of items that can be put in place with stronger materials. To make this work you'd probably have to add a new variable to most if not all materials to give them a rank, then change what modifiers the lower ranked materials get compared to the higher ranked ones. For example, rank 1 metal might give at most +1 AB while a rank 2 metal might have at most +2 AB, giving a natural progression in the material and thus the items you can make with them. Next is taking the level increase from ranked items, That's confusing thing to say but what I mean is that if you make a basic blaster it might have a base level of 2, which is modified by components used to make it into the total level before it's crafted. while a blaster 2 might have a base level of 12, before modified by components. The importance of the rank is now the materials used to form the strength of the item. Materials might need to have a better natural level increase to compensate for this, maybe, but that is a talk for another time!

I could write more on this, in more depth but I've tried to keep this into a more readable form. The main things I really wanted to address with this is to have items be important, to actually have significance in the long run to a character and to allow for some items to even have a legacy even trough RP. If you have questions about it be free to ask and I can maybe explain parts better.

**Comment by zunath** [comment]
I really appreciate this - but I have to request that you post this on the forums for a wider feedback pool.

GitHub is primarily for tracking specific development tasks. I think there are a lot of good points here, but we need to discuss them so we can pull specific items out of it to work on. There's a wider audience on the forums than there is here as well. So I'm going to close this ticket not to "get rid of it" but to have it reach the appropriate audience. 

I'll also ping you in Discord just in case you're not watching notifications on this item.
