### ISSUE TITLE
GAME: Add option to rename apartment/building

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#671]
Enable players to rename apartments or buildings. There's already code to load this data from the CustomName field. We just need a way to allow players to enter in their own text.

Be sure to check length restrictions on the DB column and incorporate that into the checks in the app code.

**Comment by Mithreas** [comment]
Can I piggy back on this and suggest craftable signs (simple buildings with no interior, renamable)?

**Comment by zunath** [comment]
I've separated your request out into another ticket. https://github.com/zunath/SWLOR_NWN/issues/691
