### ISSUE TITLE
GAME: Craftable droid henchmen

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#673]
Base droid is a high level Fabrication skill.  A droid on its own has an inventory but doesn't do much.

Other crafts can make upgrades.
- Engineering - blasters, harvesting tools
- Weaponsmith - melee attachments
- Armoursmith - HP/AC upgrades

Droid can be used as a pack mule (basic), or tasked with mining/fighting with the right attachments.  

Mechanically implemented as furniture that turns into a henchman when placed, and becomes furniture again when picked up.  PCs can have up to 1(?) henchman droid at once.  Equipment is implemented as bonuses/powerups on the furniture object. 

Optional extra: Mining droids can also be assigned to a control tower, taking 1 CPU each, and raising the mining yield slightly.

**Comment by zunath** [comment]
With revamp I'd like to take an approach of giving engineers the ability to build droids and customize their parts & AI. Inspiration for the AI comes from the gambit system in FF12. Some implementation ideas here: https://immersivenick.wordpress.com/2019/03/31/programming-the-ffxii-gambit-system/

Anyone should be able to use a droid but only someone with the required perks in engineering should be able to build and customize them.
