### ISSUE TITLE
GAME: Wildwoods teleportation

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#682]
entered Wildwoods and teleported to Mandalorian base	Shade Darkstrider	viscarawildwoods	305.008911132813	159.125747680664	-0.0302509441971779

**Comment by Couls** [comment]
I have no idea how to even begin reproducing this. More information is definitely needed

**Comment by zunath** [comment]
Has to do with how the game lands you into the area. Might look into moving the waypoint. These kinds of bugs are really difficult to reproduce and fix.
