### ISSUE TITLE
GAME: Plasma Cell executing when you're shot

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#687]
Plasma Cell even firing when you're shot, not shooting someone.	Kerrikkata	viscarawildwoods	81.1989059448242	262.789794921875	-0.236478507518768	131.183685302734

**Comment by zunath** [comment]
https://cdn.discordapp.com/attachments/484936923341651980/521525648037249084/unknown.png

**Comment by Couls** [comment]
Will be working on fixing this when I have the time

**Comment by BrendanGalvin** [comment]
More of the same: https://cdn.discordapp.com/attachments/530996421646745623/530996459789877248/unknown.png

Jacen shot DD-39, and a fire cell triggered, but not on DD-39.
