### ISSUE TITLE
GAME: Auto-deploy updates

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#690]
Right now updates are a manual process. I'd much prefer if the auto-restart script would check for the existence of a "mono.rar" file and/or a "Star Wars LOR.rar" file. If either or both of these exist, the script would run "dtrx --flat" on them (or any unrar command really) and put them into the mono folder or the userdirectory/modules folder.

This would let me more easily deploy updates and have them apply on the next reboot.

**Comment by Mithreas** [comment]
Yep... my startup script for Anemoi does pretty much exactly that.   Travelling atm but will do this for you when I have some time.
