### ISSUE TITLE
New Player Houses

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#699]
This adds 3 new styles of player homes all made by Mythic. I went in and make sure all the resrefs and tags line up and that the IS_BUILDING variable is set.
Let me know what else is needed to implement and I will get that done as well.
[Houses.zip](https://github.com/zunath/SWLOR_NWN/files/2665491/Houses.zip)

**Comment by zunath** [comment]
Can you replace the doors with Building Entrance placeable doors? There also needs to be a Player Home Entrance waypoint near the door inside each building. Make sure it's pointing in a proper direction.

And to save me some more time can you give me a list of the area resrefs so I can build a database migration script for it?

Thanks!

**Comment by zunath** [comment]
Added these.
