### ISSUE TITLE
GAME: appearance.2da edit for Cathar helmet scaling.

### ISSUE THREAD

**Issue by Miaoutain** [zunath/SWLOR_NWN#702]
The appearance.2da had helmet scaling for Cathar to be defaulted to human instead of defaulted to Half-Orc. Scaling is now 1.2 for both male and female.
[appearance.zip](https://github.com/zunath/SWLOR_NWN/files/2669952/appearance.zip)

**Comment by zunath** [comment]
I've added this 2da to the repo. Next time we update the 2das this change will be in place.
