### ISSUE TITLE
GAME: Rename entrances as well as building areas

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#703]
Building renaming only renames the area, not the entrance.  So it doesn't help visitors find which building they should be trying to enter.	

Phylaverian	viscarawildlands	251.132247924805	257.400238037109	2.15248227119446

**Comment by zunath** [comment]
Each area has a cache of data which stores what structures are in it. You can use this to get the appropriate object based on the building's structure ID. It might be a bit complicated so let me know if you need help.

**Comment by Couls** [comment]
Hmm for now I just need the syntax for accessing the cache

**Comment by zunath** [comment]
List<AreaStructure> areaStructures = area.Data["BASE_SERVICE_STRUCTURES"];

^ This should be used on the area the building/door are spawned in. You can then do something like areaStructures.Single(x => x.PCBaseStructureID == myID); to get the right one. 

You want to grab the placeable structure and change its name to whatever the player changes it to. On top of that, you want to edit the code so that it loads on boot too. I don't think it currently looks at CustomName so that probably needs to be added.

**Comment by zunath** [comment]
Closing this ticket out as it will no longer be relevant in the revamp.
