### ISSUE TITLE
GAME: Fix apartment structure limits

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#712]
Players are able to place more structures than their apartment allows. We need to fix this check on apartments.

**Comment by zunath** [comment]
I was somehow over the structure limit in my apartment, 51/50, I removed an excess piece to bring it back down to 50.	Artemis Alcantar	apartment_3	20.3353710174561	16.0062789916992	0

**Comment by Couls** [comment]
Fixed by Mithreas
