### ISSUE TITLE
GAME: Add new portrait

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#713]
[RiePortrait.zip](https://github.com/zunath/SWLOR_NWN/files/2681075/RiePortrait.zip)

**Comment by Couls** [comment]
https://www.dropbox.com/s/0bom5b8c8lyukgl/hak.zip?dl=0

**Comment by zunath** [comment]
I need the individual files, not the full hakpak please. Just the graphics and the 2da

**Comment by Couls** [comment]
[portraits.zip](https://github.com/zunath/SWLOR_NWN/files/2705297/portraits.zip)

**Comment by DMSymphony** [comment]
Added to Haks:
01290d35 GAME: Add new portrait #713
01290d351d00d9abe47317a79c1e2de8b37eafa3
Motion to close issue @zunath
