### ISSUE TITLE
GAME: Weapon Focus/Spec lost when player unequips an offhand item

### ISSUE THREAD

**Issue by Wandering-Poet** [zunath/SWLOR_NWN#716]
Equip Dagger - get weapon focus
Equip second dagger - no change
Unequip second dagger - lose weapon focus
Equip Shield - gain weapon focus
Unequip Shield - lose weapon focus

**Comment by zunath** [comment]
Unequipping a shield causes the weapon focus to be lost. This likely happens with weapon spec/improved critical as well. Equipping a shield will cause the weapon focus mace to be regained.	Alasdaer Quinn	viscarawildwoods	99.6968841552734	109.366004943848	-0.0719900205731392
