### ISSUE TITLE
GAME: cannot place more furniture than the base limit even in structure-up houses

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#732]
BaseManagementTool.cs line 125 correctly defines the furniture limit as follows.
`                int itemLimit = baseStructure.Storage + structure.StructureBonus;`

However, PlaceStructure.cs doesn't count the StructureBonus, so it reports the limit wrongly.  
Line 109:
`                header += _color.Green("Structure Limit: ") + childStructures.Count + " / " + baseStructure.Storage + "\n";`

And row 513 of BaseService.cs also doesn't check for the structure bonus.
`                if(buildingStructureCount > parentBaseStructure.Storage)
                {
                    return "No more structures can be placed inside this building.";
                }`

I believe the fixes are:
PlaceStructure.cs
`header += _color.Green("Structure Limit: ") + childStructures.Count + " / " + (baseStructure.Storage + buildingStructure.StructureBonus) + "\n";``
BaseService.cs
`if(buildingStructureCount > (parentBaseStructure.Storage + parentStructure.StructureBonus)`

**Comment by zunath** [comment]
This looks right to me. Thanks! This will be part of the force update.
