### ISSUE TITLE
GAME: rebalance mining component level increases

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#738]
Many mining components have very high level increases - higher than are available from other comparable components.  With mining requiring a lot of setup, they should if anything be better. 

Changing the following:
Arvina (Armorsmith up 2) - 6->2
Coqina (Cooking up 2) - 6->2
Corylus (Structure up 1) - 2->2 no change
Engina (Engineering up 2) - 6->2
Fabrino (Fabrication up 2) - 6->2
Gorruchi (Rest up 1) - 4->4 no change
Harvino (Harvesting up 2) - 6->2
Hollinium (Damage up 2) - 7->3
Hzzuntil (Damage up 5) - 8->7
Medcina (Medicine up 2) - 6->2
Nibullan (AC up 3) - 8->8 no change
Omedia (charges up 1) - 2->2 no change
Pawisis (light up 1) 2->2 no change
Pefoate (dark up 1) 2->2 no change
Plexite gemstone (FP up 6) 8->4
Porlang (FP up 6) 3->3 no change
Regvis gemstone (prismatic mod) 6->6 no change
Stalluchi (Scanning up 1) 4->1 [Keth Hound fur does +1 for 2 levels)
Tinnuchi (Meditate up 1) 4->4 no change
Ultranio (+1 all craft skills) 10->3
Uunuchi (+3 durability) 4->4 no change
Venduusi gemstone (+1 BAB) 12->8
Weevina (weaponsmith up 2) 6->2

[rare_mined_components.zip](https://github.com/zunath/SWLOR_NWN/files/2711811/rare_mined_components.zip)

**Comment by zunath** [comment]
I've imported this and will include it in the force update since that's currently the master module I'm working from.
