### ISSUE TITLE
GAME: Prismatic object recipes have multiple problems

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#739]
* Force Belts, Light Belts and Heavy Belts all show up under Heavy Armor.  The Force and Light belts should be in the respective places.
* Light Belts, Light Necklaces and Heavy Necklaces all use Force Armor Cores and Force Armor Segments.  They should use Light/Heavy respectively.
* Force Belts use Light Armor Core & Segment.  Should use Force Armour Core & Segment.

Current database values as follows. I am going to fix these up now.
![image](https://user-images.githubusercontent.com/38130103/50513195-f07aa680-0ae1-11e9-9989-09e771e25753.png)

**Comment by Mithreas** [comment]
Commands run and fixed table:
update SWLOR.dbo.CraftBlueprint set CraftCategoryID = 19 where ID=275;
update SWLOR.dbo.CraftBlueprint set CraftCategoryID = 18 where ID=276;
update SWLOR.dbo.CraftBlueprint set SecondaryComponentTypeID=33,TertiaryComponentTypeID=36 where ID=307;
update SWLOR.dbo.CraftBlueprint set SecondaryComponentTypeID=35,TertiaryComponentTypeID=38 where ID=275;
update SWLOR.dbo.CraftBlueprint set SecondaryComponentTypeID=34,TertiaryComponentTypeID=37 where ID=276;
update SWLOR.dbo.CraftBlueprint set SecondaryComponentTypeID=34,TertiaryComponentTypeID=37 where ID=306;

![image](https://user-images.githubusercontent.com/38130103/50513267-60892c80-0ae2-11e9-8f34-e9b11a930fc4.png)

**Comment by zunath** [comment]
I'm going to reopen this because we need to add a migration script to ensure the database is in a proper state every time. The only time it's safe to do one off DB updates is when we're fixing bugs in the player data (dupes or whatever). Otherwise when someone else comes in, they might have core data which is different

**Comment by zunath** [comment]
https://github.com/zunath/SWLOR_NWN/pull/744

Check this PR out for how I made a DB migration script. 

It essentially boils down to adding a SQL script to the Data/Migrations folder using the naming scheme "yyyy-mm-dd.v.sql" where y is the year, m is the month, d is the day, and v is the version for that particular day. After this is done you need to right click the script file and go to properties. Then switch from "Content" to "Embedded Resource".

When the server boots up it'll apply the DB scripts in sequential order starting with the oldest one. This ensures that someone coming in fresh will get a DB with all fixes and changes up to that point.
