### ISSUE TITLE
GAME: Base database entry not cleared up when a player released a base

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#743]
Korben released their lease, and Shade bought the plot.  The game worked fine until reset, when Shade couldn't manage the property, and one of Korben's houses was still on it.

The database had two rows for Wildwoods NW.
![image](https://user-images.githubusercontent.com/38130103/50544513-80843180-0c43-11e9-994d-b6269c63604e.png)

A manual delete of the duplicate failed, with:
The DELETE statement conflicted with the REFERENCE constraint "FK_PCBaseStructure_PCBaseID". The conflict occurred in database "swlor", table "dbo.PCBaseStructure", column 'PCBaseID'.

i.e. the house on the property was stopping the delete command. 

So ended up running these two commands to clear it up.
delete from swlor.dbo.PCBaseStructure where PCBaseID='9E1579F0-C6A7-4946-B799-7E861B9E46A1';
delete from swlor.dbo.PCBase where ID='9E1579F0-C6A7-4946-B799-7E861B9E46A1';

**Comment by zunath** [comment]
I believe this should be fixed with the control tower fixes. There was an ordering issue with how I was getting structures that was getting parents before children and causing FK issues later on.
