### ISSUE TITLE
GAME: new perk ideas

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#776]
Thread for brainstorming and discussion.  If we like any of them, I'll need some guidance on what back end stuff is needed to make a perk actually work.

Martial Arts
- Knockdown.  Must be equipped with a quarterstaff.  Tier 1 - -4 attack penalty.  Tier 2 - no attack penalty.

Polearm
- Knockdown.  Must be equipped with a polearm.  As above. 

Force Combat
- Force Chuck.  Hurl a nearby object at your target for physical damage.  Higher perk levels let you move larger objects for more damage.  Since this ability does not target the opponent with the Force directly, resistances don't apply - it just deals damage. 

Force Utility
- Absorb Energy.  Gives the caster DR against all energy attacks (elemental damage + blaster fire) equal to their Wisdom modifier.  Total amount of damage absorbed scales with perk level.  (Think Yoda in the duel with Sidious).  At higher perk levels, adds the damage to the next Force attack the caster makes.

Force Support
- Confusion (Mind spell).  If the caster's WIS modifier is higher than the target's, applies the NWN Confusion effect for a number of rounds equal to the difference.  This may cause an NPC to attack other NPCs.  Requires a successful Force Accuracy check to hit, and applies the resistance level to the duration.

Force Utility
- Force Persuade (Mind spell).  If the caster's CHA modifier is higher than the target's, applies a Domination effect for a number of rounds equal to the difference.  Requires a successful Force Accuracy check to hit, and applies the resistance level to the duration.  If the caster attacks the Persuaded individual the effect immediately ends. (For bonus points, use the Arelith-style player tool 1 NPC control ability that lets you tell the NPC where to move to).

**Comment by zunath** [comment]
Perks need a few things:

1.) A database migration script which adds entries to the following tables: Perk, PerkLevel, PerkLevelSkillRequirement, PerkLevelQuestRequirement, PerkFeat, PerkCategory. Only Perk and PerkLevel are required, but depending on what you're building you might need to add entries to the other tables.

2.) A C# perk script. Right now even if the perk is passive it still needs a script. These should be put into the appropriate folder under the Perk directory.

3.) If the perk is activatable, new entries to the tlk and 2das will need to be added. Feats.2da and Spells.2da are the ones you need to edit for this.

4.) If there's a custom effect involved, you will need to edit the C# script for that as well as the database entries for it.

Those are the major things I can think of at the moment. I'm sure I'm forgetting stuff though.

**Comment by zunath** [comment]
I've been wanting to add a Force Utility ability which reduces a target's force defenses for a short period of time. I'm not sure how to divvy it up, but I was thinking something along the lines of a single perk "Force Enfeeble" which unlocks several feats:

(Better names probably needed)
1.) Enfeeble Lightning - Reduces lightning defense, STR, and WIS for a short period of time.
2.) Enfeeble Mind - Reduces mind defense, DEX, and INT for a short period of time.

These would be available at rank 0 for Force Utility and each upgrade would increase the potency of the effects (read: amount and length).

**Comment by CragOrion** [comment]
A couple things on "Absorb Energy"
This is a real thing in SW lore. Info here: https://starwars.fandom.com/wiki/Tutaminis
* Rename it to Tutaminis. 

* This should considered a _very_ advanced technique. While it was taught to most padowans, it was very rare for anyone to make good use of it. The most notable exceptions of course being Satele Shan and Yoda. 

I would suggest having an initial rank available at an earlier level (maybe around utility lvl 10) that doesn't do very much at all, but make advanced ranks become available every ten levels starting at lvl 40.  So there would be 7 ranks total. 10, 40, 50, 60, 70, 80, 90, 100.  Once you hit the second rank the usefulness should jump to represent making a breakthrough in understanding of the power. 

Rank 1 - The first rank can be a basic DR against energy with not a long duration. 
Rank 2 - Can improve the DR and duration to be much more useful against lightning and blasterfire
Rank 3 - Can start using absorbed energy to empower self, restoring force points
Rank 4 - Can improve force point restoration from absorption
Rank 5 - Another improvement to DR for superior protection against focused energy attacks, including force breach and lightsaber attacks
Rank 6 - Another improvement to duration. Starts giving user bonues akin to stat potions and bless
Rank 7 - Absorption empowerment improves to give bonuses akin to the spells "Aid" and "Divine Power"

**Comment by CragOrion** [comment]
Confuse should probably be force utility, rather than support. 

Would also like to suggest battle meditation, which should be an advanced power, probably becoming available at utility lvl 20 or 40. It can employ effects similar to "Prayer", bard song, and curse song as ranks progress

**Comment by CragOrion** [comment]
I also have an idea for blaster deflection.

Force Support perk: Jedi Defense - Would work a lot like Parry, but with some differences. Counts as a "Stance" Cannot be active while other stances are active. While active, user does not make attacks. 

Rank 1: Req Force Support lvl 1.  Gain Jedi Defense Stance. Lightsaber must be equipped to activate stance. Stance activation is instant, unlike other stances. While stance is active, cannot make attacks. User may attempt to parry and reposte # of melee attacks/turn = to user's APR (basic parry mode). When rolling for reposte, attacker rolls attack vs user's AB+Wis mod+1D20

Rank 2: Req Force Support lvl 5. May now attempt to parry/reposte ranged attacks

Rank 3: Req Force Support lvl 10. Gain +1 APR while stance is active (essentially enabling you to parry one extra attack)

Rank 4: Req Force Support lvl 20. Gain another +1 APR while stance is active

Rank 5: Req Force Support lvl 40. Add user's Wis mod to AC while stance is active

* Lightsaber & Saberstaff perk: Intuitive Strike - User bides their time during a fight to find the right opening where they can pierce the enemy's defense. Sacrifice all extra attacks this turn (even if dual wielding) to add Wis modifier to AB for a single attack. Cooldown 30s. Using this attack takes you out of any stance you are currently in. Subsequent ranks in this perk can increase chances of a crit and lower cooldown.
