### ISSUE TITLE
GAME: Import New Czerka Ranger Uniforms

### ISSUE THREAD

**Issue by CragOrion** [zunath/SWLOR_NWN#790]
I've put together some new outfits for the Czerka Rangers to better fit Czerka's color scheme and design. 
The Trandoshan outfits have also been made barefoot.

[czerka_outfits3.zip](https://github.com/zunath/SWLOR_NWN/files/2775954/czerka_outfits3.zip)

**Comment by CragOrion** [comment]
Fixed the colors and trando arms and legs, updated the erf/zip file posted above

**Comment by zunath** [comment]
Thanks for this. In general, I'm not a fan of redoing content we've already established. I think instead of replacing what we've got, we'll repurpose these for Tattooine or another area.

**Comment by CragOrion** [comment]
The main thing I wanted to do was actually fix the trandoshans we have standing around Veles wearing boots and having human hands. Can I at least get an .erf of what they currently wear so I can fix their hands and feet?
