### ISSUE TITLE
GAME: Add warnings alongside the hourly reboot for impending lease expiry

### ISSUE THREAD

**Issue by Mithreas** [zunath/SWLOR_NWN#802]
Every lease a player holds that expires in <24 hours should be flagged to them alongside the message that says "the server will reboot in X hours".

**Comment by zunath** [comment]
I assume the intention of this is to make sure they're around to pay the lease before the reboot?

**Comment by Mithreas** [comment]
It's mainly so active players don't forget.  I know a couple of people have been surprised by their lease expiring a day earlier than they thought, where getting a 24 hour countdown would have been a perfect reminder.

Tying it to the reboot message is just for convenience, and to avoid stacking up the number of random messages players get. Having it all on the same timer should be more efficient too.

**Comment by zunath** [comment]
I've added this for the next release.
