### ISSUE TITLE
GAME: Post 3/7/2019 Hak Issues

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#834]
These are the outstanding issues which cropped up after the large hak update we released on 3/7/2019.

- [x] Shade keeps crashing in the Mountain Valley. Doesn't seem to be a creature model. Could be tiles, textures, or another model. Need to do further investigation.

- [ ] Most of the textures on the Jukebox are missing apart from the ribbed front.

- [ ] Starfield texture on ship windows is messed up. https://cdn.discordapp.com/attachments/495642017414774795/553423159165059101/unknown.png

- [ ] Miskol reports extended loading times and longer "freezing" where the game acts like it isn't responding. Only confirmed to be a problem on the DM client.

**Comment by naiatis** [comment]
Textures: Jukebox
Most of the textures on the Jukebox are missing apart from the ribbed front.

**Comment by naiatis** [comment]
Textures: Mace, Desk placeable in the Czerka Tower

Tileset: Modern Office
Tiles are broken other than the hallways.

**Comment by kittenblackfriends** [comment]
Club, Middle 10, Color 1 → Scanner. Has some color blocks, but no depth of color.
Club, Middle 10, Color 2 → Briefcase. Seems to be entirely one shade of grey with no depth of color.
