### ISSUE TITLE
GAME: Starship permissions

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#837]
C3F8A33D-3983-4200-895F-400B434EA725	QRRPJXG7	 Cant give full permissions to other people on starship, they can only take off, nothing else.	Ship's Computer	starship1_int	34.7997627258301	36.0694274902344	0	109.099990844727

**Comment by zunath** [comment]
Per SweetSunrise: When Zain bought our ship, I could do everything but access the fuel/stron/upgrade compartments from the computer despite having full permissions to the ship

**Comment by zunath** [comment]
Per Althea: on the starship unless you are the owner you cannot access the fuel/storage/strodium part of the ship. There are also no permissions for such

There's a storage tab that holds things picked up in space and where modifications go
The one tied to the console needed to fly
Also structure storage is weird and works only on land you have given permissions to haha

**Comment by givemedeath** [comment]
This should be resolved.
