### ISSUE TITLE
GAME: Level not listed on Ravior Meat

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#839]
The level isn't listed in the description for Ravior meat. Which is Lv9, by the way.

**Comment by zunath** [comment]
I'm not seeing this one. Can you give me a screenshot? @kittenblackfriends 

![image](https://user-images.githubusercontent.com/3136227/54151032-45a33480-4410-11e9-8291-b4313b4632ec.png)

**Comment by kittenblackfriends** [comment]
Already deleted it but it may have been that the level property disappears
if it has been placed in a table.

**Comment by zunath** [comment]
If you scrap the item, the level property will be dropped. Could that have been it?

**Comment by kittenblackfriends** [comment]
Definitely did not scrap it, since it was lv9 when I tried using it to make
a wooden baton head.

**Comment by zunath** [comment]
Reproduced it. Happens whenever the code tries to convert the NWN property to a SWLOR one. Will be fixed for the next release.
