### ISSUE TITLE
[GAME] [CRAFTING] Accessories & Enhancements

### ISSUE THREAD

**Issue by kittenblackfriends** [zunath/SWLOR_NWN#840]
The light belt I doesn't provide an option for an enhancement slot. Likely, this is because it's also the first version (since there is no "basic" version). It should be standard that I has 1 enhancement slot enabled.

**Comment by zunath** [comment]
This appears to be working as intended. Higher tiers have enhancement slots, leading up to the prismatic belt which has two enhancement slots.
