### ISSUE TITLE
GAME: Charges and Durability on Molecular Reassembly Terminals

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#842]
Currently players cannot reassemble components with +Charges and +Durability because we don't track these stats separately. This means we can't tell the difference between charges and durability which appear naturally on the item versus charges and durability which were added through using components.

I don't want natural charges and durability to be factored in when reassembling. For this reason I left both of these properties out of the terminal options. However, players should be able to reassemble components with these properties so we need to look at making this work.

**Comment by Mithreas** [comment]
There also seems to be an issue with FP (maybe also HP).  It correctly allows you to do +5 on one item, but appears to give it a CL of 10. 
![image](https://user-images.githubusercontent.com/38130103/54564750-7c56ed00-49c4-11e9-9ea6-2b5517f06518.png)

**Comment by zunath** [comment]
Fixed that one. Was dividing instead of multiplying. Whoops.

**Comment by NZNightwolf** [comment]
61C347EB-3DBB-487F-88C4-6EC86449C9F6 | 55EBBFC1-E039-4025-8EE7-BCECA2DDE470 | QRR9WMY7 | Charge bonuses cannot be broken down with the reassembler. | Veral'anar'ilind | viscarawildlands | 251.7616119 | 249.6828918 | 2.033263206 | 159.3899841 | 2019-03-27 11:32:31
