### ISSUE TITLE
GAME: Force Sounds

### ISSUE THREAD

**Issue by Cavcode** [zunath/SWLOR_NWN#845]
The wav files for the Force sounds that I updated. Guess I forgot to include these with the sound update. Whoops!
[ForceSounds.zip](https://github.com/zunath/SWLOR_NWN/files/2964018/ForceSounds.zip)

**Comment by zunath** [comment]
Reposted to the new hak repo here: https://github.com/zunath/SWLOR_Haks/issues/3
