### ISSUE TITLE
GAME: Add new jedi robes for humans,elves and orcs

### ISSUE THREAD

**Issue by Azimn** [zunath/SWLOR_NWN#847]
Hello here are some new robes, this version overwrites the current trechcoat model so you might want to renumber it unless you would want to replace it.
[overrideSW.zip](https://github.com/zunath/SWLOR_NWN/files/2981855/overrideSW.zip)

**Comment by zunath** [comment]
Moved to new Hak repo here: https://github.com/zunath/SWLOR_Haks/issues/4
