### ISSUE TITLE
GAME: Speeders

### ISSUE THREAD

**Issue by Cavcode** [zunath/SWLOR_NWN#849]
[Speeders.zip](https://github.com/zunath/SWLOR_NWN/files/2986136/Speeders.zip)
Speeder assets and 2da entries. They overwrite a few of the horses.

**Comment by zunath** [comment]
Going to track this in #121 since we've got a ticket for it already.

**Comment by zunath** [comment]
https://github.com/zunath/SWLOR_Haks/issues/21
