### ISSUE TITLE
GAME: Anchorhead Tatooine

### ISSUE THREAD

**Issue by Cavcode** [zunath/SWLOR_NWN#850]
[AnchorheadTat.zip](https://github.com/zunath/SWLOR_NWN/files/2994146/AnchorheadTat.zip)
Since I'm on meds for a bit, releasing Tat in smaller chunks. Gonna need help to finish up the creatures, but I'll work on NPCs in the actual city. No claimable areas are in this pack yet, but I plan on making those 32x32 sand dunes that are spread throughout the planet of Tatooine.

**Comment by zunath** [comment]
To reiterate what I mentioned in chat:

There's a bunch of database code being called in these scripts. If we need to store stuff in the DB, that's fine but we need to put it in the same database. I can help you with this.

Please remove all of the NWScript code accessing a database from the erf.

**Comment by NZNightwolf** [comment]
I have finished compiling and fixing the shit storm that was tatooine. I have given all the areas unique resrefs and all transitions -should- be working. Currently 2 dungeons in the areas, with a third to be added at a later time.

[TatooineFin.zip](https://github.com/zunath/SWLOR_NWN/files/3133007/TatooineFin.zip)
