### ISSUE TITLE
GAME Character Description

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#853]
Make a way for players to change character description.

**Comment by givemedeath** [comment]
Is there no way to access the below existing conversation?
I'm not seeing it referenced anywhere.

    internal class ChangeDescription: ConversationBase
    {

        public override PlayerDialog SetUp(NWPlayer player)
        {
            PlayerDialog dialog = new PlayerDialog("MainPage");

            DialogPage mainPage = new DialogPage(
                "<SET LATER>",
                "Next"
            );

            DialogPage confirmSetPage = new DialogPage(
                "<SET LATER>",
                "Confirm Description Change"
            );

            dialog.AddPage("MainPage", mainPage);
            dialog.AddPage("ConfirmSetPage", confirmSetPage);
            return dialog;
        }

        public override void Initialize()
        {
            string header = "Please type the new description for your character into the chat box. Then press the 'Next' button.\n\n";
            header += ColorTokenService.Green("Current Description: ") + "\n\n";
            header += _.GetDescription(GetPC().Object);
            SetPageHeader("MainPage", header);
            GetPC().SetLocalInt("LISTENING_FOR_DESCRIPTION", 1);
        }

**Comment by zunath** [comment]
It was in-game for a while but was buggy for some reason. I didn't have time to go back and look at it. 

It's a good starting place - you can hook it up to the Character Management section of the Rest Menu if you want. That's where it was before. There's also likely some kind of conflict with the OnExamine code running, unless we've inadvertently fixed it.
