### ISSUE TITLE
GAME: Large Tower melee attacks

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#858]
large Towers need an appearance that can be targeted by melee for attacks, they currently are unable to be.

**Comment by NZNightwolf** [comment]
A53C657F-D901-481A-8F3C-78496C34990E | DBFEC800-29F8-49C9-8937-80FE29D82A04 | QR7GQPUA | You can't melee a large tower. | Large Control Tower | viscarawildwoods | 23.01695061 | 119.6749649 | -0.2826809585 | 54.29999924 | 2019-03-14 8:44:23

**Comment by givemedeath** [comment]
Is this the problematic tower?

![image](https://user-images.githubusercontent.com/49852989/86301567-2ebfbd00-bbd4-11ea-925c-08b31b5d2cf3.png)

**Comment by taelon875** [comment]
Yes

**Comment by zunath** [comment]
Closing this ticket out as it will no longer be relevant in the revamp.
