### ISSUE TITLE
GAME: Veles General Store: Inventory

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#874]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

30F4EFAE-A843-422B-8446-5EDC2D94571C | E0FF428E-D895-406F-899F-598423FBE9EE | QRJLKYHX | The general store is removing items almost as soon as you sell items to it. That's definitely not 30 minutes. | Nima Poy | velesinterior | 37.89282227 | 89.44026184 | 0 | 101.7777786 | 2019-04-03 1:09:59

**Comment by NZNightwolf** [comment]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

30F4EFAE-A843-422B-8446-5EDC2D94571C | E0FF428E-D895-406F-899F-598423FBE9EE | QRJLKYHX | The general store is removing items almost as soon as you sell items to it. That's definitely not 30 minutes. | Nima Poy | velesinterior | 37.89282227 | 89.44026184 | 0 | 101.7777786 | 2019-04-03 1:09:59

**Comment by NZNightwolf** [comment]
30F4EFAE-A843-422B-8446-5EDC2D94571C | E0FF428E-D895-406F-899F-598423FBE9EE | QRJLKYHX | The general store is removing items almost as soon as you sell items to it. That's definitely not 30 minutes. | Nima Poy | velesinterior | 37.89282227 | 89.44026184 | 0 | 101.7777786 | 2019-04-03 1:09:59 | 399

**Comment by givemedeath** [comment]
This appears to be working now. Can anyone else confirm?
