### ISSUE TITLE
GAME: Supply Crates: Spawn Positions

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#875]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

0CB881BC-4558-4AB7-9C25-C6EC56203B1D | 9E70E55E-A736-4EC8-8E88-859682702B65 | UPWNEPJK | Supply crates constantly getting stuck in the walls or in places unable to be reached. | Iradtoki | manda_facility | 47.2118721 | 41.55427933 | 0 | 126.0999985 | 2019-04-01 7:30:11

**Comment by NZNightwolf** [comment]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

0CB881BC-4558-4AB7-9C25-C6EC56203B1D | 9E70E55E-A736-4EC8-8E88-859682702B65 | UPWNEPJK | Supply crates constantly getting stuck in the walls or in places unable to be reached. | Iradtoki | manda_facility | 47.2118721 | 41.55427933 | 0 | 126.0999985 | 2019-04-01 7:30:11

**Comment by NZNightwolf** [comment]
0CB881BC-4558-4AB7-9C25-C6EC56203B1D | 9E70E55E-A736-4EC8-8E88-859682702B65 | UPWNEPJK | Supply crates constantly getting stuck in the walls or in places unable to be reached. | Iradtoki | manda_facility | 47.2118721 | 41.55427933 | 0 | 126.0999985 | 2019-04-01 7:30:11 | 395 |

**Comment by givemedeath** [comment]
This may require a smaller size to the following in BakeArea:
const float MinDistance = 6.0f;

**Comment by zunath** [comment]
We can try it but I'm pretty sure we're going to run into the problem in some cases no matter the value. Since the positioning is random and we don't have a great way to determine bad locations I think we're gonna continue to hit this.

**Comment by zunath** [comment]
I've fixed this by using "No Spawn Zone" triggers which make the spawn system ignore any locations within the area of the trigger. This will be available in the revamp.
