### ISSUE TITLE
GAME: Vellen Flesheater: Aggro Range

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#878]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted |   | Comment |

AA463346-6D43-429A-AC09-F5AA8680B452 | 1BABA9A5-7653-4843-B0E2-9548C8E78695 | QRMGFED6 | Vellen Flesheaters aggrod from last room, even though I was at the blue console for opening the door leading to them | Vellen Fleshleader | v_cox_base | 51.19261551 | 128.8345032 | -0.2748175561 | 236.0339355 | 2019-03-31 23:26:41

**Comment by NZNightwolf** [comment]
Been running this dungeon a bit Zunath, and the range on them is ridiculous. Activate red console, and they aggrod right through to the next console.

**Comment by zunath** [comment]
We have a line of sight check in the AI to prevent that kind of thing from happening. So my best guess is that the tileset has some issues (big surprise). I'll need someone else to look at that but in the meantime we can move the spawn points away and see if that helps.
