### ISSUE TITLE
Floor Flicker: Mandalorian Facility

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#881]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted |   | Comment | 

5C2C7D00-E9F8-4E85-92EB-D33705740955 | B1A5AC0D-7241-498C-A506-AE11B88FA1B3 | UPWWTMJT | floor tile flickering. Might be too low into the ground. |   | manda_facility | 143.8247681 | 138.2378235 | 0 | 285 | 2019-03-30 23:58:06

**Comment by NZNightwolf** [comment]
Fixed, ERF Uploaded.


[manda_facility.zip](https://github.com/zunath/SWLOR_NWN/files/3041666/manda_facility.zip)

**Comment by zunath** [comment]
Imported the fix.
