### ISSUE TITLE
Coxxion Facility: Music

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#882]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

7ED11F2C-1980-4EA0-9555-E07001528F31 | 541B163D-024C-4CD9-BB13-12EDBCC272D2 | QRM4XYKJ | there appears to be no music in coxxion zones | Salavar Bloodtalon | v_cox_base | 39.9595871 | 26.10508919 | 0 | 181.3336182 | 2019-03-30 4:20:57

**Comment by NZNightwolf** [comment]
Music Added.

Viscara - Coxxion Headquarters: d20 FO1 Raiders
Viscara - Coxxion Base: d20 Drums 4. Battle: d20 Batl C&C Generals

ERF Uploaded.

**Comment by zunath** [comment]
Imported this.
