### ISSUE TITLE
GAME: Broken Supply Crates

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#885]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

0435DCCF-99AF-4465-A5BC-BEE71EEF5AC0 | B1A5AC0D-7241-498C-A506-AE11B88FA1B3 | UPWWTMJT | Somehow there are a lot of broken supplie crates. | Remains | manda_facility | 28.40530968 | 80.69197845 | 0 | 162.6999817 | 2019-03-27 20:48:29

**Comment by givemedeath** [comment]
What exactly is a broken supply crate?
A crate that doesn't spawn any contents?
A crate that spawns in a destroyed state?

**Comment by zunath** [comment]
Not sure tbh. This might be fixed already?

**Comment by zunath** [comment]
Gonna close it out. If it's still broken, we can reopen it.
