### ISSUE TITLE
GAME: Yavin Placeable

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#887]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

56A4CE2F-7466-4A56-AE48-EC7FBB4EA7F8 | F3D70BB8-4D4E-4503-9DD6-332E03C564C7 | UPFY7PLP | The Yavin object in mon cala's map room should be a red planet, its the moon that's lush and forested, not the planet | Yavin | moncaladaccityex | 128.8575439 | 124.6277008 | 0 | 356.1000061 | 2019-03-20 3:16:51

**Comment by NZNightwolf** [comment]
Changed placeable to be the red version. 

ERF Uploaded.
[moncaladaccityex.zip](https://github.com/zunath/SWLOR_NWN/files/3046371/moncaladaccityex.zip)

**Comment by zunath** [comment]
Imported this.
