### ISSUE TITLE
GAME: Manage Property Screen

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#889]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

E669CF6E-8A81-472E-8A2A-6344E4487F6E | C3F8A33D-3983-4200-895F-400B434EA725 | QRRPJXG7 | The manage property screen doesnt always show a NEXT option which means I can not pay all of my rents | Shade | viscarawildwoods | 17.99055099 | 153.2955322 | -0.3051568866 | 280.4000244 | 2019-03-18 20:26:17

**Comment by zunath** [comment]
This is due to an NWN bug which we can't really fix. It occasionally drops other response options, especially during laggy times.
