### ISSUE TITLE
GAME: Ship Computer Access

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#890]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

7A2A5B50-D86A-45AB-995A-D45FF4B8DB22 | C3F8A33D-3983-4200-895F-400B434EA725 | QRRPJXG7 | Cant access the ships computer in space above Mon Cal | Ship's Computer | starship1_int | 33.13066101 | 37.9156723 | 0 | 53.69999695 | 2019-03-17 1:46:37

**Comment by zunath** [comment]
I think this is already fixed.
