### ISSUE TITLE
GAME: Nibullan Item

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#892]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

70D5DE10-63D3-4982-8D3D-F6B1E6B1048A | F3D70BB8-4D4E-4503-9DD6-332E03C564C7 | UPFY7PLP | Nibullan can only be used on armor, but can't be used on the components to actually make the armor, so the Nibullan is just a useless item. Needs to be changed so it can be used to make metal reinforcements | Nibullan | apartment_002 | 4.43349123 | 16.23856735 | 0 | 137.0999908 | 2019-03-15 3:05:31

**Comment by zunath** [comment]
Made this an enhancement
