### ISSUE TITLE
GAME: Out Of Bounds NPC

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#893]
ID | SenderPlayerID | CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

64FE7674-B615-4376-B26B-B21819913BB1 | E0FF428E-D895-406F-899F-598423FBE9EE | QRJLKYHX | This Vellen Flesheater seems to be out of bounds, despite being on the floor. | Vellen Flesheater | v_cox_base | 33.99716949 | 104.0443039 | 0 | 4.192281723 | 2019-03-14 12:52:09

**Comment by NZNightwolf** [comment]
Note: Possible tileset error as some of the coxxian base wall details can be passed through.

**Comment by taelon875** [comment]
This is the flesheater that is on the bugged tile-set, i think this is "fixed" with the new aggro stuff.

**Comment by NZNightwolf** [comment]
I have not come across any bugged flesheaters in my hours of farming this place. The tileset itself has a few wall areas where the mesh allows you to pass through them.

**Comment by NZNightwolf** [comment]
Tested this via DM Client and NPC's, no longer applicable. Can be closed <3
