### ISSUE TITLE
GAME: Viper's Not Granting EXP

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#897]
CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

UPWNEPJK | Viper not granting XP even though I killed it | Iradtoki | moncalacorali001 | 88.41494751 | 40.53701782 | 1 | 216.1000061 | 2019-04-04 3:46:57

**Comment by taelon875** [comment]
I think this might be that the player has outleveled the vipers xp range.

**Comment by NZNightwolf** [comment]
She was in a part with 2 other people at the time. She got the killing blow, and said she is in the level range (Getting exp from others, apparently).

**Comment by taelon875** [comment]
Killing blow doesn't matter, I think everything is working fine here. It accounts for all party members levels that contributed to the fight, and if 1 of them had one too high nobody gains xp. I think this is closed for now unless someone can duplicate this. And give better details of exact levels of skills, and weapons.
