### ISSUE TITLE
GAME: NPC Firing Through Wall

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#898]
CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

UPWWTMJT | enemies firing through the wall. | Eco Terrorist | moncalacifacilit | 56.27110291 | 106.047287 | 0 | 320 | 2019-04-04 3:48:50

**Comment by NZNightwolf** [comment]
Will look into this later. Could be a placeable or tileset thing.

**Comment by taelon875** [comment]
It is because the area is made with placeables in some spots and they don't stop line of sight.

**Comment by NZNightwolf** [comment]
I'll have a look and see if using static / Plot can allow for this to be stopped

**Comment by NZNightwolf** [comment]
All the walls are placeable, therefor not something that can be fixed easily.

**Comment by NZNightwolf** [comment]
Think this one can also be closed for now. Not much can be done due to them being placeables.

**Comment by givemedeath** [comment]
Is there such a thing as an invisible placeable wall that blocks line of sight?

**Comment by zunath** [comment]
I don't think there is. We'd have to block it with the tileset. Might warrant adjusting the area to make that happen, not sure there's anything else can do about it.

**Comment by zunath** [comment]
Can't really fix this one. I've moved the spawns around to help with the entry area though. Gonna close this out unless someone wants to tackle building a new version or fixing the tileset.
