### ISSUE TITLE
GAME: Hzzuntil not used is saber craft

### ISSUE THREAD

**Issue by NZNightwolf** [zunath/SWLOR_NWN#899]
CDKey | Text | TargetName | AreaResref | SenderLocationX | SenderLocationY | SenderLocationZ | SenderLocationOrientation | DateSubmitted

UPWNEPJK | Hzzuntil does not serve any use in saber craft as it is listed as an electonic and powertype crystal, cannot be socketed into emitters or lightsabers or Hilts, so no use at all. | Iradtoki | apartment_3 | 22.42088509 | 32.06348801 | 0 | 172.8377075 | 2019-04-04 17:34:52

**Comment by NZNightwolf** [comment]
4468C77D-1044-4A6A-8F42-6DE64FC58DCD | 9E70E55E-A736-4EC8-8E88-859682702B65 | UPWNEPJK | Hzzuntil does not serve any use in saber craft as it is listed as an electonic and powertype crystal, cannot be socketed into emitters or lightsabers or Hilts, so no use at all. | Iradtoki | apartment_3 | 22.42088509 | 32.06348801 | 0 | 172.8377075 | 2019-04-04 17:34:52 | 403

**Comment by zunath** [comment]
Changed to an enhancement.
