### ISSUE TITLE
GAME TEST: Bugs

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#909]
Light Foils do not seem to be finessable.

**Comment by taelon875** [comment]
Shield proficiency  not showing up in perks list.

**Comment by taelon875** [comment]
Armor immunity need to be scaling from level, so players unable to just use highest tier of armor and reap benefits.

**Comment by taelon875** [comment]
AB needs to stack when item is made/when item gets AB sockets added

**Comment by taelon875** [comment]
Mon Cal Amphi-Hydrus no longer use dark force powers.

**Comment by taelon875** [comment]
Components/Enhancements needs to be reviewed to cut out any unused/old properties.

**Comment by taelon875** [comment]
![NA](https://user-images.githubusercontent.com/15068982/59165912-22605200-8af1-11e9-9c1c-6ea0a0e8ce62.PNG)
Conversation issue with Next Bonus  showing N/A before it

**Comment by taelon875** [comment]
Force Absorb divides by 0 when you die with it active.
Either that or Heal divides by 0 when you are at full health.

**Comment by taelon875** [comment]
Absorb Energy is listed under Sense not control in the chat menu.

**Comment by taelon875** [comment]
Force Heal is sharing a cooldown when it shouldn't have one.

**Comment by taelon875** [comment]
Comprehend Speech doesn't give any xp?

**Comment by taelon875** [comment]
Force Push Cooldown is 10 mins opposed to 10 secs

**Comment by taelon875** [comment]
Force heal is under Control but it says it requires altar to use.

**Comment by taelon875** [comment]
Force Rage never reactivates but stay up in concentration.

**Comment by taelon875** [comment]
Comprehend speech icon doesn't show correctly.

**Comment by taelon875** [comment]
Battle Meditation doesn't give ab/ac

**Comment by taelon875** [comment]
Battle meditation perks are not given properly it has given me the third and second ability when i should only have first and second.

**Comment by taelon875** [comment]
Edit Force heal costs to reflect spreadsheet changes.

**Comment by givemedeath** [comment]
Drain Life IV is unable to target creatures (spells.2da issue)

**Comment by taelon875** [comment]
Force heal can be activated and the the caster can leave the area/change zones and the skill still applies. it also still gives xp.

**Comment by taelon875** [comment]
Meditate can be used while concentration skills are being used.

**Comment by taelon875** [comment]
Quality of Life: Have a command that cancels concentration ability activated, or have something reminding the user what ability is up.

**Comment by givemedeath** [comment]
Confusion not working (all tiers?)
Stun not working (all tiers?)

**Comment by taelon875** [comment]
Mind shield also may not be working as well.

**Comment by taelon875** [comment]
Mind Shield doesn't refire immunity once it expires.

**Comment by givemedeath** [comment]
Not sure if this is intended or not but force powers interrupt actions and cause flatfooted.

- if you are in combat and use a force power, it will play brief cast animation and then cancel all actions leaving you flatfooted

- if running using the keyboard it pauses briefly but otherwise ok. if running by clicking then using it mid run then it works as above

**Comment by givemedeath** [comment]
https://github.com/zunath/SWLOR_NWN/blob/881f9d10f02a101a1622b7d2ca33346035fa53f1/SWLOR.Game.Server/Service/AbilityService.cs#L259

I believe this is why some force powers aren't working. They exhibit the following error in the server console:

EVENT ERROR (C#)
MessageHub: 0c60ad04-1e3a-4b93-8ac7-91532bee3c12
**
 EXCEPTION:

Exception type: System.DivideByZeroException
Message       : Attempted to divide by zero.
Stacktrace:
  at SWLOR.Game.Server.Service.AbilityService.ProcessConcentrationEffects () [0x000a4] in <e03824ca845d4314843f916bb160cf64>:0
  at SWLOR.Game.Server.Service.AbilityService+<>c.<SubscribeEvents>b__5_3 (SWLOR.Game.Server.Event.SWLOR.OnObjectProcessorRan message) [0x00000] in <e03824ca845d4314843f916bb160cf64>:0
  at SWLOR.Game.Server.Messaging.Subscription.Handle[T] (T message) [0x00017] in <e03824ca845d4314843f916bb160cf64>:0
  at SWLOR.Game.Server.Messaging.MessageHub.Publish[T] (T message) [0x0006b] in <e03824ca845d4314843f916bb160cf64>:0

**Comment by taelon875** [comment]
Rage Drains Hp per tick not round.

**Comment by zunath** [comment]
Specialization restrictions / DM approval need to be added to the force abilities as needed.

**Comment by zunath** [comment]
Grant +1 AC for every 20 skill ranks in armor, when that armor type is equipped.

**Comment by zunath** [comment]
Outstanding issues that still need to be addressed:

Mon Cal Amphi-Hydrus no longer use dark force powers.
Components/Enhancements needs to be reviewed to cut out any unused/old properties.

"Not sure if this is intended or not but force powers interrupt actions and cause flatfooted.

    if you are in combat and use a force power, it will play brief cast animation and then cancel all actions leaving you flatfooted

    if running using the keyboard it pauses briefly but otherwise ok. if running by clicking then using it mid run then it works as above
"
Specialization restrictions / DM approval need to be added to the force abilities as needed.

Everything else has been looked at and needs to be retested. I believe a majority of them were due to mismatched IDs in the 2das. Will update test again and then I need you guys to run through and check these out again. Will work on the outstanding issues in the meantime.

**Comment by taelon875** [comment]
Force Stun 3 Crashes Server on use.

**Comment by taelon875** [comment]
Force Stun Series isn't costing FP.

**Comment by taelon875** [comment]
Throw saber works with ranged weapons, maybe it should be restricted to melee only if we want to allow other weapons.

**Comment by taelon875** [comment]
Throw saber also works unarmed.

**Comment by taelon875** [comment]
Cooldown Reduction Runes say they add cast time,  and they also do not reduce cooldowns.

**Comment by taelon875** [comment]
[powergloves.zip](https://github.com/zunath/SWLOR_NWN/files/3299489/powergloves.zip)
Late Addition to the Melee Balancing because I am forgetful.

**Comment by taelon875** [comment]
Players with over 120 force skill will have additional left over for redistribution when they are putting points in and is unable to spend the points because of the 40 Max distribute cap.

**Comment by taelon875** [comment]
Rename Battle Meditation to Battle Insight to avoid QQ

**Comment by taelon875** [comment]
Force Issues:
Mind Shield Cooldown is 10 Minutes should be 5
Confusion Cooldown is wrong.
Confusion Still doesn't work.
Cooldowns for Lightning, and Drain life are wrong, they shouldnt have one, currently 10 minutes.(Unable to test to confirm)
Cooldown for Breach is wrong 10 minutes instead of 10 seconds. (Unable to Test to Confirm)
Cooldown for Throw saber is wrong is 10 minutes should be 10 seconds.


Battle Insight:
First level gives Battle Insight II Feat, it is applying the 5 AC/AB but the AC is stacking each time.
Cooldown is 10 minutes, should be 30 minutes.
It is applying AC/AB to the caster it should be taking it away.

**Comment by taelon875** [comment]
Guild masters are Hostile....

**Comment by taelon875** [comment]
On Combat with battle Insight Server Crashes.

**Comment by taelon875** [comment]
Nearby players get told of player deactivation of concentration ability.

**Comment by taelon875** [comment]
Rage doesn't give xp.

**Comment by taelon875** [comment]
Can use non-concentration abilities while other concentration abilities are up.

**Comment by taelon875** [comment]
Armor scaling damage immunity forces bad Strref damage immunity

**Comment by taelon875** [comment]
Hitting Over 500 Skill Points Killed all Skill  Points

**Comment by taelon875** [comment]
Changing item appearance with weapons eats the item.
Shield Boost Removed HP....

**Comment by taelon875** [comment]
Sneak Attack doesnt do more damage.

**Comment by taelon875** [comment]
Cooldown reduction is too good?

**Comment by KendaricSwlor** [comment]
Mods can't be installed into "lightfoils" no matter what perk rank you have. Tested with Cooldown II mod, received the message "required rank 7, your rank 0" despite having 7 ranks in the Engineering mod perk.

**Comment by KendaricSwlor** [comment]
Armor mods are listed as red mods (like they are on live) but produce a yellow +AC mod (despite requiring red crystal clusters). Also, the installation message read "installed into prismatic slot".

**Comment by zunath** [comment]
Saber throw turns you to a male phenotype, so it breaks arm and head placement on females, if you change areas it fixes this for others but not yourself.

**Comment by KendaricSwlor** [comment]
Since Ugnaughts lack their hair color restriction here' a list of suitable colors:

16, 17, 18, 19, 62, 120, 128, 164, 166, 168

**Comment by YellowKingThe** [comment]
Force heal is costing 4fp per six seconds, not one fp persecond.
Xp is way too low to level it in a reasonable manner. You will be seeing most likely double diget xp in the time it takes to get 400 xp through killing things.
I would say do it at 10*amount healed. It may be easier to level then other things at high level, but that is a small price to pay for not having to grind for 2xp per second at low level.

**Comment by YellowKingThe** [comment]
Force xp is way too low.
Alter and Sense are both basically impossible to level, alter can only be used on mynocs currently at level 1, and sense can only be leveled by people speaking other languages.

**Comment by zunath** [comment]
RE: "Force heal is costing 4fp per six seconds, not one fp persecond"

To keep the spam down, your FP won't be spit out to the combat log on every tick. It'll display on every sixth tick (with a few exceptions, iirc). Is it possible the timing of the message is throwing you off?

**Comment by zunath** [comment]
RE: "Alter and Sense are both basically impossible to level, alter can only be used on mynocs currently at level 1, and sense can only be leveled by people speaking other languages."

Alter has all kinds of options. Throw Saber, Force Push, Force Heal are all low-level. Some of those unlock at 10 so that might be part of the issue, but I think with a boost to XP on force heal it'll be fine.

Sense is definitely a problem. We likely need another force ability that can be used in combat for that skill. Might need to pull something from phase 2 or create something new to cover that.

**Comment by KendaricSwlor** [comment]
The pelvis part of the light armor doesn't exist for Ugnaughts. This will likely be the case for a good number of parts as well, since we didn't have a race using the dwarf model before.

**Comment by zunath** [comment]
I've sent that particular model to Acidchalk for fixin'. I'm having TYK put together a list of the other broken parts so he can fix those too. Anyone who wants to help with that effort, let me know!

**Comment by KendaricSwlor** [comment]
The description for the Force Sense skill lists Force Stun as an example, but the actual Furce Stun ability is Force Alter.

**Comment by KendaricSwlor** [comment]
The Cairnmog Spine still has the "Light Potency Up" property which is no longer used to my knowledge.

**Comment by KendaricSwlor** [comment]
The cardmaster dialog has unrecognized tokens in several dialog options, notably in the "What is Rimer" and "They stuck you in the hallway, huh?" NPC responses.

**Comment by KendaricSwlor** [comment]
Force Insight seems bugged, it yields no exp and appears to grant +18 AB at rank 1 (should be +3 AB). I need someone to confirm it though...

**Comment by taelon875** [comment]
Change Force Abilities XP Gains to reflect Sheet:
Force Speed : XP granted = skill level x 10 + 50
Absorb Energy : XP granted = damage reduced * 3
Force Body : XP granted = HP converted * 2

**Comment by taelon875** [comment]
Is the AC scaling for armor was put in, it is not working.

**Comment by taelon875** [comment]
DM command to change force specializations.

**Comment by YellowKingThe** [comment]
Rimmer spectator exit does not work.

**Comment by taelon875** [comment]
[BackloggedERFS.zip](https://github.com/zunath/SWLOR_NWN/files/3364104/BackloggedERFS.zip)
These should be a majority of the backlogged ERF files that were given to me to put in the server over the past few months.

**Comment by taelon875** [comment]
Player Reports Ugnaught Robe issues: (misapplied textures, invisible body parts etc,)
11 , 12, 101, 116, 195, 198, 201-203, 221, 222, 226, 227, 230, 234, 235, 255

**Comment by Terallis** [comment]
Distributing perk levels into languages at start stops at 19/20 ranks. All options to distribute more perks doesn't appear at all to make it go higher. 40 perk ranks are available from the start, so it's not due to lack of points to spend.

**Comment by zunath** [comment]
Address the skills being divided by 8.

**Comment by givemedeath** [comment]
Force Heal keeps burning FP after fully healed.

**Comment by taelon875** [comment]
AC Mod sockets don't seem to work on light shields.

**Comment by YellowKingThe** [comment]
Amphi-Hydrus no longer have force abilities through the normal system. They have 5/day drain life instead, and it does nothing.
