### ISSUE TITLE
GAME: Add Shurikens and Darts

### ISSUE THREAD

**Issue by givemedeath** [zunath/SWLOR_NWN#910]

**Comment by givemedeath** [comment]
Item templates for shurikens with properties mirroring the tiered shortsword based vibroblades.

[swlor_shurikens.zip](https://github.com/zunath/SWLOR_NWN/files/3268094/swlor_shurikens.zip)

**Comment by givemedeath** [comment]
Item templates for darts with properties mirroring the tiered shortsword based vibroblades.

[swlor_darts.zip](https://github.com/zunath/SWLOR_NWN/files/3268226/swlor_darts.zip)

**Comment by zunath** [comment]
Do we want to make these unlimited use? It seems kind of crappy you can put a mod into them, but eventually use them up.

**Comment by YellowKingThe** [comment]
I am not sure you can make them unlimited.
If possible they should use the same durability system as other items.

**Comment by zunath** [comment]
We can work some magic with it I think. If they're unlimited, they would be subject to durability.

**Comment by YellowKingThe** [comment]
Well my opinion is make them use the same system as every other item.
Some things to keep in mind, they should get str to damage by default, so be cautious of tacking too much extra damage onto them.
But their base damage statistics are also pretty bad.

**Comment by zunath** [comment]
I've changed the shuriken, dart, and throwing axe stack sizes to 1 and prevented them from decrementing on use with NWNX. 

Also updated all their mod slots to be in line with the rebalance stats (GMD made them before that was released). 

Added them to the applicable stores on CZ-220, Veles, and in the Hunter's Guild stores.
