### ISSUE TITLE
GAME: Implement Grenades

### ISSUE THREAD

**Issue by givemedeath** [zunath/SWLOR_NWN#911]

**Comment by zunath** [comment]
https://docs.google.com/spreadsheets/d/14IJbSfcN-kDHfbMEWkYjE2upx-XSDUZ3-QrmFHLwmEY/edit#gid=1684605331

Grenade info on tab 2

**Comment by givemedeath** [comment]
Release ready ERF:

Contains smuggler merchant blueprint update and the grenade item blueprints. Only the basic variant of each grenade is available in the smuggler merchant. The rest will be added to crafting blueprints later.

[grenades_gmd_v1.zip](https://github.com/zunath/SWLOR_NWN/files/4802130/grenades_gmd_v1.zip)
