### ISSUE TITLE
GAME: Lightfoils don't receive lightsaber perks

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#940]
Lightfoil doesn't recieve any lightsaber perks.	Basic Training Foil	viscaradeepmount	219.639831542969	219.119522094727	5.05762672424316	171.599975585938	2019-07-11 07:23:51.5366667

**Comment by givemedeath** [comment]
Is this when using the katana based training foil?

**Comment by zunath** [comment]
I believe this is referring to the longsword-based training foil.

**Comment by givemedeath** [comment]
This is a strange one. It is pretty inconsistent in how it displays in the character sheet for crit range etc.
 
I can confirm that the proper feats are being added and the code for checking item types doesn't appear to have any issues.

One thing i've noticed that does seem to be consistent is equipping a Basic Training Foil that is too high level and gets an ab debuff will properly display the right values in character sheet for crit range etc. One that is within level range, and thus no debuffs, doesn't seem to display the right values in the character sheet for crit range etc.

Note that using Force Insight will cause the above scenario with an in level range foil to display correctly on the char sheet.

**Comment by zunath** [comment]
Char sheet is 100% unreliable. If the perks are being granted and the combat log shows them working, then I say we close this one out and chalk it up to the normal char sheet issues.

**Comment by givemedeath** [comment]
Confirmed to be working then!

**Comment by zunath** [comment]
Thanks!
