### ISSUE TITLE
Display "Back Button" on all applicable pages in all conversations

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#95]
When using the Head/Hair Color option add Back to the bottom of each page. This helps so the play will not have to scroll to the end of the list in the event they have the color they need. They could always end, but it is a ease of use thing so they do not have to rechat the command.

**Comment by zunath** [comment]
This is actually a pretty substantial work item believe it or not. All of the conversations use this style of adding a back button on a per-menu basis. I've been wanting to do this for a while but have been putting it off. I'm going to rename this ticket to better reflect that it affects all conversations - not just the customize menu.
