### ISSUE TITLE
GAME: Training Foil Top Part 0

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#954]
14	B11FC015-1B75-48AA-9AD9-C90E1CB03C9F	4C8C9CCD-C32A-4A62-AEB7-C7657968D2AD	UPFY7PLP	 when trying to change appearance of blue training foil staff > top > part #0 results in the saberstaff disappearing	Dax Tanaas	apartment_002	6.58210897445679	14.0417928695679	0	41.5999946594238	2019-07-23 03:42:06.1933333

Not sure why part 0 is showing in the first place, but we need to remove it if it's missing.

**Comment by givemedeath** [comment]
This should be closed as those aren't changeable as of 7/26.
