### ISSUE TITLE
GAME: Absorb Energy I doesn't grant XP

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#956]
7C84B07B-512A-45E3-BAF8-D090BD917912	6AB70A69-0D9B-4511-9D3C-9F77F5B66ED9	UPWNHFPR	 absorb energy 1 does not give xp or cost fp or really seem to do anything	Veras Gristham	czs220_maintlvl	31.4571838378906	39.8669700622559	-0.499999493360519	100.91633605957	2019-07-24 19:16:33.6100000

This happened in the maintenance level, so make sure it's not a situation where the player is using the ability on a droid and the ability doesn't work on droids. If that's what's happening, make sure an error message is sent back to the player explaining why.

**Comment by givemedeath** [comment]
This is not currently an issue.
