### ISSUE TITLE
GAME: Force Rites quest dropping two sabers

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#957]
66B025FF-28D8-40F3-9F99-031E76FDFA64	082855F6-C72F-42B2-8677-3CD34420C96A	UPD4UDDC	 when killing yourself at the end of the last rites quest, your double drops an npc lightsaber item	Nivi Unavi	visc_forcevision	79.232421875	101.202644348145	3	42.3000030517578	2019-07-25 03:33:28.3033333

This is an old bug I thought we took care of. But it seems to be happening. It's the only one I know of that's in NWScript, so be sure to check there and not in the C# code base. Bonus points if we migrate it to C#.

**Comment by givemedeath** [comment]
The items were removed automatically after exiting the quest area. Guess this should be closed.
