### ISSUE TITLE
GAME TEST: Questing Issues

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#965]
Refinery Trainee quest offers 'Continue' as a reward I think this is supposed to be a red mod reward not that. Clicking on continue also just closes and completes the quest.

**Comment by taelon875** [comment]
Select Reward doesn't work on 'The Colicoid Experiment' Quest

**Comment by taelon875** [comment]
Datapad Retrieval quest does not give credit reward when selected.

**Comment by zunath** [comment]
https://i.gyazo.com/thumb/1200/8e819aa62e58be60df1421076afa33e8-png.jpg

Probably a fame prereq issue. Shouldn't let the player accept the quest if they don't meet the requirements. Tal'gar Meyne is the NPC

**Comment by Cavcode** [comment]
![image](https://user-images.githubusercontent.com/25558825/63214132-f3aabd00-c0d9-11e9-998d-ae3784a3b8e6.png)
Hunter's kath hound meat quest seems to be acting like a crafting quest. Does not allow meat dropped from an enemy to be turned in (as seen in the combat window).

**Comment by zunath** [comment]
All the hunter's guild quests are looking for crafted items. I just fixed them but haven't deployed. Same deal with the other reported bugs. Will update later.

**Comment by zunath** [comment]
Removed the fame requirements from quests. Going to close out this ticket since I think all issues have been resolved. If there's more, open up a new ticket.
