### ISSUE TITLE
GAME: Unrestrict Skills From Armor

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#972]
Allow players to use skills unrestricted to armor. AKA Rapid shot in force or heavy armor.

**Comment by zunath** [comment]
We need to discuss what the removal of these restrictions looks like. I agree they should be removed, but there should be some type of scaling in place to make it consistent with other scaling methods. 

I.E: Clarity, for example, has a force armor restriction in place. We don't want someone to use heavy armor to receive the same level of benefits. So what do we do in that case? Reduce the effectiveness by 50% for light and 75% for heavy?

These are all the perks I know of which have these restrictions:

Hide
Evasiveness
Deflect Damage
Point Blank Shot
Evade Blaster Fire
Dodge
Expertise
Mobility
Rapid Reload
Rapid Shot
Rapid Toss
Shield Boost
Speedy Armorsmith
Provoke
Armor Mod Installation
Sneak Attack
Armor Blueprints
Battlemage
Clarity
Sturdiness
Armor Repair
Deflect Blaster Fire

We need to establish the scaling on every single one of these perks.

**Comment by taelon875** [comment]
Could we leave the ones that are directly on armor to be restricted as it is now, but just open all other open to all armor types? I feel the combat ones should be free to use on any armors.

**Comment by zunath** [comment]
Ok so that means we're removing the restrictions on the following:

Point Blank Shot
Evade Blaster Fire
Rapid Reload
Rapid Shot
Rapid Toss
Sneak Attack
Battlemage
Deflect Blaster Fire

I don't think any of these would require scaling in that case.

**Comment by taelon875** [comment]
That seems fair, and we can look into the others if needed at a later date.
