### ISSUE TITLE
GAME: Force Insight + Force Speed Cancellation

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_NWN#973]
FD1C5EBD-2D4C-47E1-A50F-F51E667C0C41	0A51B61D-510B-476A-8CCB-464A704AE9C6	QR6VYEKR	 force insight cancels out force speed when it shouldn't.	Althea	viscarawildlands	179.643325805664	272.249908447266	-0.0173142831772566	1.00001096725464	2019-08-14 07:30:50.9400000

792E6D0B-4FEF-47D8-B8F7-5C7C5225955F	FCCF57A7-6BBE-473A-8C99-7D7C8FF8D6D7	UPWNHFPR	 force insight wears off too fast and will not give xp as a result because the attack is made without it.	Tran Illimar	viscarawildwest	125.843780517578	178.167922973633	14.5090885162354	338.765747070313	2019-08-17 00:25:22.2933333

**Comment by givemedeath** [comment]
Confirmed this is working as expected.
