### ISSUE TITLE
Quest Bug: CZ-220 Supplies - Scavenging

### ISSUE THREAD

**Issue by taelon875** [zunath/SWLOR_NWN#98]
The items you pull from the junk piles do not work for the quest turn in, says it is not required for the test.

Unless there is something you are supposed to do with them? If so we might need to consider adding that into the journal logging.

https://gyazo.com/7230d30ea6f7e99c28f51d5d70fea6a1

**Comment by zunath** [comment]
This appears to be fixed with the code restructuring I did today.
